### PR TITLE
remap shortcuts for previous/next tab & plot commands

### PR DESCRIPTION
**Pull request by jjallaire**
We are in a losing battle with desktop window managers around attempting to use the arrow keys in shortcuts. Recently found out that arrow keys were being used by Windows 8 for switching workspaces. This PR uses the F11 and F12 keys rather than the arrow keys (logic being that they are still conveniently located and are not used at all by browsers or desktops).

### CODE REVIEW

**Comment by kevinushey** [comment]
I would strongly prefer adding these keyboard shortcuts in addition, rather than instead, of the current shortcuts. At least, for me, I am somewhat 'attached' to the current keybindings (as someone who doesn't use an OS whose window manager grabs those key combinations), so I would be sad to see them go -- and I imagine many others will be too.

Any thoughts on adding, instead of remapping?

**Comment by rmflight** [comment]
Instead of remapping to function keys, is there any way to make them user settable instead of hard-coded, so that users can change them to something that doesn't interfere with their OS settings?

**Comment by jjallaire** [comment]
Yes, we are hoping to make all the keys re-mappable at some point soon (not
this release but hopefully the next release).

**Comment by jjallaire** [comment]
FYI restored them as undocumented bindings: https://github.com/rstudio/rstudio/commit/057c2fa71a3bef8133d6b0bc633a525b914817ef

**Pull request merged**
