### PR TITLE
fix building with boost 1.75

### PR DESCRIPTION
**Pull request by JanMarvin**
### Intent

This pull requests solves building rstudio with boost 1.75 which recently dropped in Arch Linux.

### Approach

The required header files were included as well as the required namespace. 

### QA Notes

This builds with my rstudio [PKGBUILD](https://github.com/JanMarvin/rstudio-archlinuxpkg) (this PKGBUILD includes another boost patch, though I am not sure what that was fixing [lost track of rstudios development a while ago]). 

I expect this to be backward compatible if the included header files exist in previous boost releases, but I have not tested this. I have also not tested this with the included rstudio boost.

I have signed a contributor agreement a long time ago.

### CODE REVIEW

**Comment by kevinushey** [comment]
Thanks for the PR!

We were getting away with this via this in CMake:

https://github.com/rstudio/rstudio/blob/df65430f3d039dd2074a77e737e7ab44cb042130/src/cpp/CMakeLists.txt#L36-L38

Is that effectively removed from Boost 1.75? If so, we might want to remove that line as well and ensure we're properly using Boost's placeholders in a forward-compatible way.

**Comment by JanMarvin** [comment]
Thanks for the hint (I didn't know the reason boost for the behavior change). Presumably including placeholder is not required and using the macro is no longer possible according to this commit:

https://github.com/boostorg/bind/commit/2797f0dc33caaae126a416bf613bd11267ba3353

**Comment by JanMarvin** [comment]
That's a hella lot of files I touched now. Did not build it, is that what you wanted @kevinushey ?

**Comment by kevinushey** [comment]
Oof, thanks! I didn't expect it would've required changes in so many source files, but I guess that ultimately makes sense.

We're currently in the process of wrapping up a 1.4 release so I don't think we can merge this immediately, but will plan to do so as part of the next 1.4 patch release (which should be released relatively soon after the initial 1.4 release).

**Comment by JanMarvin** [comment]
Happy to help. Just to clarify, my first commit actually fixes a build error I was seeing, the second commit merely fixes warning messages. Good luck with the release and stay healthy

**Comment by jmcphers** [comment]
@JanMarvin I pulled your branch and built it locally w/o issue. I'm going to rebase your PR onto our current patch release branch, `v1.4-juliet-rose`, and merge it there. That branch will be merged to `master` shortly after RStudio 1.4 is released.

**Comment by jmcphers** [comment]
@JanMarvin Thanks very much for the contribution!

**Comment by Enchufa2** [comment]
Did you build this against Boost 1.75? I've incorporated the patch in Fedora rawhide, which contains Boost 1.75 now, and compilation fails. I think we still need `-DBOOST_BIND_GLOBAL_PLACEHOLDERS`, which was removed in this PR.

**Comment by JanMarvin** [comment]
yes, I build current master with [boost 1.75](https://archlinux.org/packages/extra/x86_64/boost/)

**Comment by Enchufa2** [comment]
I see the following applying this patch to current release (1.4.1103):

```
/builddir/build/BUILD/rstudio-1.4.1103/src/cpp/session/SessionConsoleProcessSocketTests.cpp: In member function 'bool rstudio::session::console_process::{anonymous}::SocketClient::connectToServer()':
/builddir/build/BUILD/rstudio-1.4.1103/src/cpp/session/SessionConsoleProcessSocketTests.cpp:249:55: error: '::_1' has not been declared
  249 |                                           &client_, ::_1, ::_2));
```

Any idea why?

**Comment by JanMarvin** [comment]
maybe someone introduced a new boost function not covered by this pull request? But I did build yesterdays master, which contains this patch.

**Comment by Enchufa2** [comment]
Nope, that was there in your PR: https://github.com/JanMarvin/rstudio/blob/a73589c69c62b55935c2b0936bbe7ffe52fe0a49/src/cpp/session/SessionConsoleProcessSocketTests.cpp#L249. For some reason, `::_1` does not found the placeholder in the global namespace. I'm rebuilding with `_1` instead, which should use the websocketpp placeholder. Let's see.

**Comment by JanMarvin** [comment]
If you could share a link to the PKGBUILD or how it's called in Fedora, I could have a look. Right now I'd say that applying the pull request somehow did not work as expected. My build files are [here](https://github.com/JanMarvin/rstudio-archlinuxpkg/tree/master/rstudio) if you want to have a look.

**Comment by Enchufa2** [comment]
Using `_1`, `_2` instead of `::_1`, `::_2` and removing `using websocketpp::lib::placeholders::_1;` and `using websocketpp::lib::placeholders::_2;` did the trick. It could be the compiler version, the flags... I don't know. But anyway, it makes no sense to declare websocketpp's placeholders and then avoid them with `::` to use boost ones. I'll open another PR for this.

**Pull request merged**
