### PR TITLE
better handle attempts to save / re-open mis-encoded documents

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/rstudio/issues/6709.

This PR bundles a few changes together:

1. We disable the autosaver when first initializing a document, as we want to avoid "spurious" document saves when the document is first opened. This is especially important for the case where the document has been opened with an incorrect encoding (and so the repesentation of that document within the RStudio editor is incorrect).

2. We handle exceptions that occur when attempting to save a document diff, since `.replace()` can throw an exception here.

3. When attempting to re-open a document with a different encoding, we no longer attempt a save before re-opening the document. This is for the same reason as in (1) -- if the user is attempting to re-open a document in a particular encoding, it's likely because the document was not correctly decoded in the current encoding, and so it's unlikely the user wants to save the document before re-opening.

Candidate for v1.3-patch backport, which is a bit uncomfortable given the lower-level changes here but I believe it's necessary.

### CODE REVIEW

**Comment by kevinushey** [comment]
In fact, given that this PR prevents users from getting into a crash loop upon opening a document that's not UTF-8 encoded (or encoded in the default system locale), it might be worth considering even for v1.3.

**Comment by jmcphers** [comment]
> it might be worth considering even for v1.3.

Was this problem introduced (or exacerbated) in 1.3? At this point 1.3 is taking only recall class issues (so if we lived with this in 1.2 with little noise it probably doesn't make the cut).

**Comment by kevinushey** [comment]
It was introduced in v1.3; v1.2 is unaffected by the associated issue.

**Comment by kevinushey** [comment]
Squashed and merged with master; cherry-picked to v1.3 and v1.3-patched:

https://github.com/rstudio/rstudio/commit/1549686ff16bde03eaef5ddac3bbf7be42e1dfec
https://github.com/rstudio/rstudio/commit/9b635d8bcc83e6c58712a15b9412e35fd7f0063d

**Comment by jmcphers** [comment]
Thanks! Builds underway.

**Pull request merged**
