### PR TITLE
(1.1 candidate) Set ANSI color environment variables before running .Rprofile

### PR DESCRIPTION
**Pull request by gtritchie**
For code running via `.Rprofile` to know if the RStudio console is supporting ANSI color sequences, set the `RSTUDIO_CONSOLE_COLOR` environment variable before `.Rprofile` runs.

Verified that console color supports still works as expected, that the `Tools/Global Options/Code/Display ANSI Escape Codes` setting is being respected, and that the environment variable is indeed now set so code in .Rprofile can see it.

### CODE REVIEW

**Comment by jjallaire** [comment]
I'm a bit worried that at the time we call this we don't yet have access to the uiPrefs (because setUiPrefs hasn't been called yet). But perhaps there is somewhere else I'm not seeing that the uiPrefs get initialized? @jmcphers What is your take on this?

**Comment by gtritchie** [comment]
I did try it and the environment variable was being set (or not set) as expected based on having an .Rprofile that echoed back the environment variable. I didn't try all combinations of platforms and so on, so would need considerably more testing!

**Comment by jjallaire** [comment]
I don't think we need to test further, just do the analysis. Where do the UI prefs get initialized on startup? I just want to make sure this happens before we call sync b/c it relies on the UI pref already having been read into memory.

**Comment by gtritchie** [comment]
`userSettings().initialize()` is called before getting to the added `syncConsoleColorEnv`.
https://github.com/rstudio/rstudio/blob/b1d31b9eaf1a6cc05fe8aac6e04354f501bee7a6/src/cpp/session/SessionMain.cpp#L1719

**Comment by jmcphers** [comment]
If we wanted to be paranoid here we could refuse to manipulate env vars (with a warning) in `syncConsoleColorEnv` if the user settings aren't initialized, but as @gtritchie pointed out the only existing use of this function demonstrably occurs after initialization so I think we're safe here.

**Pull request merged**
