### PR TITLE
Minor tweaks to R mode indentation

### PR DESCRIPTION
**Pull request by kevinushey**
This PR further refines indentation in R modes, by conditionally indenting on assignment operators when appropriate.

Briefly, the indentation code works as follows:

1. Find an opening `[`, `(`, or `{` to provide for indentation.
2. If we find a `(` or `[`, we can use that for indentation (re-using pre-existing indentation code),
3. If we find a `{`, then we backtrack and attempt to first indent on an assignment operator (`=`, `<-`) first; otherwise, we indent based on the found `{` (plus indentation).

I also added some new tests to the R auto-indent and we now pass on all tests.

One of the main 'features' in this PR -- if we choose to vertically align, then we indent:

```R
if (a &&
    b &&
    c)
```

and

```R
plot(x = x +
         1,
     y = y +
         2
)
```

; ie, we can better discriminate on what is providing the 'scope' for a current expression.

### CODE REVIEW

**Comment by jjallaire** [comment]
It looks to me like all of the changes in SessionRCompletions.R are whitespace. Is that correct? In general I'd like to keep whitespace/reformatting changes in their own commit/PR so they don't obscure the other code to be reviewed (let's of course leave this PR as-is, more of a note for future work)

**Comment by jjallaire** [comment]
This is a pretty low level change for right before a preview release but my instinct says in spite of the large diff it's relatively safe. Perhaps @jmcphers and you could go over the change realtime just to make sure we have one more pair of eyes on it before merging. If you both feel it carries too much risk we can just put it on the same branch we are using for Ace.

**Comment by kevinushey** [comment]
Right, the large diff is a bit of a misnomer (most of it is just a re-arrangement of pre-existing code); the new branches introduced are relatively risk-free. @jmcphers and I will go over it together later today.

**Comment by kevinushey** [comment]
After reviewing with @jmcphers, we've decided to leave this out for now -- the gain is relatively small, and although the regression risk is pretty small, it's better to just be safe. Let's merge after the first preview release.

**Comment by jjallaire** [comment]
Okay, sounds good!

**Comment by kevinushey** [comment]
Merged into (https://github.com/rstudio/rstudio/tree/v0.99-preview-2) (https://github.com/rstudio/rstudio/commit/9529c500782d48860feb5ad3a097c83447a794e7)

**Pull request closed without merging**
