### PR TITLE
Make getDollarNamesMethod find super classes

### PR DESCRIPTION
**Pull request by flying-sheep**
I also simplified excludeBaseClasses functionality by relying on `mode`.

### CODE REVIEW

**Comment by jjallaire** [comment]
Thanks. Could you send us a contributor agreement as described here: https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

**Comment by flying-sheep** [comment]
sure! other projects allow signing digitally without printing. is there some way to do that here as well?

also: are there tests for `.rs.getDollarNamesMethod` that I can add to?

**Comment by kevinushey** [comment]
Unfortunately we don't yet have automated tests for the completion system.

Can you confirm that we retrieve the correct completions for S4 objects inheriting from `environment` and `list` with this PR? E.g.

```
setClass("Environment", contains = "environment")
envir <- new("Environment")
envir$a <- 1
envir$b <- 2
envir$<TAB> ## should see completions for 'a', 'b'
```

**Comment by flying-sheep** [comment]
i could create tests. it would be as easy as:

```r
setClass("Environment", contains = "environment")
envir <- new("Environment")

stopifnot(identical(.rs.getDollarNamesMethod(envir), utils:::.DollarNames.environment))
```

**Comment by jmcphers** [comment]
Closing due to inactivity (feel free to reopen once CLA is signed and comments from @kevinushey  are addressed)

**Comment by flying-sheep** [comment]
hi, i signed the CLA earlier today, but i can’t reopen this, only you can

**Comment by jmcphers** [comment]
Thanks! @kevinushey could you review/merge as appropriate?

**Comment by kevinushey** [comment]
Thanks!

**Comment by flying-sheep** [comment]
great!

**Pull request merged**
