### PR TITLE
add support for 'clean' restart

### PR DESCRIPTION
**Pull request by kevinushey**
Addresses https://github.com/rstudio/rstudio/issues/2841.
Addresses https://github.com/rstudio/rstudio/issues/11378.
Will need follow-up in https://github.com/rstudio/rstudioapi/issues/95 post-merge.

This adds a commonly-requested feature, and allows for users to restart the R session programmatically into a fresh / "clean" state.

For testing, one can confirm that using the "clean" version of a restart ensures that no packages or variables from the previous session are saved and restored.

```
> library(dplyr)
> loadedNamespaces()
 [1] "methods"    "utf8"       "R6"         "tidyselect" "magrittr"   "glue"       "tibble"     "pkgconfig" 
 [9] "dplyr"      "generics"   "lifecycle"  "utils"      "cli"        "fansi"      "vctrs"      "graphics"  
[17] "grDevices"  "stats"      "compiler"   "base"       "rstudioapi" "tools"      "pillar"     "rlang"     
[25] "datasets"  
> .rs.api.restartSession(clean = TRUE)

Restarting R session...

> loadedNamespaces()
[1] "compiler"  "graphics"  "tools"     "utils"     "grDevices" "stats"     "datasets"  "methods"   "base"  
```

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
Nice, LGTM!

**Comment by benfarmer05** [comment]
Hello, I am trying right now to run .rs.restartR() on an M1 Macbook 2020 (RStudio Version 2024.04.2+764 (2024.04.2+764)), and it does not properly clear variables or loaded packages. I have to run rstudioapi::executeCommand("restartR") to achieve that functionality. I am cross-posting this in https://github.com/rstudio/rstudioapi/issues/95

**Comment by ronblum** [comment]
@benfarmer05 What do you get with `.rs.restartR(clean = TRUE)` ?

**Comment by benfarmer05** [comment]
That works great, thanks I'll use it instead!

**Pull request merged**
