### PR TITLE
Node 18.20.3 for Chocolate Cosmos

### PR DESCRIPTION
**Pull request by gtritchie**
### Intent

Addresses [Update node.js in Chocolate Cosmos #14731](https://github.com/rstudio/rstudio/issues/14731)

### Approach

Updated scripts, uploaded node to cdn.

### Automated Tests

NA

### QA Notes

This node is used by Copilot, so sanity-checking that functionality is recommended.

### Documentation

NA

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by jeffvroom — APPROVED** [review]
LGTM!

**Comment by gtritchie** [comment]
Marking as draft pending decision on which node version to use, also while I investigate why the check build failed.

**Comment by gtritchie** [comment]
The build was failing because I uploaded the `*.xz` variants for Linux instead of the `*.gz` files. Fixed.

**Comment by gtritchie** [comment]
Un-drafted it so another check build will run.

**Review by MariaSemple — APPROVED** [review]
LGTM!

**Pull request merged**
