### PR TITLE
Add project reload message on R session crash

### PR DESCRIPTION
**Pull request by timtmok**
### Intent
Addresses #9949 
Update the session crash message to prompt the user to check that the project is loaded after restarting the session.

### Approach
String update

### Automated Tests
None

### QA Notes
Sample C++ code:
```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void crash() {
  abort();
}
```

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by timtmok** [comment]
@kevinushey I don't know if there's anything else to do for a string change to generate a change list for future translation. From what I understand, French translation have been made by community contributors.

**Comment by kevinushey** [comment]
LGTM!

@gtritchie, do we have any "official" communication channel for requesting updates to the incoming French translation?

**Comment by jgutman** [comment]
Should we open a separate issue to have someone update the corresponding French translation to match?

**Comment by romainfrancois** [comment]
Sure. Feel free to ping me for things like this, for this one I'll just make another pr. 🇫🇷

**Pull request merged**
