### PR TITLE
performance, errors, visuals and other improvements to data import

### PR DESCRIPTION
**Pull request by javierluraschi**
The main change from this PR is to improve performance of data import by caching files form URLs into the local file system. This is accomplished on the preview code and import code to be consistent (otherwise users would have to hit another long delay to download the file again after they validate the preview). There are also additional improvements that wrap up the feedback from the latest test pass.

I'm sending this as a new PR based on the last one to minimize code review churn.

Not too many design changes, but here is a quick preview for the off-by-1-px fix:

screen shot 2016-02-17 at 1 58 16 am

### CODE REVIEW

**Comment by jjallaire** [comment]
If it's straightforward to do so let's get this PR so it only shows the changes subsequent to the merging of the async preview PR.

**Comment by jjallaire** [comment]
The caching of downloaded files might be overreaching a bit as this code would fail to download updated versions of the dataset (unless we somehow use eTag based cache revalidation). Even though it seems like this is a very nice thing to do for users it might be more properly something done directly by users after the fact (or perhaps handled via a feature of the curl package)

**Comment by jjallaire** [comment]
Scratch that note about fixing up this PR, it looks like it mostly has incremental fixes on the last PR (all of which look fine). I do however think that we should reconsider whether the generated code should have download caching for the reasons mentioned above. @jmcphers What do you think?

**Comment by javierluraschi** [comment]
Regarding caching:
- **Refresh**: Good point. Let me invalidate the temp cache when the user clicks "update"; that way, if the file is stale, they can always click update themselves to retrieve the latest copy. Will send a small PR.
- **Code Generation**: There are definitely PROs and CONs on both sides; however, it still looks reasonable to use temp files. A PRO for no temp files in code generation is that it keeps things simple for URLs (Notice that this is a URLs only feature). However, with temp files in code generation we:
  1. Keep consistent imports: It could be the case that if the data is live, data types and other artifacts could change the data and cause unexpected consequences.
  2. Avoid duplicating downloads.
  3. Work even when WiFi is lost: If you see your preview you know it will import.
  4. Teach users how to cache files: I think this is a good practice for users that are changing the import code while using URLs, it takes time to download files so caching files seems sensible.

**Comment by javierluraschi** [comment]
Here is the PR: https://github.com/rstudio/rstudio/pull/591

**Comment by jjallaire** [comment]
I agree with your reasoning regarding the desirability of temp file based data caching however I think a few problems remain:

1. The hard coded temp file location requires that we not use R session temp files (because the directory will disappear when the session exits). This means those temp files will be long lived and have the invalidation problem I mentioned before.

2. Generating code with hard coded temp file locations is going to be a bit confusing for users as many of them will not be sophisticated enough to understand what's going on.

We could solve both of the above by NOT using temp files (rather using files that are in the current working directory). I think this would be much more understandable to users.

Also, there is a `cacheOK` argument to download.file. If this works well across platforms then the code could be further simplified to eliminate the interaction with the local filesystem entirely. If that doesn't do what we want then we could consider taking a dependency on the curl package if it has a nice cache-friendly download URL method.

Net: I'd like to preserve the performance and "best practices" wins you've got here with much simpler generated code.

**Comment by javierluraschi** [comment]
tried out `cacheOK` and `curl::`. `cacheOK` is `TRUE` by default; however, it still re-downloads the file once is downloaded. For `curl::curl_download`, I learned a bit about the options (`destfile`, `quiet`, `mode`) and I also empirically tried downloading the file twice, it downloaded the file twice still.

The code currently looks like this:

```
library(readr)
rows_file <- "/tmp/file1547364988393.txt"
if (!file.exists(rows_file))
    download.file(
        "https://data.consumerfinance.gov/api/views/s6ew-h6mp/rows.csv",
        rows_file)
rows <- read_csv(rows_file)
```

and it would be nice to have something like this instead:

```
library(readr)
rows <- read_csv(
    download.tempfile(
        "https://data.consumerfinance.gov/api/views/s6ew-h6mp/rows.csv"))
```

This function would have to create a hash out of the URL (or remember the URL-tempFiles mapping), download only the file if something changed in the server and retrieve the path to the cached file for further processing.

Wouldn't mind trying to push this change to `utils::` if we think this is interesting enough, but might make more sense to track this and consider this in future versions. Let me know.

**Comment by jjallaire** [comment]
Here's another proposal: let's add a function to the downloader package
(maintained by Winston) that has this behavior then depend on that.

**Comment by javierluraschi** [comment]
K, will follow this route. First step, send PR to Winston. Planning to work on this in the next couple days.

**Comment by jjallaire** [comment]
Okay, one tricky aspect of this will be the management of temp file names.
You'll want to use the R session temp directory of the user's session
(rather than the child session we use for async data preview). I think this
means that the download_tempfile function will need to respect either an R
option or an environment variable that tells it what temp directory to use
(the default being the R session temp directory). When doing the async
preview you'll then want to seed this value with whatever the session temp
dir of the user's R session is.

I think this whole scheme also probably bears one review with Jonathan
before plunging in.

**Pull request merged**
