### PR TITLE
Prefer system zlib.h over local

### PR DESCRIPTION
**Pull request by zachhannum**
### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

When `zconf.h` was removed in rstudio/rstudio#13641, it revealed an issue with the way we are including `zlib.h` in our `zlib.cpp` wrapper. We only want to use the local zlib.h if zlib is not installed on the system. This should only happen on Windows as we only build the embedded zlib _for_ Windows.

Otherwise, we were essentially including the local `zlib.h` file, even though the actual definitions would be defined by the system library (and in the case of centos7, was actually incompatible).

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

`z_size_t` is not expected to exist on the version of zlib on centos7 (and is incompatible with the embedded version of zlib we have locally).

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

N/A

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

N/A

N/A

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by GCRev — APPROVED** [review]
LGTM

**Comment by kevinushey** [comment]
This breaks the Windows builds, since RStudio expects to find `zlib.h` in the same directory there.

https://github.com/rstudio/rstudio/blob/main/src/cpp/core/zlib/zlib.h

Note also that this built version of zlib is only used on Windows:

https://github.com/rstudio/rstudio/blob/e32fb38f34af7cf3fd0fff630dba41cf79b69df5/src/cpp/session/CMakeLists.txt#L539-L540

so the correct fix here is to avoid compiling zlib on non-Windows platforms altogether:

https://github.com/rstudio/rstudio/blob/e32fb38f34af7cf3fd0fff630dba41cf79b69df5/src/cpp/core/CMakeLists.txt#L135

That line can probably be removed, or just moved to a Windows-specific block.

**Comment by kevinushey** [comment]
See also the comments here: https://github.com/rstudio/rstudio/blob/e32fb38f34af7cf3fd0fff630dba41cf79b69df5/src/cpp/core/zlib/CMakeLists.txt#L16-L20

**Comment by zachhannum** [comment]
I think the confusion here is that `zlib.cpp` is not a part of the zlib library (even though it's in the same folder). `zlib.cpp` was written by us as a wrapper around some of the zlib functionality. The change to `#include <zlib.h>` was so that the compiler would search the system path first instead of the local directory, but AFAIK it should still find the header file in the local directory as well.

**Comment by kevinushey** [comment]
Ahh! Thanks, you're right -- that threw me off.

**Pull request merged**
