### PR TITLE
ensure satellites update keybindings when changed

### PR DESCRIPTION
**Pull request by kevinushey**
Not quite ready for merge -- @jmcphers, can you help me finish this? I'm not quite sure how to explicitly fire an event from the main window to all satellites.

### CODE REVIEW

**Comment by jmcphers** [comment]
There is currently no specific mechanism for this so I'd add one on the `SatelliteManager` (you'll just need to enumerate the `ActiveSatellite` objects and `fireEventToSatellite` from `EventBus` on each). You could then remove the code specific to source windows, too.

**Comment by jmcphers** [comment]
One other thing you'll need to change: the `KeybindingsChangedEvent` needs to override `CrossWindowEvent.forward` to return `false` so that it doesn't get forwarded back to the main window.

In retrospect I think that the window event disposition should be an enum since we have enough cross-window events now that we can neatly categorize them (main to all satellites, main to satellite, satellite to main, etc.), although I don't think that should be part of this change.

**Comment by kevinushey** [comment]
Thanks for the guidance @jmcphers; it looks like things are working well now. Can you sanity check the PR and let me know if everything looks okay?

**Comment by jmcphers** [comment]
Looks good.

**Pull request merged**
