### PR TITLE
MonokaiDucks.css - added here as no `rstudio` dir

### PR DESCRIPTION
**Pull request by leerssej**
A Monokai wirh more prominent annotation, cursor, and selected text
highlighting (with colors related to Oregon Ducks color scheme)

### CODE REVIEW

**Comment by leerssej** [comment]
the `rstudio` dir is gitignored so I have added the file into the base directory one level up. Please let me know if there is somewhere else I should submit instead.

**Comment by jmcphers** [comment]
We do accept PRs for new editor themes, but you'll need to change the theme sources rather than the compiled CSS. You can see two examples of user-contributed theme PRs here:

Dracula - https://github.com/rstudio/rstudio/pull/1453

Material - https://github.com/rstudio/rstudio/pull/748

Hope this helps, and appreciate the contribution!

**Comment by leerssej** [comment]
Great! Thank you for the links - It may take me a few days to translate the
formatting in, but look forward to getting the theme properly submitted.

**Comment by jmcphers** [comment]
I'm closing this PR; feel free to open a new one once you've gotten the theme hooked up!

**Pull request closed without merging**
