### PR TITLE
Enable builds for newer Debian releases and SuSE

### PR DESCRIPTION
**Pull request by jmcphers**
This change enables two new builds from the containerized build system.

## Xenial (Qt 5.4.2)

We currently use a release of Qt which is built against `libgstreamer0.10` (a dependency of `QtWebKit`). Unfortunately, this library has been deprecated and has been entirely removed from the repositories in newer Linux distributions. The replacement is `libgstreamer1.0`; which is [not at all ABI compatible with libgstreamer0.10](https://abi-laboratory.pro/tracker/timeline/gstreamer/). 

Fortunately, Qt can be built against `libgstreamer1.0` with some effort. I've done so (using the Qt 5.4.2 source code, and system configurations in [these docker files](https://github.com/jmcphers/qt-gst10)). The recompiled Qt libraries are packaged and uploaded to S3. 

It's now necessary to produce two desktop builds -- one for Trusty and earlier releases, using the stock Qt 5.4.0 (now identified by a new `-trusty-` in the .deb name, and one for Xenial and newer releases, using recompiled Qt 5.4.2 (identified by `-xenial-` in the .deb name). 

## SuSE

We have built RPMs for SuSE/SuSE Enterprise Linux from the CentOS machines on EC2; this change restores that behavior to the containerized build system.

cc @stevenolen: note that after these changes we use two more containers that we did previously.

### CODE REVIEW

**Comment by jjallaire** [comment]
We should do the bundling of the newer version of pandoc here (i.e. the .deb binaries distributed from the pandoc github repo).

**Comment by jmcphers** [comment]
@jjallaire I was planning on tackling that separately, but it could also be included in this PR. Do you have any input concerning which version of pandoc we should bundle? (was going to use the latest, but not sure if there are any R Markdown compatibility issues I've missed!)

**Comment by stevenolen** [comment]
@jmcphers thanks for the heads-up! The nightly capacity should be plenty to handle this for now, the builds will just run a bit longer!

**Comment by jjallaire** [comment]
We can definitely include that in a separate PR, just wanted to make sure it was on the radar.

For the sake of consistency I'd just bundle the same version we are currently bundling elsewhere:

pandoc-1.17.2
pandoc-citeproc-0.10.1

**Comment by jmcphers** [comment]
@jjallaire Thanks! I'll merge this today and we'll make another change for pandoc.

**Pull request merged**
