### PR TITLE
fix issue with double-printing of R banner on Windows

### LINKED ISSUE #3439: R banner is duplicated sometimes on launch
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.961
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Launch RStudio.

### Describe the problem in detail

Observer that, sometimes (~50%) the banner is duplicated.

screen shot 2018-09-06 at 4 32 35 pm

### Describe the behavior you expected

The banner should only pop up once.

### PR DESCRIPTION
**Pull request by kevinushey**
This PR fixes an issue where the R banner would occasionally be printed twice on startup, primarily on Windows.

The ultimate issue is that we end up making two `get_events` requests with the same event ID `-1`. Here's my understanding as to how we get there:

1. An initial `get_events` call with id `-1` is made. The `console_output` event (alongside some other events) is returned to the client, and that output is sent to the console.

2. A number of other interleaving JSON RPCs are made during initialization. Some of these don't set any response. When this occurs, we assume (as a default) that more pending events are on the way, and so as a side-effect launch a watchdog timer that double-checks that we receive a `get_events` response in a timely manner.

https://github.com/rstudio/rstudio/blob/0a706e50a5284dcad52943195034c1fc0a5beb5b/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java#L3148-L3153

https://github.com/rstudio/rstudio/blob/0a706e50a5284dcad52943195034c1fc0a5beb5b/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java#L3186-L3193

In particular, note that a null response or 'empty' response won't have the `ep` field set, and so those will prompt the client to start its watchdog timer to check for `get_events`:

https://github.com/rstudio/rstudio/blob/0a706e50a5284dcad52943195034c1fc0a5beb5b/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerEventListener.java#L201-L202

3. A new `get_events` request is made, approximately 1 second after the watchdog timer was launched by one of the prior JSON RPCs. This `get_events` request has an updated ID number.

4. The watchdog timer fires, detects that we haven't received a `get_events` response yet (even though a fresh one is now in flight!), and so restarts the service. This implies killing the active `get_events` request, and (most importantly for this bug) resetting the event number to -1.

https://github.com/rstudio/rstudio/blob/343d6a73f8ea0670379c5e3828cc73ba04bd13bb/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerEventListener.java#L111-L122

5. A new `get_events` request is made, with id -1. Note that the server only clears the event queue after it's knowingly serviced a new `get_events` request, with an id greater than the previously-received id. See:

https://github.com/rstudio/rstudio/blob/343d6a73f8ea0670379c5e3828cc73ba04bd13bb/src/cpp/session/SessionClientEventService.cpp#L278-L279

This implies that the server will respond with the same set of events a were seen in (1).

6. The server responses with the same set of events as before, including the console output, and then replays the R banner onto the console a second time.

Based on this, I think the issue is ultimately caused by an over-eager watchdog timer. We relax the watchdog timer a bit by:

1. Re-scheduling the watchdog every time a new JSON RPC response is received (so that `get_events` gets another second to respond after some RPC response is made),

2. We reset the timer when a new `get_events` request is made (so that the watchdog doesn't erroneously shoot a `get_events` request that was just started)

Closes #3439.

cc: @jjallaire

### CODE REVIEW

**Comment by kevinushey** [comment]
One other question: should we just ensure that _all_ JSON RPC responses are marked with the `ep` field, indicating whether more events are pending? Interpreting null / empty responses as 'events are pending' seems potentially bug-prone.

**Comment by gtritchie** [comment]
Is this a new problem, or something that's started (or become more common) with 1.2? Just wondering if this is something we should touch for 1.2 or leave until 1.3.

**Comment by kevinushey** [comment]
This is a new problem, although the underlying codepaths that lead to this bug have existed basically forever. Some combination of changes in IDE infrastructure / startup logic have unfortunately gotten the Windows builds into a state where this occurs much more frequently.

Given that this is effectively a regression I think it's worth fixing for v1.2 (although this is a high-risk codepath so extra caution is definitely warranted!)

**Comment by kfeinauer** [comment]
I'm curious why this would only happen on Windows?

**Comment by kevinushey** [comment]
Windows is just unlucky, I think -- RPC requests / responses take longer there, and apparently in such a way that the timing of various in-flight RPCs are enough to trigger this bug.

**Pull request merged**
