### PR TITLE
diagnostics background task

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: not quite ready for merge.

This PR will provide a mechanism for us to display a diagnostics popup if the user leaves their cursor idle within a marker for long enough.

### CODE REVIEW

**Comment by jjallaire** [comment]
Why not a keyboard shortcut? My concern about the background approach is that users won't actually wait the two seconds (it's easier to just move the mouse which would take less than a second). 

I think most users will actually be fine with moving the mouse, those who aren't may be looking for time efficiency (this request came from Hadley who I think might be annoyed at having to wait vs. just hitting a key combo)

**Comment by kevinushey** [comment]
Main reason was because we're starting run out of easily accessible keyboard shortcuts (almost all of the prime real estate is gone), and many other IDEs do something similar (ie, leave the mouse / cursor over a diagnostic and get some UI in response)

**Comment by jjallaire** [comment]
Maybe less than 2 seconds then?

**Comment by kevinushey** [comment]
Probably something closer to 500ms will feel okay, but will play around to see what feels 'right'.

**Comment by kevinushey** [comment]
This PR is in a reasonable state, although there is some conflict as to whether we should highlight based on the mouse position or the cursor position. Here's what it looks like right now:

screen shot 2015-03-19 at 5 53 07 pm

Should we soften the UI a bit, e.g.

- Use the same colouring as we do for our help popup / signature tooltip?
- Rounded corners? Light box shadow?

**Comment by jjallaire** [comment]
I think that the popup should display based on *either* the mouse position or the cursor position being over the diagnostic.

In terms of look and feel, I'd use either the same one that Ace does for it's diagnostic tooltip or if that's difficult then use our own completion tooltip. I also think that the tooltip should be offset below the line of text where the diagnostics is (sort of like Ace does in the gutter hover tooltip).

**Comment by kevinushey** [comment]
screen shot 2015-03-20 at 9 37 10 am

**Pull request merged**
