### PR TITLE
better respect knitr options when sizing htmlwidgets

### PR DESCRIPTION
**Pull request by kevinushey**
This PR attempts to improve the sizing of HTML widgets in generated R notebooks, to ensure that the generated widgets more closely match what would be generated in a regular render of an html notebook.

This change feels pretty risky so I don't think we want it for v1.0.

### CODE REVIEW

**Comment by jmcphers** [comment]
Let's get this one merged -- do you think it's safe enough for the patch release?

**Comment by kevinushey** [comment]
I believe this will be safe for the patch release.

**Comment by jmcphers** [comment]
LGTM. Can you add a NEWS entry?

**Comment by kevinushey** [comment]
Done!

**Pull request merged**
