### PR TITLE
Fix typos in src/cpp/session comments and documentation

### PR DESCRIPTION
**Pull request by luzpaz**
### Intent

> Fixes typos found within the source code which includes comments and documentation. 

### Approach

> Found using `codespell -q 3 -S *_fr.properties -L ba,enque,ot,prevend,pevent,pevents,ptd,texline src/cpp/session/`

### Automated Tests

> This PR fixes typos. No unit tests needed.

### QA Notes

> N/A 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
This is great, thank you! Please fill out the contributor agreement as described here (https://github.com/rstudio/rstudio/blob/main/CONTRIBUTING.md#contributing-code) and then I can merge this.

**Comment by luzpaz** [comment]
@gtritchie the pdf isn't editable? :cry:  
Other CLAs just reference the user's github info.

**Comment by gtritchie** [comment]
Give this one a try (I'll work on getting the ones on the website updated):

[rstudio_individual_contributor_agreement.pdf](https://github.com/rstudio/rstudio/files/8073304/rstudio_individual_contributor_agreement.pdf)

[rstudio_corporate_contributor_agreement.pdf](https://github.com/rstudio/rstudio/files/8073307/rstudio_corporate_contributor_agreement.pdf)

**Comment by luzpaz** [comment]
@gtritchie thanks. Done

**Pull request merged**
