### PR TITLE
refine the 'new statement' indentation heuristics

### PR DESCRIPTION
**Pull request by kevinushey**
The guts of this PR: we now look for 'separate statements' when providing for indentation in all cases. For example, previously, we produced this indentation:

```
foo()
    bar()
|
```

whereas now we produce

```
foo()
    bar()
    |
```

which seems a more consistent default (to me, at least). However, this is a 'breaking change' in a sense so we might consider making it an option as it could be surprising to some users.

Note that new tests were added, and all pre-existing tests still pass.

One slight bonus is that this PR should (marginally) improve the performance of indentation code as we now perform less look-behind when attempting to produce an indentation for the next line (which implies e.g. reformat actions should be faster)

### CODE REVIEW

**Comment by kevinushey** [comment]
I added an option to control this indentation behaviour; if we think it's overkill I can strip that commit out.

**Comment by jjallaire** [comment]
I think we should hold this PR until after the release (since we're trying to close down now anything that touches indentation, code-model, etc. is I think too risky). We can also discuss realtime when you get in.

**Comment by kevinushey** [comment]
Although this PR should be 'safe' since we're just using well-tested APIs already established previously, it might produce 'wrong' indentation in some subtle cases that haven't yet been seen (feels unlikely, but possible).

Either way, I agree that it's best to be conservative.

**Comment by jjallaire** [comment]
Okay, let's hold off until development commences on the next release.

**Comment by kevinushey** [comment]
Consolidating into https://github.com/rstudio/rstudio/pull/419.

**Pull request closed without merging**
