### PR TITLE
fix issue when git located in home dir

### PR DESCRIPTION
**Pull request by kevinushey**
This PR fixes an issue where RStudio would fail to detect + use Git when the git installation lived somewhere beneath the home directory. (This is somewhat more common on Windows, where users might install a Portable Git installation into their home directory.)

### CODE REVIEW

**Comment by jmcphers** [comment]
It looks like there is at least one other place where we convert the path to a string: https://github.com/rstudio/rstudio/blob/42a4d272188bb70a938bdfc4e8ae82c1e30ba0ff/src/cpp/session/modules/SessionGit.cpp#L3040-L3041

a) Do we need to do the same transformation everywhere that we access the static variable?

b) If so, would it be better to store the resolved path in the static variable (vs. making sure we resolve it when using it)?

**Comment by kevinushey** [comment]
Good idea re: just transforming when we store the executable path. I'll make that change.

**Comment by kevinushey** [comment]
It looks like the best place to resolve this is 'upstream' in SessionUserSettings. Because the paths can potentially be aliased, we should construct the FilePath using `module_context::resolveAliasedPath()`.

**Comment by jmcphers** [comment]
Thanks, this feels like the right change! There's a lot more downstream now, though. Given that it's ostensibly always been this way, how do you feel about moving the change to 1.2?

**Comment by kevinushey** [comment]
That seems okay to me -- we've only had one report of this issue thus far so it seems most users don't encounter this bug in practice.

**Comment by jmcphers** [comment]
Wow, changing the base in the github UI didn't go so well. 👍 to merge this onto 1.2 when you're ready.

**Comment by kevinushey** [comment]
Oof, you're right! To avoid getting stuck in Git Calamity I just cherry-picked the associated commit onto v1.2.

**Pull request closed without merging**
