### PR TITLE
Set xterm first 16 colors based on iTerm themes when available

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

adresses #1959 

### Approach

Reboot changes from #4076 which was abandoned because of other issues, but still feels relevant. The first 16 xterm colors come from https://github.com/mbadolato/iTerm2-Color-Schemes/ e.g. for `tomorrow_night_eighties` : 

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/xrdb/Tomorrow%20Night%20Eighties.xrdb

```
#define Ansi_0_Color #000000
#define Ansi_1_Color #f2777a
#define Ansi_10_Color #99cc99
#define Ansi_11_Color #ffcc66
#define Ansi_12_Color #6699cc
#define Ansi_13_Color #cc99cc
#define Ansi_14_Color #66cccc
#define Ansi_15_Color #ffffff
#define Ansi_2_Color #99cc99
#define Ansi_3_Color #ffcc66
#define Ansi_4_Color #6699cc
#define Ansi_5_Color #cc99cc
#define Ansi_6_Color #66cccc
#define Ansi_7_Color #ffffff
#define Ansi_8_Color #000000
#define Ansi_9_Color #f2777a
#define Background_Color #2d2d2d
#define Bold_Color #cccccc
#define Cursor_Color #cccccc
#define Cursor_Text_Color #2d2d2d
#define Foreground_Color #cccccc
#define Selected_Text_Color #cccccc
#define Selection_Color #515151
```

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
However, some themes don't have equivalent xterm themes, and so still use the default colors:

I believe it's ok for light themes: 

chrome: 

image

clouds: 

image

crimson: 

image

dawn: 

image

dreamweaver: 

image

eclipse:

image

katzenmilch: 

image

textmate: 

image

Xcode: 

image

**Comment by romainfrancois** [comment]
but not so much for dark themes, i.e. the red is too "aggressive". 

ambiance: 

image

chaos: 

image


clouds midnight: 

image

idel fingers: 

image

kr theme: 

image

merbivore:

image

merbivore soft: 

image

mono industrial: 

image

**Comment by romainfrancois** [comment]
Another issue related to this: https://github.com/r-lib/usethis/issues/1240

Cobalt: 
image

Dracula:
image

Material:
image

Monokai:
image

Pastel on Dark: 
image

Solarised DArk: (not great for `code`). 
image

Solarised Light:
image

Tomorrow Night:
image

Tomorrow Night Blue:
image

Tomorrow Night 80s:
image

Twilight: 
image

Vibrant Ink:
image

**Comment by romainfrancois** [comment]
... going with the colors from "pastel on dark" for themes that are not specified by an `xrdb` file. (The only thing that changes below is the background, all other output colors are borrowed from pastel on dark): 

Ambiance:

image

Chaos:
image

Clouds Midnight:
image

Idle Fingers: 
image

Kr Theme: 
image

Merbivore:
image

Merbivore Soft:
image

Mono Industrial: 
image

**Comment by jimhester** [comment]
Thanks for taking the time to work on this @romainfrancois, I will definitely notice and appreciate this if (when 🤞) it is merged.

**Comment by hadley** [comment]
`silver` generally seems to be hard to read on the themes with dark backgrounds, but I guess being defined elsewhere, so it's hard to argue we should special case them?

**Comment by jennybc** [comment]
(FWIW usethis will also update its UI in due course and can adjust to lessons learned here and newer tooling that's now availalbe, e.g. cli.)

**Pull request merged**
