### PR TITLE
ensure dialogs created by R shown on top

### LINKED ISSUE #2901: On Windows, when installing a package that needs compilation, the dialog box shows behind RStudio window
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.667
    OS Version      : Windows
    R Version       :  3.5.0

### Steps to reproduce the problem

As of right now, doing the following will cause the problem. First make sure the purrr package is not installed. Then run:

```R
install.packages('plotly')
```

It will try to install purrr, because plotly imports it. The dialog will appear behind the RStudio window, and unless the user knows that it's there, they will probably end up killing the RStudio process.

Note that if you install purrr directly, the problem does not happen; the dialog appears in front, as it should.

```R
install.packages('purrr')  # OK
```

This happens right now because purrr does not have the latest binary package on CRAN. Once it's there, these instructions won't cause the problem, but I'm guessing it will happen with other packages.

### PR DESCRIPTION
**Pull request by kevinushey**
This PR attaches a Windows event handler, listening for dialogs created by the `rsession` process. When such a dialog is created, we ensure that window is activated and brought to the front.

Fixes #2901. One thing worth discussing is whether we need to be more careful about which dialogs that R might create need to be brought to the front; I think it's okay to assume that all dialogs created from R are modal and require immediate user attention but perhaps I'm missing some cases where that might not be true (download dialogs?)

### CODE REVIEW

**Comment by kevinushey** [comment]
In fact, this behavior is pretty annoying when a download is triggered for multiple R packages, since focus will 'flash' between RStudio and the generated download windows, so I think we should indeed attempt to scope this behavior down a bit.

Perhaps it will be sufficient to check the window title or something similar?

**Comment by jmcphers** [comment]
> Perhaps it will be sufficient to check the window title or something similar?

Are there situations other than download progress popups where this might be an issue? I'm hesitant to resort to heuristics based on the window title since we don't control it and it's therefore subject to false positives and, in possible future R versions, false negatives. 

Is there any deterministic way to override the way R provides download status? If there is, it seems like the ideal path forward would be to take your change as-is, making sure all dialogs from R get visibility, and to handle the download case specifically by drawing our own progress.

**Comment by kevinushey** [comment]
Unfortunately, I don't think so. Here's where R creates the windows during download:

https://github.com/wch/r-source/blob/a54dba12df0a77eff889be6c87cac15a3791e90c/src/modules/internet/libcurl.c#L550-L552

https://github.com/wch/r-source/blob/trunk/src/modules/internet/internet.c#L483-L484

Those calls to `newwindow()` use [GraphApp](http://enchantia.com/graphapp/), which IIUC is just a simple wrapper across these various Window creation APIs. I dove into the sources there and GraphApp just calls `CreateWindowEx()` pretty quickly.

**Comment by kevinushey** [comment]
Looking in a bit further, this window hook isn't actually being called for the download progress dialogs, so the behavior of how they're positioned isn't touched by this code at all. In other words, I think this is safe to take -- it just affects all dialogs from R that require user input, and those should typically be brought to front.

**Comment by jjallaire** [comment]
I believe I made a change a few years back that enabled R HTTP download dialogs to come to the front (they were being shown behind the IDE prior to that). So that's been the behavior for a while (just to say that if we did do something that causes all R dialogs even ones not requiring input to come to the front that would be fine).

**Comment by jmcphers** [comment]
Thanks @kevinushey for verifying that there is indeed no good way to hook R's download dialogs (and @jjallaire for the background). We'll take this as-is.

**Pull request merged**
