### PR TITLE
Update index.htm

### PR DESCRIPTION
**Pull request by pyltime**
Fixed links that were pointing to outdated webpages.

### CODE REVIEW

**Comment by jjallaire** [comment]
These links are all correct (they are redirects) however it looks like the server hosting the redirects is down!!! @jcheng5 This is the www.rstudio.org server, did that get taken offline in the recent move of the website?

**Comment by jjallaire** [comment]
Note this means that ALL in product links are currently broken.

**Comment by jcheng5** [comment]
Investigating now

**Comment by jcheng5** [comment]
rstudio.org is back up. The server was running but the Apache process had been stopped from the command line. I restarted it, I'm assuming just a miscommunication between me and Chad. I'll follow up with him to make sure.

**Comment by jjallaire** [comment]
Okay, awesome, thanks for running this down!

Ian I think our links should all be back in business now.

**Pull request closed without merging**
