### PR TITLE
run 'testthat::test_file()' on source

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: not quite ready for merge.

This PR augments the source command to use `testthat::test_file()` when appropriate.

## TODO

- [x] Avoid eager system callback to check `testthat` version (ie, update some client state on startup / package install)
- [ ] Only enable for testthat files in current project?

### CODE REVIEW

**Comment by kevinushey** [comment]
Hmm, it's probably better to piggyback on the logic in `executeSourceCommand()`.

**Comment by kevinushey** [comment]
This PR blew up a bit because it seems like we could be monitoring + using the package events fired on load + unload a bit more; let me know if you think it's reasonable that we implement a system like this.

Note that if we go down this road we need to do a bit more work as e.g. it seems that the package hooks are not injected until after the .Rprofile is run, which means some packages can be missed.

**Comment by jjallaire** [comment]
I would leave aside the package loaded/unloaded stuff for this PR. As you pointed out it's a bit leaky to begin with. Also, for the purposes of this feature I think it's not relevant whether testthat is loaded as we can just always emit the fully qualified call to testthat::test_file.

Let's break the package load/unload stuff into a separate PR that we can iterate on later.

**Comment by kevinushey** [comment]
One problem is that `testthat::test_file()` doesn't work unless `testthat` is actually attached (as otherwise the functions like `context()` are not properly resolved). cc @hadley -- should `test_file()` ensure `testthat` is attached, or evaluate the code in an environment where the `testthat` namespace is otherwise available?

**Comment by jjallaire** [comment]
I think it's sufficiently complicated for us to robustly detect when
packages are loaded and unloaded then test_file should definitely make sure
testthat is attached. Note that even if we could detect these things
robustly then wouldn't users need to do "library(testthat)" in order for
the feature to light up? (and I'm not sure how intuitive that would be).

If it's ugly or undesirable for test_file to have that behavior then
perhaps we could introduce a different function just for this use case
(e.g. testthat::source_test)

**Comment by hadley** [comment]
Yeah `test_file` should take care of that for you

**Comment by kevinushey** [comment]
Does `test_file()` also need to call `devtools::load_all()` (or just ensure the whole package is loaded)?

**Comment by hadley** [comment]
@kevinushey I don't think so - I think it's reasonable to expect the user to do that themselves.

Also, I think the write default in this case is to run `test_file(..., env = globalenv())` - that more closely mimics what source does.

**Comment by jjallaire** [comment]
One problem if we leave that to the user is that since we're defaulting to
running test_that for Cmd+Shift+Enter users may end up with error messages
they don't understand. I also think that many users (myself included) use
Build and Reload with test_that so never call load_all. To benefit from
this feature I'll need to always remember to load_all first.

This might argue for a dedicated function (testthat::source_tests) which
could have the automagic load_all behavior?

**Comment by hadley** [comment]
Hmmm, that seems reasonable. Maybe it belongs in devtools?

**Comment by jjallaire** [comment]
That does seem like the right thing.

**Comment by hadley** [comment]
I realised this should probably work identically to cmd + shift + t (i.e. run in a separate process too), but for a single file. That would make rapid iteration when fixing a single test much easier.

**Comment by kevinushey** [comment]
I'm going to close this PR for now, until we have the appropriate machinery in testthat / devtools.

**Pull request closed without merging**
