### PR TITLE
Use incremental feature on gwt

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
Signed-off-by: Wolfgang E. Sanyer <WolfgangESanyer@gmail.com>

### Intent

Simply, this allows for quicker iterations during development (or, in my case,
packaging), since gwt will not rebuild the full source every single time it is
invoked.

### Approach

The built-in `-incremental` feature of gwt is being used.

### Automated Tests

There are no tests associated with this change, as it is simply enabling a
feature on the gwt compiler.

### QA Notes

I cannot thing of any.

### Checklist

- **not applicable** If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- **not applicable**  If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

contributor agreement has been signed and mailed.

### CODE REVIEW

**Comment by gtritchie** [comment]
Thanks for the contribution! I'm excited to try it out, wasn't aware of that GWT option.

Have you signed the contributor agreement as mentioned here? https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

**Comment by ezzieyguywuf** [comment]
> Thanks for the contribution! I'm excited to try it out, wasn't aware of that GWT option.
> 
> Have you signed the contributor agreement as mentioned here? https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

Yes i signed it and sent the email

**Comment by gtritchie** [comment]
Evaluating now, will report shortly.

**Comment by gtritchie** [comment]
Unfortunately this is failing when I try it on our standard dev machine config.

- macOS, JDK8
- rstudio/rstudio on master
- go into `rstudio/src/gwt`
- `ant`

Gives: 
```
     [java] Compiling module org.rstudio.studio.RStudio
     [java]    [ERROR] Current binding properties are expanding to more than one permutation but per-file compilation requires that each compile operate on only one permutation.
```

**Review by gtritchie — CHANGES_REQUESTED** [review]
Fails to build when I try it, see command in PR. Don't have time right now to investigate more deeply myself.

**Comment by kevinushey** [comment]
We could also hide this behind a flag of some kind (e.g. `GWT_EXTRA_ARGS`) that one could set as they deem appropriate.

**Comment by ezzieyguywuf** [comment]
I get the same `per-file compilation` error/message. It's wrapped up with
missing `fuse-box/sparky` on my system, so I thought the error was
associated with the missing dependency.

It could be that, for whatever reason, `-incremental` will simply not work
with this project.

**Comment by kevinushey** [comment]
Closing as `-incremental` doesn't appear to work as we would hope. Please feel free to re-open if you're able to diagnose the reason why and confirm things are working.

**Pull request closed without merging**
