### PR TITLE
change files list from CellTable to DataGrid

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: Hold for merge (pending tests on other platforms).

This PR modifies our `FilesList` widget (shown in the Files pane) to use a `DataGrid` rather than `CellTable`. This has the effect of ensuring the header row is fixed.

Note that this PR modifies some of the default RStudio DataGrid styles; currently, the ModifyKeyboardShortcutsWidget is the only other DataGrid widget using those styles, so we have a bit of freedom to settle the styles within there.

### CODE REVIEW

**Comment by jjallaire** [comment]
This looks quite straightforward and a very welcome change! @jmcphers I know you have worked a bit with DataGrid probably worth a quick look by you as well.

**Comment by jmcphers** [comment]
Looks good to me. @kevinushey what's the behavior w/ long filenames? IIRC DataGrid does not adjust column width to content (columns are fixed width) so it's important we choose good width defaults and have reasonable overflow behavior.

**Comment by kevinushey** [comment]
Good catch -- the Name column is unfortunately the column first to collapse, so the filenames truncate at smaller widths:

screen shot 2016-04-07 at 3 12 05 pm

Definitely need to fix this before merge!

**Comment by kevinushey** [comment]
Alright, I've implemented a smarter resizing policy. It effectively works like this:

- If the table width is less that 500 pixels, then clamp the name column width at 208 pixels (magic number). This forces a right overflow of the other columns, which is desired here.

- If the table width is greater than 500 pixels, allow the name column to fill the rest of the width (use auto sizing).

This should mimic what we had with the CellTable implementation; unfortunately I had to write a wonky resize handler to make it work (@jmcphers, can you double check / let me know if you're aware of a simpler way of accomplishing what I've set out to do?)

**Comment by jmcphers** [comment]
This looks good to me now (thanks!) so go ahead and merge it if you've done the platform tests you mentioned earlier. 

There is in fact a way to express this with pure CSS but I don't think you can use it here since GWT is already involved in the sizing code.

**Comment by kevinushey** [comment]
I did a bit of size nudging (the checkboxes on Qt are larger, so I gave that column more space); so I think this is good to go now. Thanks for reviewing!

**Pull request merged**
