### PR TITLE
stan editor mode

### PR DESCRIPTION
**Pull request by jjallaire**
This is based on the Stan highlight mode created by @jrnold here: https://gist.github.com/jrnold/6a2e3b565cf78d871ca0

On top of this we've added a Stan editor mode that uses this highlight mode and C-style indent/outdent and code folding:

https://github.com/rstudio/rstudio/blob/feature/stan-highlight-mode/src/gwt/acesupport/acemode/stan.js

### CODE REVIEW

**Comment by jrnold** [comment]
I'd love to have stan support in RStudio. That's the reason I wrote it.

But, that was the first version that I wrote, and almost certainly out of date. I updated it in both a fork of ace: https://github.com/jrnold/ace/tree/stan and a fork of rstudio:  https://github.com/jrnold/rstudio/tree/feature/stan. You may want to check them out.

**Comment by jjallaire** [comment]
Okay, I'm bringing in your other changes now. 

One related question: for some files types we can bind Cmd+Shift+Enter (the same as "Source" in R) to emit a command to the console to "run" or "compile" the script. This provides a very nice single-keystroke for saving and trying out what's in the buffer. Examples of this are running bash or python scripts, or previewing graphviz diagrams. Is there a single R function call that we could emit (with the name of the .stan file passed as an argument) that would provide a sane try/preview behavior or is the invocation/compilation a bit more complex?

**Comment by jrnold** [comment]
Not exactly. It would be closer to Rcpp source, but I don't think there is
a good way to automatically name the R objects that would be created. I'm
sending this over to the stan-dev mailing list if the others have better
ideas.

**Comment by jrnold** [comment]
cc: @maverickg @syclik @bgoodri @bob-carpenter

**Comment by syclik** [comment]
@rtrangucci

**Comment by bgoodri** [comment]
If there were going to be something roughly analagous to `source`, I think it would be to bind to `stanc(filename)`. That would parse (but not compile) the filename, and hence would almost instantly give an indication of whether there are any syntax errors.

**Comment by jjallaire** [comment]
Okay, the UI bound to this would be a button called "Preview" (which goes
at the top-right where "Source" typically is). It seems like "Preview" is
reasonable nomenclature but perhaps "Check" would be better. Let me know
what you think.....

**Comment by bgoodri** [comment]
Is "Parse" acceptable?

**Comment by bgoodri** [comment]
Also, let me know if you would like me to make a separate issue for this, but it would be good if RStudio had a template for a Stan file like it has for Rcpp. I sketched one out here:

https://groups.google.com/d/msg/stan-dev/xWNQHm4zwo0/DaxwNNsckqIJ

**Comment by jjallaire** [comment]
I'm going to merge this PR then create a separate one for the "source/preview/check" button mentioned above.

**Comment by jjallaire** [comment]
In terms of New File -> Stan, I think we should wait on this until we have a more scalable New File user experience (right now it's just a single menu so we try to keep it spare so it doesn't get overwhelming). We're hoping to do that in our next release so we can revisit then.

**Comment by bgoodri** [comment]
OK

**Comment by jrnold** [comment]
Sorry for putting this on an old pr. Could you add snippets for Stan files? It looks like they aren't registered somewhere, so even if I put them in `~/.R/snippets`, they don't appear. I put together a default set of snippets: https://gist.github.com/jrnold/97b3bf98b95a7372fb1c.

**Comment by jjallaire** [comment]
Would be happy to!

Could you send us a contributor agreement as described here:
https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

Note that it's also possible to add more intelligent (context/scope
sensitive) completion (right now it's just text based completion) as well
as custom inline diagnostics. We'd be happy to include those as well. If
you are interested in pursuing this perhaps you can find a time to get
together with @kevinushey (who did all the completion and diagnostics work
in RStudio and is based in Seattle) to discuss how to go about it.

**Comment by bgoodri** [comment]
Just responding to say that all this would be great!

Currently, rstan 2.7.0 from CRAN has a file called stan-functions.txt under
its tools/ subdirectory that looks like this

 goodrich@T540p:/opt/rstan/rstan/rstan/tools$ head stan-functions.txt
# This file is semicolon delimited
StanFunction; Arguments; ReturnType; Page
abs;(int x);int;284
abs;(real x);real;292
acosh;(real x);real;297
acos;(real x);real;296
append_col;(matrix x, matrix y);matrix;326
append_col;(matrix x, vector y);matrix;327
append_col;(row_vector x, row_vector y);row_vector;327
append_col;(vector x, matrix y);matrix;327

and that becomes a data.frame in its R/sysdata.rda file that gets loaded
into the rstan namespace. So, if the user typed acos in a .stan file and
paused, it ideally should behave like if you typed acos in a .R file and
paused (showing acos and acosh) and then the user might select acosh in
which case the beige box pops up saying its only argument is x and is real.
We don't have a help string but the autogenerated help string could say
"look at page 297 in the Stan User Manual".

I think this would be pretty straightforward iff the code completion could
be implemented at runtime rather than RStudio build time.

**Comment by kevinushey** [comment]
To be clear -- you're saying that the set of candidate completions (e.g. valid `stan` 'words' / 'tokens') within a `.stan` file could be drawn from that data structure? It looks like it can be accessed with:

    rstan:::rosetta

Although we have less tooling available here for non-R documents I think it should still be possible to at least provide 'simple' completions of the function names for `stan` files, based on the available `stan` functions. I'll file this as a feature request and we can take a look.

**Comment by bgoodri** [comment]
Yes, all exposed Stan functions (although the same function can have
different argument signatures) are contained in that rstan:::rosetta
data.frame and the stan-functions.txt file it derives from. In addition, it
is possible for users to define their own functions within a functions
block like e.g.

functions {
  real sinc(real x) {
    return if_else(x == 0, 1, sin(x) / x);
  }
}

The functions block has to be at the top (excluding comments and
whitespace) of a .stan file and can be used in any subsequent block of a
.stan file. It might be harder to do completions on a user-defined Stan
function, but if a user is defining a Stan function then it is probably
obvious to that person what its arguments are.

**Comment by jrnold** [comment]
When you say

>   Note that it's also possible to add more intelligent (context/scope
>    sensitive) completion (right now it's just text based completion) as well
>    as custom inline diagnostics.

Is that through the snippets or the rest of your autocompletion engine? I wrote those snippets just pattern recognizing the existing snippets. Now that I've been looking through other ACE editor snippets, I can tell that there is more powerful functionality. But after an embarrassing amount of searching, I cannot find the docs, and don't feel like rummaging through the source code. I wrote a pretty complete set of snippets for Stan for the emacs snippet engine yasnippet: https://github.com/stan-dev/stan-mode/tree/master/stan-snippets. Some of those had optional components or nested snippet, and I didn't port those over. In that, I also used the same file `stan-functions.txt` that @bgoodri mentioned to generate snippets for all the built-in functions (although there's presumably better ways to do the autocompletion).

@kevinushey I'm pretty busy the the next month, but if you're ever near UW, let me know and we can grab a coffee or beer and talk about Rstudio.

**Comment by jjallaire** [comment]
Ace exposes an interface for smarter completion behavior (the default just
uses text-based autocompletion). They use this internally for e.g.
completing html tags and their attributes. With some help from us we could
also help you marry this to introspection of the stan-functions.txt file.

There aren't docs that I know of for the snippets but they are based on
TextMate snippets which are documented here:
https://manual.macromates.com/en/snippets

Now that we've properly integrated the Stan snippets (as of a daily build
that will be out later today) they'll be editable at
~/.R/snippets/stan.snippets). If you end up adding more let us know and we
can incorporate them into our built-in Stan snippets.

**Comment by kevinushey** [comment]
@jrnold I added the set of stan functions listed in `rstan:::rosetta` to keyword completions, so they are now provided (although without docstrings at this point):

screen shot 2015-07-24 at 5 19 08 pm

You should see this in the next daily builds; let me know what you think.

**Comment by bgoodri** [comment]
Awesome! The gaussian_dlm_obs keyword is actually a "sampling statement"
and we are still working on getting the arguments sampling statments take
into stan-functions.txt and then rstan:::rosetta for the next version. A
sampling statement always follows a tilde (which is what is in the
Arguments column of rstan:::rosetta currently). So, if the user typed

y ~ multi

we would ideally want the suggested completions to be sampling statements
only. In this example, there are 6 possible sampling statements that
complete

multi_gp
multi_normal_cholesky
multi_normal_prec
multi_normal
multi_student_t
multinomial

Tha gaussian_dlm_obs_log is a "regular" function, although the sampling
statement y ~ gaussian_dlm_obs(...) calls gaussian_dlm_obs_log(y, ...).
Anyhoo, for a regular function we would ideally like the help string to be
a concatenation of the next three columns of rstan:::rosetta. So, if the
user selected gaussian_dlm_obs_log the popup box would say there are 2
valid signatures (in general, there can be one or more than one valid
signature)

(matrix y, matrix F, matrix G, *matrix V* matrix W, vector m0, matrix C0)
returns a real. See page 382 of the manual.
(matrix y, matrix F, matrix G, *vector V* matrix W, vector m0, matrix C0)
returns a real. See page 382 of the manual.

That would be an amazing start, even if it is not possible to boldface the
differences in the signature.

I'm not sure if the code diagnostics API is advanced enough that if the
user tried to pass a scalar to the first argument that it could bark "first
argument must be a matrix". It works pretty much like C++ in that respect,
although Stan has some non-obvious scoping rules.

**Comment by bgoodri** [comment]
Conversely, if there is no tilde immediately preceeding the token, the completions should filter out sampling statements.

**Comment by bgoodri** [comment]
I pushed a fix to rstan:::rosetta handle the sampling statements better,
but you would have to reinstall rstan from GitHub

devtools::install_github("stan-dev/rstan", ref = "develop", subdir =
"rstan/rstan", dependencies = TRUE)

to see it. Now there is another logical column in rstan:::rosetta called
SamplingStatement. So, if the token starts with "~", RStudio should filter
the possible completions according to whether
rstan:::rosetta$SamplingStatement == TRUE and if the token does not start
with a "~", RStudio should filter the possible completions according to
whether rstan:::rosetta$SamplingStatement == FALSE. In addition, the
sampling statements now have the corresponding elements of
rstan:::rosetta$Arguments filled in.

**Comment by kevinushey** [comment]
I don't think we'll be able to make auto-completions more context-sensitive at this point; hopefully sometime in the future we'll have an API that will allow package authors to provide their own completions for given file types, so that e.g. `rstan` could provide its own function that RStudio could use to form a completion list. (Making RStudio as a whole is a goal for upcoming releases; we're hopeful that pluggable autocompletion will become possible in the future as well.)

**Pull request merged**
