### PR TITLE
add more recognized file types to filesystem

### PR DESCRIPTION
**Pull request by jameslamb**
Similar to #5065,  in this PR I propose adding a few more recognized files types to RStudio's filesystem, so RStudio will recognize them as plaintext and allow editing.

The types included here are other source code file types we use in https://github.com/microsoft/LightGBM.

* `.cl`: C code to be compiled by [OpenCL compilers](https://en.wikipedia.org/wiki/OpenCL)
* `.i`: interface file for building cross-language interfaces with [SWIG](https://en.wikipedia.org/wiki/SWIG)
* `.ps1`: Powershell script
*  `.vxcproj`: configuration details for [MSBuild](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019) projects

Thanks for your time and for considering this PR!

### CODE REVIEW

**Comment by MariaSemple** [comment]
Hi James, thanks for taking the time to contribute to RStudio! The master branch is version 1.3 right now, which is currently closed for new features. Would you be able to rebase this PR onto the `v1.4` branch?

Other than that, it looks good to me!

**Comment by jameslamb** [comment]
> Hi James, thanks for taking the time to contribute to RStudio! The master branch is version 1.3 right now, which is currently closed for new features. Would you be able to rebase this PR onto the `v1.4` branch?
> 
> Other than that, it looks good to me!

oh sure, no problem! I just stayed with whatever the default branch was at the time I opened the PR. Will rebase and push shortly.

**Comment by jameslamb** [comment]
rebase done 😀

**Comment by jmcphers** [comment]
@jameslamb 1.4 dailies are building but not yet being posted to our dailies page. They will appear later this month once we branch 1.3 for release later this month. Stay tuned!

**Comment by jameslamb** [comment]
Thanks!

**Pull request merged**
