### PR TITLE
Don't switch to visual mode if there are unprocessed source capsules

### PR DESCRIPTION
**Pull request by jjallaire**
Fixes https://github.com/rstudio/rstudio/issues/8617

### CODE REVIEW

**Review by jmcphers — APPROVED** [review]
LGTM!

**Comment by jjallaire** [comment]
@jmcphers and @mikebessuille I'd like to make the case that this fix be included in v1.4 proper. My reasoning:

1) When it occurs it results in user data/content loss. We can only speculate about how often it might occur, however....

2) A user just sent me an Rmd to repro a bug in the Distill package and lo and behold it had an unprocessed source capsule in it! So unscientifically it seems like this can happen probably more frequently that we'd like. It could even happen to hundreds or even thousands of Rmds.

3) The fix is *extremely* safe. No new code paths, just a regex that when matches disqualifies visual mode and using an existing code path we have for implementing the disqualification.

I don't think that merging this would disqualify any regression testing we have already done as I think we can reason well about it's locality of impact.

**Comment by mikebessuille** [comment]
I could get behind that.  Especially if the fix is made to Master this weekend, because then we can still cut an RC on Monday. :)

**Comment by jjallaire** [comment]
Okay, I'll. merge it to master now. Thank you! I will sleep much better at night knowing there is no way we can ever munge user data.

**Pull request merged**
