### PR TITLE
remove spectron

### PR DESCRIPTION
**Pull request by gtritchie**
### Intent

Spectron is essentially unusable on Electron 10+ (current Electron version is 13). It uses the deprecated remote module, and requires configuring the app in a non-recommended configuration (no context isolation).

See https://github.com/electron-userland/spectron/issues/693 and https://github.com/electron-userland/spectron/issues/896

### Approach

Remove Spectron.

### Automated Tests

😭 

### QA Notes

We'll have to investigate other approaches. Right now we'll fall back to focusing on unit tests for the Electron-specific code, and our existing browser-based testing.

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by astayleraz — APPROVED** [review]

**Comment by nowshed-imran** [comment]
Playwright has been recommended as replacement in you tagged issues.

https://github.com/microsoft/playwright

**Comment by gtritchie** [comment]
Glanced at it and it seemed to be more for traditional browser-based testing (of the single-page app itself). We have that already with the server version of RStudio using Selenium; looking for something that can examine state of Electron-specific aspects such as native menus, dialogs, command-line handling, etc. (as well as seeing and manipulating the web page loaded into Electron). Haven't looked closely yet, so maybe I missed it!

**Comment by vladimiry** [comment]
> Glanced at it and it seemed to be more for traditional browser-based testing (of the single-page app itself).

It's not exactly like this, see https://playwright.dev/docs/api/class-electron. So you can manipulate the main process code too, not just pure web. The point I'd like to highlight though is that when you call `evaluate` on an electron app created by `playwright` the serialization takes place. So if you want to use something inside the `evaluate` callback you have to pass it as serializable arguments.

**Comment by gtritchie** [comment]
Will take a deeper look. Thanks!

**Pull request merged**
