### PR TITLE
preview colors for css

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

adresses #11587 

### Approach

uses https://github.com/rstudio/rstudio-ace/pull/4, https://github.com/rstudio/rstudio-ace/pull/5

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
- Some of these changes should go to `rstudio-ace` but I was wondering if there is a way to update `CssHighlightRules` after the fact rather than modify it. 

- the whole `var namedColors = {"aliceblue":"#f0f8ff",... ` thing is because we need the hex so that we can decide on the text color. Maybe there's another way to do that with some css trick, i.e. maybe something like `mix-blend-mode` but I could not figure it out.

**Comment by romainfrancois** [comment]
This handles hex colors and named (html) colors in css mode:

image

Would be nice to also support various other ways, e.g. `rgb(<red>, <green>, <blue>)` as well, but I don't know yet how to handle multiple tokens.

**Comment by romainfrancois** [comment]
handles named (html), hex and `rgb()` spec: 

image

**Comment by romainfrancois** [comment]
R and css colors, in light and dark themes. The color of the text is adjusted based on the editor background color for the theme: 

image

image

image

image

`col.R`: 

```r
# rrrggbb colors
c("#EE3325", "#F57F26", "#FCEE1A", "#58B948", "#0656A5", "#9F258F")

# rrggbbaa colors
c("#EE3325", "#F57F2688", "#FCEE1A88", "#58B94888", "#0656A588", "#9F258F88")

# rgb colors
c(
  "#000", "#111", "#222", "#333", "#444", "#555", "#666", "#777",
  "#888", "#999", "#aaa", "#bbb", "#ccc", "#ddd", "#eee", "#fff"
)

# R named colors
c("lavender", "cornsilk", "purple", "pink2", "lightblue")

c(
  "#EE3325ff", "#0656A5ff", "#eeeeeeff", "#111111ff",
  "#EE3325ee", "#0656A5ee", "#eeeeeeee", "#111111ee",
  "#EE3325dd", "#0656A5dd", "#eeeeeedd", "#111111dd",
  "#EE3325cc", "#0656A5cc", "#eeeeeecc", "#111111cc",
  "#EE3325bb", "#0656A5bb", "#eeeeeebb", "#111111bb",
  "#EE3325aa", "#0656A5aa", "#eeeeeeaa", "#111111aa",
  "#EE332599", "#0656A599", "#eeeeee99", "#11111199",
  "#EE332588", "#0656A588", "#eeeeee88", "#11111188",
  "#EE332577", "#0656A577", "#eeeeee77", "#11111177",
  "#EE332566", "#0656A566", "#eeeeee66", "#11111166",
  "#EE332555", "#0656A555", "#eeeeee55", "#11111155",
  "#EE332544", "#0656A544", "#eeeeee44", "#11111144",
  "#EE332533", "#0656A533", "#eeeeee33", "#11111133",
  "#EE332522", "#0656A522", "#eeeeee22", "#11111122",
  "#EE332511", "#0656A511", "#eeeeee11", "#11111111",
  "#EE332500", "#0656A500", "#eeeeee00", "#11111100"
)
```

`progress.css`: 

```css
/* named color */
.progress1  { color: white;}

/* rrggbb */
.progress2  { color: #F398C1;}

/* rrggbbaa */
.progress3  { color: #7DBFE9aa;}

/* rgb() */
.progress10 { color: rgb(6, 86, 165);}

/* rgba() */
.progress9  { color: rgba(88, 185, 72, 0.5);}

```

**Comment by romainfrancois** [comment]
We might want to fine tune the color or transparency of the border, but I'm otherwise happy about this pr.

**Comment by kevinushey** [comment]
Awesome, LGTM!

**Pull request merged**
