### PR TITLE
force appMode to 'static' for Quarto manuscript projects

### PR DESCRIPTION
**Pull request by dragonstyle**
### Intent

Quarto Manuscripts, even when published statically, can include `qmd` files, which are included as downloadable source for qmd files which provided embedded plots, tables, or other resources for the manuscript. Prior to this change, when publishing to Connect, the presence of these `qmd` files would lead Connect to attempt to render the document (even for a static publish). 

### Approach

This change uses a new argument in deployApp which allows us to specify that static manuscript publishes should be treated completely statically.

### QA Notes

- This requires the most recent version of the reconnect package which is not yet published to CRAN
- Once published to CRAN, I will update package dependencies for RStudio to reflect that version
- A simple project which shows the behavior is attached

**[manuscript.zip](https://github.com/rstudio/rstudio/files/12362863/manuscript.zip)**

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by dragonstyle** [comment]
(Please hold off on merging while I look at rsconnect timing)

**Comment by jgutman** [comment]
@dragonstyle I think @aronatkins made some changes in rsconnect to support this and it has been published to CRAN. is this something that's ready for the upcoming IDE release?

**Comment by dragonstyle** [comment]
Thank you for the nudge - apologies for letting this languish! I have updated the package dependency for rsconnect to 1.1.0 , which should be the other change required for the PR. I'm going to ask @jmcphers just to sanity check everything and then it should be good to go!

**Review by jmcphers — APPROVED** [review]
LGTM (pending rsconnect 1.1.0 on CRAN)

**Comment by jgutman** [comment]
Please note, main now refers to our next next release, not the upcoming release planned for September. If we are able to get this in before code freeze, we can backport it to the release branch

**Comment by dragonstyle** [comment]
I've restored the r-packages to its previous state to avoid dragging the R version up for all users. Kevin has already worked around requiring rsconnect 1.0.2 for Quarto Manuscript publishing more narrowly, so all that is required at this point is for the change to `SessionRSConnect.cpp` to pass the appMode. Sorry for the goat rodeo!

**Comment by jgutman** [comment]
Looks good then -- I'll merge this in to the desert sunflower branch for our upcoming release, as well as to main

**Review by jgutman — APPROVED** [review]

**Comment by dragonstyle** [comment]
Thank you I very much appreciate your help!

**Pull request merged**
