### PR TITLE
use curl to match readr download behavior

### PR DESCRIPTION
**Pull request by javierluraschi**
The preview to import CSV form https://data.consumerfinance.gov/api/views/s6ew-h6mp/rows.csv?accessType=DOWNLOAD does not work but the file can be imported.

The problem is that `download.file` fails from the IDE, while this works from `readr` since readr appears to be using curls: https://github.com/tidyverse/readr/blob/3715a2d0bcd7e028b4c0ffe03fce0fd7063ede18/R/source.R#L105

Fix is to match `readr` behavior in the IDE to allow us to download this file for preview purpuses.

### CODE REVIEW

**Comment by kevinushey** [comment]
I wonder if this code should instead just respect the current values of the `download.file.method` and `download.file.extra` variables? Note that `curl` is likely not available on many systems.

Note that the `curl` package works separately / differently from `download.file(..., method = "curl")` -- the former uses the `curl` R package which presumedly bundles `libcurl`; the latter attempts to call the `curl` program (as discovered on the `PATH`).

**Comment by javierluraschi** [comment]
Thanks @kevinushey, so currently I have:

```
options("download.file.method")
$download.file.method
[1] "libcurl"
```

but still `download.file` would not match `readr` download behavior. I wasn't aware `method = "curl"` does not use the curl package, how about we download the file using:

`curl::curl_download()` instead?

**Comment by kevinushey** [comment]
That sounds good to me. Should we explicitly add `curl` to the data import dependency list, just to be safe?

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java#L356-L362

(just in case someone has an older version of `readr` that didn't depend on the `curl` package, and so they have `readr` without `curl`)

**Comment by javierluraschi** [comment]
I think we might need to add a check and fallback to `download.file` since `readXL` and other packages don't have the curl dependency and ideally would be good to match `readr` with `download.file` for previous versions. Updating PR...

**Comment by jmcphers** [comment]
LGTM. @kevinushey can you merge this if you're okay with the latest changes?

**Comment by kevinushey** [comment]
LGTM as well!

**Pull request merged**
