### PR TITLE
Add simple API for adding Vim commands; add 'gq' to reflow text

### PR DESCRIPTION
**Pull request by kevinushey**
This PR adds a simple (currently local) API for adding Vim commands, and uses it to map `gq` to a `reflowText` command.

I plan on making a similar API proposal upstream as well, but this one exposes just the bits we need to define our own commands.

### CODE REVIEW

**Comment by jjallaire** [comment]
Looks good. Let's discuss and merge when you get back.

**Comment by jjallaire** [comment]
2 things before we merge:

1. Looks like we need to merge from master to resolve conflicts

2. Add docs on this to Jonathan's new Vim quick reference card.

**Comment by kevinushey** [comment]
I think this is good to go now -- I've merged from master, re-run the `sync-ace-commits` file just to ensure that everything is up to date + merged properly, and also ensured that the `gq` command is available (for now) just in markdown + text modes.

**Comment by Rainymood** [comment]
Sorry for necroing this post. I was wondering if the `gq` command actually did get implemented or not. As of writing this I am using RStudio Version 0.99.902 and the `gq` command is not functional.

**Comment by kevinushey** [comment]
Can you elaborate on what you were trying to do? Right now `gq` just works just in the simplest cases; e.g. with a visual selection on an overly-long Markdown text segment, or an overly long R comment.

**Comment by Rainymood** [comment]
`gq` in visual selection does not seem to work for me on a comment that is past the (I assume) 80-char column line

**Comment by kevinushey** [comment]
It does work for me -- can you please provide more information? A reproducible example? What file / file type are you editing?

**Pull request merged**
