### PR TITLE
snippets for stan mode

### PR DESCRIPTION
**Pull request by jjallaire**
Note that this PR isn't ready for merge yet. Needs two things:

1) Contributor agreement from original author of snippets.stan

2) The snippets aren't currently getting registered correctly.

### CODE REVIEW

**Comment by jjallaire** [comment]
@kevinushey This was my attempt at registering built-in snippets for Stan however they still don't seem to activate when I'm in Stan mode. What is missing here?

**Comment by kevinushey** [comment]
It looks like the snippets indeed are being registered (e.g. if I type `for` and then press `Shift+Tab` the snippet for `for` is expanded); however:

1. We don't register the snippets in such a way that the Ace autocompletion popup displays it (only the RStudio completion popup knows how to 'display' these snippets, it seems), and

2. It looks like Ace still attempts to load the 'default' snippets -- e.g. I see an error in the JS console,

Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:8787/snippets/stan.js]

I can investigate a bit further if you like.

**Comment by kevinushey** [comment]
@jjallaire, this should be good to go now. To sum it up, we ensure snippets are loaded both on editor load, and just before adapting to file type (this is necessary to avoid Ace attempting to make spurious GET requests to load a particular snippets file).

The other noise is mainly related to using uncompressed versions of various Ace pieces when running SuperDevMode (which should make debugging these sorts of things a bit more tangible)

**Comment by jrnold** [comment]
You're right. The snippets were being loaded. I apologize  for not doing full diligence. What I had done was check to see that Stan appeared when opening the edit snippet window. When it didn't, I just assumed that only a predetermined set of snippet types were recognized (R, C/C++, Markdown, etc) and didn't think that it would work.

**Comment by jjallaire** [comment]
@kevinushey Thanks for sorting all of this out (I would have had no chance!). @jrnold If you are interested at some point we can describe in more depth what's possible in terms of smarter completions and diagnostics.

**Pull request merged**
