### PR TITLE
stop building RDP for Qt

### PR DESCRIPTION
**Pull request by gtritchie**
### Intent

Addresses https://github.com/rstudio/rstudio-pro/issues/5233 (once merged into pro, that is)

### Approach

No longer build RDP with Qt (aka "Desktop"), only Electron.

Also stop updating daily build redirects for Qt RDP and instead update them for Electron.

### Automated Tests

N/A

### QA Notes

Build stuff.

### Documentation

N/A

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
Should we also consider making Electron the default in our package build script?

https://github.com/rstudio/rstudio/blob/a6a932f62ef90cfb28f91e85c7f967b219f248a9/package/win32/make-package.bat#L19

(not directly applicable to this PR, but might be nice to fold in)

**Comment by gtritchie** [comment]
@kevinushey Good idea, done! (Linux script didn't have a default so didn't touch it).

**Comment by timtmok** [comment]
There's also the `CMakeGlobals.txt` that defaults Mac Pro builds to desktop. Might be good to change that default too.

https://github.com/rstudio/rstudio/blob/d6a7e58047ab7a97778069a90adb9b4c8426b187/CMakeGlobals.txt#L125-L126

**Comment by gtritchie** [comment]
> There's also the `CMakeGlobals.txt` that defaults Mac Pro builds to desktop. Might be good to change that default too.

@timtmok Done!

**Review by timtmok — APPROVED** [review]

**Pull request closed without merging**
