### PR TITLE
Allow successful compilation with libc++ (C++11) / boost 1.58

### PR DESCRIPTION
**Pull request by kevinushey**
@howarthjw, can you confirm that this branch builds with the updated `libc++` / Boost 1.58? I imagine your motivation is that you want RStudio added to the `fink` project -- is that correct?

@jjallaire, do you think this trimmed down PR would be okay to merge, or would you prefer not? (Eg. if the motivation here was that a version of RStudio might be released built against an untested toolchain, should we prefer to avoid that?)

### CODE REVIEW

**Comment by howarthjw** [comment]
I'll try to find some time to test current rstudio trunk later in the week.
I initially attempted to update the fink rstudio-desktop/rstudio-server
packages to a nightly snapshot from
https://github.com/rstudio/rstudio/releases but was stymied by the new
rmarkdown requirement. Specifically, it was unclear if tarballs exist for
the required rmarkdown or if I have to resort to a git pull of markdown
trunk for the correct version of that package. Also, I am unclear about
where it will want to install rmarkdown. Does the build install  rmarkdown
into a subdirectory within the Rstudio application directory or does it
have to be installed into the normal site-packages directory with the other
R modules from CRAN. I have most of those packaged for the available R
releases...

http://pdb.finkproject.org/pdb/browse.php?maintainer=Jack+Howarth

and could do the same for trunk rmarkdown. The rmarkdown on the CRAN web
site appears to be much older (v0.5.1) and I assume won't work as a
substitute. By comparison, the build dependencies for 0.98.1103 were much
more straight forward.
        Jack

**Comment by kevinushey** [comment]
@howarthjw, please look at the [dependencies](https://github.com/rstudio/rstudio/tree/master/dependencies) folder if you want to understand how the build environment for RStudio is generated. Everything you need to know is in the scripts there; for example, on OS X, we generate the build environment with:

    cd dependencies/osx
    ./install-dependencies-osx

And, [here](https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-packages), you'll see that we (currently) install RMarkdown from GitHub master.

**Comment by jjallaire** [comment]
Note that our plan is to once again install rmarkdown from CRAN in the
final release of v0.99 (once the CRAN version has been updated from the
current decelopment version)

On Apr 26, 2015, at 8:59 PM, Kevin Ushey <notifications@github.com> wrote:

@howarthjw <https://github.com/howarthjw>, please look at the dependencies
<https://github.com/rstudio/rstudio/tree/master/dependencies> folder if you
want to understand how the build environment for RStudio is generated.
Everything you need to know is in the scripts there; for example, on OS X,
we generate the build environment with:

cd dependencies/osx
./install-dependencies-osx

And, here
<https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-packages>,
you'll see that we (currently) install RMarkdown from GitHub master.

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rstudio/pull/397#issuecomment-96454744>.

**Comment by howarthjw** [comment]
Okay, compiling https://github.com/rstudio/rstudio/archive/v0.99.408.tar.gz
with the proposed patch from
https://patch-diff.githubusercontent.com/raw/rstudio/rstudio/pull/397.patch
using -std=c++11 and libc++ on darwin14 triggers the new failure of....

[ 77%] Building CXX object
src/cpp/session/CMakeFiles/rsession.dir/modules/SessionRParser.cpp.o
cd
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/build/src/cpp/session
&& /usr/bin/c++   -DBOOST_ASIO_DISABLE_KQUEUE -DBOOST_ENABLE_ASSERT_HANDLER
-I/sw/Library/Frameworks/R.framework/Versions/3.2/Resources/include
-DBOOST_SIGNALS_NO_DEPRECATION_WARNING -std=c++11  -stdlib=libc++ -O3
-DNDEBUG -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
-mmacosx-version-min=10.10 -isystem /sw/opt/boost-1_58/include
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/session/include
-I/sw/Library/Frameworks/R.framework/Versions/3.2/Resources/include
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/monitor/include
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/r/include
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/build/src/cpp/session
-I/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/tests/cpp
   -Wall -pthread -Wsign-compare -o
CMakeFiles/rsession.dir/modules/SessionRParser.cpp.o -c
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/session/modules/SessionRParser.cpp
In file included from
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/session/modules/SessionRParser.cpp:23:
In file included from
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/Debug.hpp:20:
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/Json.hpp:152:11:
error: no matching conversion for functional-style
      cast from 'const boost::optional<std::__1::basic_string<char> >' to
'json::Value' (aka 'Value_impl<json_spirit::mConfig>')
   return json::Value(val);
          ^~~~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/Debug.hpp:36:33:
note: in instantiation of function template
      specialization
'rstudio::core::json::toJsonValue<boost::optional<std::__1::basic_string<char>
> >' requested here
      object[it->first] = json::toJsonValue(it->second);
                                ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/session/modules/SessionRParser.cpp:1572:14:
note: in instantiation of function template
      specialization
'rstudio::core::debug::print<std::__1::basic_string<char>,
boost::optional<std::__1::basic_string<char> > >' requested here
      debug::print(matched.matchedCall());
             ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:41:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'Const_str_ptr' (aka
'const char *') for 1st argument
        Value_impl( Const_str_ptr      value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:42:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'const String_type' (aka
'const std::__1::basic_string<char>')
      for 1st argument
        Value_impl( const String_type& value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:43:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'const Object' (aka
'const map<String_type, Value_type>') for 1st
      argument
        Value_impl( const Object&      value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:44:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'const Array' (aka
'const vector<Value_type>') for 1st argument
        Value_impl( const Array&       value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:45:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'bool' for 1st argument
        Value_impl( bool               value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:46:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'int' for 1st argument
        Value_impl( int                value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:47:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'boost::int64_t' (aka
'long long') for 1st argument
        Value_impl( boost::int64_t     value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:48:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'boost::uint64_t' (aka
'unsigned long long') for 1st argument
        Value_impl( boost::uint64_t    value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:49:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'double' for 1st argument
        Value_impl( double             value );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:51:9:
note: candidate constructor not
      viable: no known conversion from 'const
boost::optional<std::__1::basic_string<char> >' to 'const

json_spirit::Value_impl<json_spirit::Config_map<std::__1::basic_string<char>
> >' for 1st argument
        Value_impl( const Value_impl& other );
        ^
/sw/src/fink.build/rstudio-desktop-0.99.408-1/rstudio-0.99.408/src/cpp/core/include/core/json/spirit/json_spirit_value.h:40:9:
note: candidate constructor not
      viable: requires 0 arguments, but 1 was provided
        Value_impl();  // creates null value
        ^
1 error generated.
src/cpp/session/CMakeFiles/rsession.dir/build.make:1253: recipe for target
'src/cpp/session/CMakeFiles/rsession.dir/modules/SessionRParser.cpp.o'
failed

This is just above where the correction...

From 073fd99150b8370fea129672752794a7d15140a4 Mon Sep 17 00:00:00 2001
From: JJ Allaire <jj@rstudio.org>
Date: Sat, 25 Apr 2015 07:36:17 -0400
Subject: [PATCH] fix compilation errors that occur as a result of GCC
concept
 checks

---
 NEWS.md                                 |  2 ++
 src/cpp/core/include/core/json/Json.hpp | 11 +++++++++++
 2 files changed, 13 insertions(+)

was made.

**Comment by kevinushey** [comment]
[This commit](https://github.com/rstudio/rstudio/commit/0da88a8ec2a5554bc5280120be99916385ae15fd) should solve the most recent compilation problem.

**Comment by kevinushey** [comment]
[This commit](https://github.com/rstudio/rstudio/commit/76f963aa618375eb9caae4f75def1c737697649d) should resolve that problem (it looks like `boost::optional` became more strict in what implicit conversions are allowed)

**Comment by howarthjw** [comment]
Unfortunately that commit didn't eliminate the compile problem, however
suppressing it for now with....

--- rstudio-0.99.408/src/cpp/session/CMakeLists.txt.orig        2015-04-26
23:37:26.000000000 -0400
+++ rstudio-0.99.408/src/cpp/session/CMakeLists.txt     2015-04-26
23:40:48.000000000 -0400
@@ -170,6 +170,8 @@
    ${CMAKE_CURRENT_BINARY_DIR}/SessionAddins.cpp
 )

+set_source_files_properties(modules/SessionRParser.cpp PROPERTIES
COMPILE_FLAGS -std=c++03)
+
 # platform specific source files
 if(UNIX)
    set(SESSION_SOURCE_FILES ${SESSION_SOURCE_FILES}

allows the build of 0.99.408 with the proposed patch from
https://patch-diff.githubusercontent.com/raw/rstudio/rstudio/pull/397.patch
to complete using -std=c++11 and   -stdlib=libc++ on darwin14 with Xcode
6.3. The resulting rstudio-desktop application runs fine. I'll test the
server build in the morning and also take try using current git head.

**Comment by howarthjw** [comment]
My mistake. I only applied one of your last two commits. Using the complete
aggregate patch from
https://patch-diff.githubusercontent.com/raw/rstudio/rstudio/pull/397.patch
does allow 0.99.408  to completely compile with -std=c++11 -stdlib=libc++
on darwin14 with Xcode 6.3.

**Comment by kevinushey** [comment]
Great news! Thanks for testing it out and reporting back so promptly.

**Comment by howarthjw** [comment]
I also can confirm that the proposed aggregate patch from
https://patch-diff.githubusercontent.com/raw/rstudio/rstudio/pull/397.patch
allows
the server build of rstudio  0.99.408  to completely compile with
-std=c++11 -stdlib=libc++ on darwin14 using Xcode 6.3. In both the server
and desktop build, the boost used was 1.58 of course.

**Comment by jjallaire** [comment]
More on the rmarkdown GitHub dependency:

We generally prefer to install packages from CRAN however there are times
when the IDE *requires* things on GitHub master and in those cases we
switch to the mechanism you noted. In general if you want to package
RStudio you need to able to handle this sort of dependency as over time
we've done it for many packages including rmarkdown, packrat, shiny, and
shinyapps.

Before building we run the ./install-packages script which creates source
packages for all our embedded packages. These packages are copied into the
RStudio installation directory and then are installed *on-demand* when the
user attempts to use a feature that requires them (they are installed into
the library that is first on the users .libPaths()

**Comment by howarthjw** [comment]
Thanks. I can confirm that unpatched rstudio trunk at commit
65704d1cb22d45aa3ceb60a2601674a704fb6789 builds fine with
-std=c++11/-stdlib=libc++ on darwin14 under Xcode 6.3's compilers and using
boost 5.18 for both the desktop and server builds.
             Jack
ps On a different topic, I noticed the build currently has a few security
issues to be patched...

./../../gcc-5.1.0/libcpp/expr.c:681:11: warning: format string is not a
string literal (potentially insecure) [-Wformat-security]
                                   0, message);
                                      ^~~~~~~
../../../gcc-5.1.0/libcpp/expr.c:684:32: warning: format string is not a
string literal (potentially insecure) [-Wformat-security]
                                      virtual_location, 0, message);
                                                           ^~~~~~~
../../../gcc-5.1.0/libcpp/macro.c:3087:40: warning: format string is not a
string literal (potentially insecure) [-Wformat-security]
              cpp_error (pfile, CPP_DL_ERROR, paste_op_error_msg);
                                              ^~~~~~~~~~~~~~~~~~
../../../gcc-5.1.0/libcpp/macro.c:3100:40: warning: format string is not a
string literal (potentially insecure) [-Wformat-security]
              cpp_error (pfile, CPP_DL_ERROR, paste_op_error_msg);
                                              ^~~~~~~~~~~~~~~~~~

**Comment by jjallaire** [comment]
As far as I can see those errors are not in the RStudio source code (rather
they are in the gcc 5.1 libcpp source code)

**Comment by howarthjw** [comment]
My mistake. I had a second log in the terminal window.

**Comment by howarthjw** [comment]
Now that rstudio trunk has been fixed to build on libc++ with -std=c++11,
the code below in src/cpp/CMakeLists.txt that forces the build on Mavericks
or later to -stdlib=libstdc++ should be removed.

      # Mavericks and later default to libc++, which is not compatible with
the
      # older libstdc++. Figure out if we're on Mavericks, and if so, add
      # flags to enforce usage of the older library.

      # Figure out what version of Mac OS X this is. Unfortunately
      # CMAKE_SYSTEM_VERSION does not match uname -r, so get the Mac OS
      # version number another way.
      EXECUTE_PROCESS(COMMAND /usr/bin/sw_vers -productVersion
OUTPUT_VARIABLE MACOSX_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
      message(STATUS "Mac OS X version: ${MACOSX_VERSION}")
      if(NOT(${MACOSX_VERSION} VERSION_LESS "10.9"))
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libstdc++")
         set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS}
-stdlib=libstdc++")
      endif()

**Comment by jjallaire** [comment]
I'm not sure we should be removing this as it may address other issues we
have with mixing different versions of the C++ standard library between R
and RStudio (IIRC we didn't add this to address compilation issues but
rather runtime issues). In any case we *definitely* cannot change this now
as we are close to release. @howarthjw I think if you have an issue here
you should make a local patch.

**Comment by howarthjw** [comment]
Longer term, that code in src/cpp/CMakeLists.txt (which currently forces
-stdlib=libstdc++ on 10.9 or later) should be replaced with code that
invokes combinations of -std= and -stdlib= based on the boost in use
instead (assuming that the boost version can be gotten at from within
src/cpp/CMakeLists.txt). FYI, I have tested current trunk with the
following successful build on Yosemite and Xcode 6.3...

boost 1.53 with the default clang++ behavior of -std=c++03 and
-stdlib=libc++

boost 1.55 with the default clang++ behavior of -std=c++03 and
-stdlib=libc++

boost 1.58 with the clang++ compiling as -std=c++11 and -stdlib=libc++

Again, the use of -std=c++11 only exists for boost 1.57 and 1.58 due to
https://svn.boost.org/trac/boost/ticket/9610 which prevents -std=c++03x or
lower from compiling certain files in rstudio.

**Comment by howarthjw** [comment]
One minor remains as a follow from the applied patch. Removing the illegal
initization of imageFileType to nil (in order to satisfy the c++11
requirements) produces warnings of...

/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:13:
warning: variable 'imageFileType' is used uninitialized whenever 'if'
      condition is false [-Wsometimes-uninitialized]
   else if ([format isEqualToString: @"tiff"])
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:658:54:
note: uninitialized use occurs here
   NSData *data = [imageRep representationUsingType: imageFileType
properties: properties];
                                                     ^~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:9:
note: remove the 'if' if its condition is always true
   else if ([format isEqualToString: @"tiff"])
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:637:4:
note: variable 'imageFileType' is declared here
   NSBitmapImageFileType imageFileType;
   ^
4 warnings generated.

According to
http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042537.html and
http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042539.html, we
should be initializing imageFileType to something. It is unclear which of
the initialization options from

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSBitmapImageRep_Class/index.html#//apple_ref/occ/instm/NSBitmapImageRep/initWithCGImage:


should be used. Or if the following applies....

For this reason, you should not use an NSBitmapImageRep object if you want
to manipulate image data. To work with data that is not premultiplied, use
the Core Graphics framework instead. (Specifically, create images using the
CGImageCreate function and kCGImageAlphaLast parameter.) Alternatively,
include the NSAlphaNonpremultipliedBitmapFormat flag when creating the
bitmap.

**Comment by jjallaire** [comment]
Should be already fixed on master


On Apr 30, 2015, at 12:06 PM, howarthjw <notifications@github.com> wrote:

One minor remains as a follow from the applied patch. Removing the illegal
initization of imageFileType to nil (in order to satisfy the c++11
requirements) produces warnings of...

/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:13:
warning: variable 'imageFileType' is used uninitialized whenever 'if'
condition is false [-Wsometimes-uninitialized]
else if ([format isEqualToString: @"tiff"])
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:658:54:
note: uninitialized use occurs here
NSData *data = [imageRep representationUsingType: imageFileType
properties: properties];
^~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:9:
note: remove the 'if' if its condition is always true
else if ([format isEqualToString: @"tiff"])
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:637:4:
note: variable 'imageFileType' is declared here
NSBitmapImageFileType imageFileType;
^
4 warnings generated.

According to
http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042537.html and
http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042539.html, we
should be initializing imageFileType to something. It is unclear which of
the initialization options from

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSBitmapImageRep_Class/index.html#//apple_ref/occ/instm/NSBitmapImageRep/initWithCGImage:


should be used. Or if the following applies....

For this reason, you should not use an NSBitmapImageRep object if you want
to manipulate image data. To work with data that is not premultiplied, use
the Core Graphics framework instead. (Specifically, create images using the
CGImageCreate function and kCGImageAlphaLast parameter.) Alternatively,
include the NSAlphaNonpremultipliedBitmapFormat flag when creating the
bitmap.

On Mon, Apr 27, 2015 at 8:56 AM, JJ Allaire <notifications@github.com>
wrote:

> Merged #397 <https://github.com/rstudio/rstudio/pull/397>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/rstudio/pull/397#event-290837207>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rstudio/pull/397#issuecomment-97855397>.

**Comment by howarthjw** [comment]
I can confirm that this issue is fixed. On x86_64-apple-darwin14 and using
Xcode 6.3, the only warnings left in the build of 0.99.421 are....

/sw/src/fink.build/rstudio-desktop-0.99.423-1/rstudio-0.99.423/src/cpp/core/tex/synctex/synctex_parser.c:3547:88:
warning: comparison of integers of different signs: 'int' and
      'unsigned int' [-Wsign-compare]
                            || (next_match == best_match &&
SYNCTEX_NODE_WEIGHT(parent)>best_weight)) {

~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
and

/sw/src/fink.build/rstudio-desktop-0.99.423-1/rstudio-0.99.423/src/cpp/desktop-mac/GwtCallbacks.mm:296:53:
warning: 'WKWebView' may not respond to 'cut:'
   [[[[NSApp mainWindow] windowController] webView] cut: self];
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/sw/src/fink.build/rstudio-desktop-0.99.423-1/rstudio-0.99.423/src/cpp/desktop-mac/GwtCallbacks.mm:301:53:
warning: 'WKWebView' may not respond to 'copy:'
   [[[[NSApp mainWindow] windowController] webView] copy: self];
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/sw/src/fink.build/rstudio-desktop-0.99.423-1/rstudio-0.99.423/src/cpp/desktop-mac/GwtCallbacks.mm:306:53:
warning: 'WKWebView' may not respond to 'paste:'
   [[[[NSApp mainWindow] windowController] webView] paste: self];
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
3 warnings generated.

On Thu, Apr 30, 2015 at 1:08 PM, JJ Allaire <notifications@github.com>
wrote:

> Should be already fixed on master
>
>
>
> On Apr 30, 2015, at 12:06 PM, howarthjw <notifications@github.com> wrote:
>
> One minor remains as a follow from the applied patch. Removing the illegal
> initization of imageFileType to nil (in order to satisfy the c++11
> requirements) produces warnings of...
>
>
> /sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:13:
> warning: variable 'imageFileType' is used uninitialized whenever 'if'
> condition is false [-Wsometimes-uninitialized]
> else if ([format isEqualToString: @"tiff"])
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> /sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:658:54:
> note: uninitialized use occurs here
> NSData *data = [imageRep representationUsingType: imageFileType
> properties: properties];
> ^~~~~~~~~~~~~
>
> /sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:649:9:
> note: remove the 'if' if its condition is always true
> else if ([format isEqualToString: @"tiff"])
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> /sw/src/fink.build/rstudio-desktop-0.99.421-1/rstudio-0.99.421/src/cpp/desktop-mac/GwtCallbacks.mm:637:4:
> note: variable 'imageFileType' is declared here
> NSBitmapImageFileType imageFileType;
> ^
> 4 warnings generated.
>
> According to
> http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042537.html and
> http://lists.cs.uiuc.edu/pipermail/cfe-dev/2015-April/042539.html, we
> should be initializing imageFileType to something. It is unclear which of
> the initialization options from
>
>
> https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSBitmapImageRep_Class/index.html#//apple_ref/occ/instm/NSBitmapImageRep/initWithCGImage
> :
>
>
> should be used. Or if the following applies....
>
> For this reason, you should not use an NSBitmapImageRep object if you want
> to manipulate image data. To work with data that is not premultiplied, use
> the Core Graphics framework instead. (Specifically, create images using the
> CGImageCreate function and kCGImageAlphaLast parameter.) Alternatively,
> include the NSAlphaNonpremultipliedBitmapFormat flag when creating the
> bitmap.
>
> On Mon, Apr 27, 2015 at 8:56 AM, JJ Allaire <notifications@github.com>
> wrote:
>
> > Merged #397 <https://github.com/rstudio/rstudio/pull/397>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rstudio/rstudio/pull/397#event-290837207>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/rstudio/pull/397#issuecomment-97855397>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/rstudio/pull/397#issuecomment-97883272>.
>

**Comment by jjallaire** [comment]
Those warnings aren't going to go away unfrotunately

**Pull request merged**
