### PR TITLE
allow 'Activate Console' to activate active tab

### PR DESCRIPTION
**Pull request by kevinushey**
This PR will ensure that e.g. `Ctrl + 2` activates the active tab in the Console pane, rather than always activating the Console 'tab' in the console pane. The intention here is to allow `Ctrl + 2` to focus the terminal, if that is what is currently active + visible to the user.

This PR also adds a secondary behavior -- pressing `Ctrl + 2` multiple times now toggles through the active tabs in the Console pane; this can be useful when e.g. using 'Find in Files' output. One can now type `Ctrl + 2` to focus that pane, then use the keyboard to navigate through + select entries in that pane.

### CODE REVIEW

**Comment by gtritchie** [comment]
There's also View->Move Focus to Terminal (Ctrl+Shift+T), which always goes to Terminal tab.

I like that your change reuses a known shortcut Ctrl+2 to cycle through all the tabs in a pane; gets cumbersome to have increasingly cryptic shortcuts for each type of tab. If we're going that way, do we want to keep "Move Focus to Terminal", or ditch it?

Our implementation constrains Console/Terminal/Marker/Find in Files as being part of the "Console" pane, but perhaps one day we might make our "tabs" and "panes" more fluid, able to arrange them however user wants? If we did that, then we'd need to rethink the keyboard accessibility here. Mind you, doubt we'll be doing such a thing in the foreseeable future given the plumbing required.

**Comment by jmcphers** [comment]
My instinct is that some users are going to love this, but that other users won't. With this change there's no way to go directly to the R console in a single keystroke, and going to the R console is undoubtably one of the most common actions users take! If we're going to make this change I think we should do one of two things:

a) Add a preference which allows users to use the old behavior if they want (as we did for e.g. the new Ctrl+Enter behavior); or

b) Add a new command which sends focus directly to the console, symmetric with the command @gtritchie mentioned which sends focus directly to the terminal.

**Comment by kevinushey** [comment]
Note that it will still be just one keystroke to go to the R console tab as long as that's the tab in the console pane that last had focus -- for users with no terminal side-by-side, or no e.g. markers output, the R console will be getting focus.

That said, you're right that there is some risk that some users will press `Ctrl + 2` while a separate tab is active in the Console pane, and not realize pressing it multiple times would bring focus back to the R console.

However, there is also an added benefit that it's now much easier to interact with e.g. diagnostics, or marker, output using only the keyboard (previously, the only way to focus the Markers pane was with the mouse)

**Comment by jmcphers** [comment]
All good points. 

If we take this, then, let's add a command which sends focus right to the R console, regardless of which pane in the quadrant previously had focus. We can even leave it unbound; for users who really want a shortcut that predictably lands in the R console, they'll have the means to create one.

One other point to consider is whether this is a good model for switching tabs in the RStudio quadrants in general. We have no means of doing this with the keyboard today, and it'd be nice if we used a model which generalized well across the IDE. Do you think users would expect the same behavior with e.g. Ctrl+3?

**Comment by gtritchie** [comment]
Eclipse, for example (and I hate to use it as an example of anything but I don't have Visual Studio installed, which would be another example to look at) lets you drag tabs into a variety of regions, and has shortcuts that target each tab (Windows->Show View->xxx), but not (as far as I can see) each pane/quadrant.

Are users going to have particular tabs they want to get to directly, versus cycling through a quadrant? We could do both, perhaps; have a standard sequence to cycle through the tabs in whatever quadrant has focus, as well as fixed "go to this tab" shortcuts that always go directly to a given tab.

**Comment by kevinushey** [comment]
> One other point to consider is whether this is a good model for switching tabs in the RStudio quadrants in general. We have no means of doing this with the keyboard today, and it'd be nice if we used a model which generalized well across the IDE. Do you think users would expect the same behavior with e.g. Ctrl+3?

I'm not sure if users would expect it, but I think it could potentially be a welcome change. I've personally never used `Ctrl + 3` through `Ctrl + 0` because I can never actually remember which shortcut targets which tab. It'd be a lot easier to remember if the shortcuts targeted a particular pane (since then there's only 4 shortcuts to remember, and 2 are already in muscle memory), and then mashing the associated binding again would get you to the tab you wanted relatively quickly.

That said, I'm less sure if the cycling would be preferred in e.g. the Source pane (where there are potentially an unbounded number of tabs). I'd suggest allowing for e.g. `Ctrl + Shift + [n]` to toggle backwards through the set of open tabs, but we've already reserved those for zooming of panes.

In general, though, I think it's more useful for the activation commands to target panes rather than tabs (but I'm sure this would not be universally preferred by users).

> Eclipse, for example (and I hate to use it as an example of anything but I don't have Visual Studio installed, which would be another example to look at) lets you drag tabs into a variety of regions, and has shortcuts that target each tab (Windows->Show View->xxx), but not (as far as I can see) each pane/quadrant.

I agree, but that work is probably far off enough that we don't need to worry about it in the context of this PR. (For what it's worth, R Tools for Visual Studio definitely shows this off as a feature that separates it from RStudio -- being able to piggyback on the tab movement / layout features in Visual Studio is quite nice)

**Comment by gtritchie** [comment]
LGTM

**Comment by jmcphers** [comment]
LGTM too!

**Pull request merged**
