### PR TITLE
additional tweaks to chunk options UI

### PR DESCRIPTION
**Pull request by jjallaire**
- Toggle chunk tri-state from indeterminate to off (more intuitive since the default is TRUE so only one click is required to change the default)
- reflect code chunk toolbar option immediately
- Distinct options icon for light and dark themes
- Don't include version info in options help link

### CODE REVIEW

**Comment by jjallaire** [comment]
@kevinushey Merging this PR so I can run a build. If you want to change/refine anything feel free, otherwise we can just discuss on Tuesday.

The light/dark treatments for options may require additional discussion. I really wanted the options button to fade nearly away (sort of like our go to directory icon in the console or our refresh button on several panes). Paul may or may not have taken this too far. Let's discuss Tuesday.

**Comment by kevinushey** [comment]
Looks good to me. My only comment is that we should still include a background color (otherwise it doesn't look great when overlapping text):

screen shot 2015-05-23 at 9 00 28 am

**Comment by jjallaire** [comment]
I think the background is way too heavyweight for the more common case of
no overlapping text. what about not drawing the buttons at all in the case
of overlapping text? (or alternatively only drawing the background in that
case)

On May 23, 2015, at 12:02 PM, Kevin Ushey <notifications@github.com> wrote:

Looks good to me. My only comment is that we should still include a
background color (otherwise it doesn't look great when overlapping text):

[image: screen shot 2015-05-23 at 9 00 28 am]
<https://cloud.githubusercontent.com/assets/1976582/7784836/6fa20626-012a-11e5-949c-84dc2cc73754.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rstudio/pull/429#issuecomment-104917393>.

**Comment by kevinushey** [comment]
I just mean having a background color the same as the chunk color (so the background is effectively 'invisible' but becomes visible if the options need to be displayed on top of text)

**Comment by jjallaire** [comment]
I just tried that (same background color) and I think it's problematic that
the toolbar covers the text entirely (it definitely looks better than when
they are intermingled, but NO visibility of text makes editing very
disorienting).

I'd be in favor doing some sort of dynamic hiding of the toolbar in the
case where we see that the text extends all the way into the toolbar
region. Would that be difficult to achieve?

**Pull request merged**
