### PR TITLE
add helper for producing Copilot diagnostics

### PR DESCRIPTION
**Pull request by kevinushey**
### Intent

Addresses https://github.com/rstudio/rstudio/issues/14358.

### Approach

- Update to the latest-available build of the Copilot Agent.
- Add support for the newly-minted `debug/diagnostics` endpoint, and provide some UI for accessing it.

This PR adds a new "Diagnostics" button to the GitHub Copilot preferences pane, as so:

Screenshot 2024-02-29 at 2 12 32 PM

Clicking that will ask the Copilot Agent for diagnostics, which are then presented as so:

Screenshot 2024-02-29 at 2 13 14 PM

Not the prettiest display, but enough to be useful?

### Automated Tests

N/A

### QA Notes

Test that the "Diagnostics" button functions as this PR suggests it does.

### Documentation

Perhaps worth adding something to our Copilot docs -- @jthomasmock?

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
Now with a scroller, plus a button for copying the generated report (as the original Markdown content).

Screenshot 2024-02-29 at 4 43 34 PM

**Review by gtritchie — APPROVED** [review]
LGTM!

**Comment by jthomasmock** [comment]
I agree - worth adding to our Copilot docs to help with user self-diagnosing!

**Comment by gtritchie** [comment]
Still needs a NEWS entry (and a bug to link it to so QA knows about it).

**Pull request merged**
