### PR TITLE
Feature/rebrand company name

### PR DESCRIPTION
**Pull request by jgutman**
### Intent

Addresses #11751

Main areas covered are: 

- Update of all copyright notices to refer to Posit
- Update of all company references from RStudio, PBC -> Posit Software, PBC
- Update of citation info in `RStudio.Version()`
- Update of Help info in About RStudio to refer to Posit company

image

image

(potentially need to update rstudio.com/trademark URL as well?)

### CODE REVIEW

**Comment by jmcphers** [comment]
Do we want to hold off on this until the company's name is legally changed? (October)

**Comment by timtmok** [comment]
Looks ready to go! (in October) I agree we should wait for this. I think Jackie mentioned that during standup.

**Comment by jgutman** [comment]
We can wait to merge -- just wanted to get this done.

**Comment by ntluong95** [comment]
It seems the IDE will keep its name, only change the company's name right?

**Comment by ronblum** [comment]
@ntluong95 Correct.

**Comment by jgutman** [comment]
Also need to update src/node/desktop/src/main/url-utils.ts and corresponding test file
Posit, PBC -> Posit Software, PBC

**Pull request merged**
