### PR TITLE
improve completions for SQL chunks / code

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: Not quite ready for merge (still needs refinement) but putting up for some discussion.

---

This PR implements a completion engine for SQL code:

screen shot 2018-09-05 at 2 32 48 pm

In particular, we provide completions for:

1. SQL keywords,
2. Tables associated with the current connection,
3. Fields associated with all tables on the current connection.

Note: I'm guessing that (2) and (3) could be quite expensive, so I'm curious if there's a way we could more intelligently populate and / or cache these -- suggestions are welcome. Some thoughts:

1. We could enumerate the context wherein a table name is expected, and only provide the table names there;

2. In other contexts, we could draw field names from the set of tables that have been specified thus far.

### CODE REVIEW

**Comment by kevinushey** [comment]
Now context-aware:

screen shot 2018-09-05 at 4 34 59 pm

screen shot 2018-09-05 at 4 35 22 pm

**Comment by jjallaire** [comment]
Does this also work within a standalone .sql file?

**Comment by kevinushey** [comment]
Indeed it does :-)

**Comment by kevinushey** [comment]
I'm going to merge this now and iterate a bit more on master, but (time permitting) reviews are appreciated.

**Pull request merged**
