### PR TITLE
Add Date: field with default to `r Sys.Date()`

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #10328 and follow up #10152

### Approach

Adding a Date field, with default to `` "`r  Sys.Date()`" ``

image

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

- `File > New File > R Markdown` 
- Leave default
- ok 

The front matter will look like this

```
---
title: "Untitled"
author: "me"
date: "`r Sys.Date()`"
output: html_document
---
```

- save to file
- knit

the rendered file should have today's date.  

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Maybe there should be an option to control if we get this as default or the current date at "generating the file"-time

**Comment by kevinushey** [comment]
> Maybe there should be an option to control if we get this as default or the current date at "generating the file"-time

I like this idea. Seeing inline R code in this field feels a little "magical" and might be weird for the user. Perhaps we could have something like:

```
Date: 2022-01-13
[ ] Always use current date when rendering document
```

If that checkbox is checked, then we could disable the Date field (grey it out), and then use `` `r Sys.Date()` `` instead in the generated document.

**Comment by romainfrancois** [comment]
image

image

**Comment by romainfrancois** [comment]
Maybe this should not show `` `r Sys.Date()` `` when greyed out ?

**Comment by kevinushey** [comment]
> Maybe this should not show `r Sys.Date()` when greyed out ?

I agree; we could just continue to display the current date (grayed out), but allow the generated R Markdown document to still use `` `r Sys.Date()` ``.

**Pull request merged**
