### PR TITLE
backport double-click patch from Ace

### PR DESCRIPTION
**Pull request by kevinushey**
This PR ports a patch from Ace that fixes an issue where attempting to double-click on a word after middle-clicking on it will fail to select that word.

cc: https://github.com/ajaxorg/ace/issues/2811

### CODE REVIEW

**Comment by jjallaire** [comment]
My only concern here is that in taking these changes they end up having assumptions about other editor behavior/internals that are not true in our version of Ace (which is once again getting pretty out of sync). I know that we'll eventually catch up and get this fix, so we should make sure we do some extra analysis and/or run the Ace tests against our branch with this fix applied to be extra sure we aren't causing a larger problem by fixing a smaller one.

**Comment by kevinushey** [comment]
I reviewed the changes and it looks like it doesn't call any new API endpoints or anything like that; however, I'll give this branch some more testing before we decide to merge.

**Comment by jjallaire** [comment]
Okay, sounds good. Appreciate the extra caution!

**Comment by kevinushey** [comment]
I'm going to close this PR -- there's already enough stuff in flight for this release, we can revisit this for the next one.

**Pull request closed without merging**
