### PR TITLE
tweak display + checkout behavior for remote branches

### PR DESCRIPTION
**Pull request by kevinushey**
This PR tweaks the behavior when displaying git branches, and how remote branches are checked out.

We now separate remote and local branches into separate blocks, e.g.

screen shot 2016-08-30 at 4 33 48 pm

And attempting to check out a remote branch now checks out a local copy of the branch tracking that remote.

Let me know what you think -- one other thing we might want to consider is, rather than grouping all remote branches into a single group, separating them into groups based on the remote name.

### CODE REVIEW

**Comment by jjallaire** [comment]
UI nit, I'd make sure the headings align correctly with the left side of the other menu text (they are likely where they are because they expect menu icons to exist, however there are none for the branch menu).

**Comment by kevinushey** [comment]
Here's an example of how things look now:

screen shot 2016-08-31 at 11 17 14 am

And now, checking out a remote branch does one of two things:

1. If no local copy of that branch exists, check out a local copy and have it track the selected remote;
2. Otherwise, check out the local copy.

Note that state 2) does not update the remote tracking branch right now; e.g. if you had:

1. A local branch `master`, tracking `origin/master`,
2. You check out `fork/master`,

right now we check out the local branch `master` that still tracks `origin/master`. We might consider updating the remote tracking branch in the future.

**Comment by kevinushey** [comment]
Okay, I think this PR is good to go -- there's certainly more that could be done but I think this will be a nice improvement.

**Comment by jmcphers** [comment]
LGTM. This will save a lot of headaches!

**Comment by jjallaire** [comment]
How about the following as titles:

Checkout Local Branch


Checkout Remote Branch

I don't think Fork will make sense to most users in this context

**Pull request merged**
