### PR TITLE
Use updated RStudio icon for Mac icons

### PR DESCRIPTION
**Pull request by jgutman**
### Intent

Addresses #8395

### Approach

Use new icon provided by @gregswinehart

### CODE REVIEW

**Review by GCRev — APPROVED** [review]
I don't currently have mac set up to build rstudio from source -- only to test running pre-built builds on safari. In the interest of getting this merged and building sooner rather than later, I'd say it looks good to me!

**Comment by jgutman** [comment]
@GCRev do you know if it was intentional/if it matters that the background changed from transparent to white?

**Comment by GCRev** [comment]
@jgutman I wasn't part of that design decision, but I assume that the white background will be displayed as filling the entire rounded rect. This way it will look more like the other application icons. I'm pretty sure the Apple icon display system automatically crops the rest of the icon to the correct shape, but I haven't verified this myself.

**Comment by jgutman** [comment]
I just did a local package build, and no -- it doesn't make it into a rounded rect/square. It shows up as 
image

I too was hoping it would sort of magically work, but based on the appearance in my local package build, I'm a little concerned that it doesn't

**Pull request merged**
