### PR TITLE
Terminal local-echo tweaks and fixes

### PR DESCRIPTION
**Pull request by gtritchie**
- factored out some common (and confusing) duplicate code from `PosixChildProcess` and `Win32ChildProcess` into a shared `ChildProcessSubprocPoll` class; still find it a bit confusing but at least the confusion is now encapsulated and has some tests
- this class tracks how often to check for subprocesses, and whether there has been recent terminal output
- new behavior: when there is no recent output, frequency of subprocess checks is reduced
- new behavior: hide the _local echo_ preference UI on Windows, which doesn't support local-echo
- new behavior: if Local Echo sees the literal text **Password:** written to the terminal, it briefly suspends local-echo, to reduce the chance of user's password local-echoing before local-echo is stopped by server reporting back that terminal is busy
- now that subprocess checking is more efficient on Mac (happening via API calls instead of shelling out commands), turn up default frequency of subprocess checks; this also helps reduce the problem of password-characters being local-echoed

### CODE REVIEW

**Comment by jmcphers** [comment]
Re: password prompt detection, do we receive any notification of e.g. `stty -echo`? If that generates something we can listen for we can have a very robust solution. This heuristic is better than nothing but I have the feeling we'll miss a lot of cases. Aside from formatting and phrasing there are also systems which prompt for passwords using non-English strings. :-)

If we can't actually sync the tty's echo setting, we might try a looser heuristic, such as "contains `password` or `passphrase` (case insensitive) and ends with a `:`".

**Comment by gtritchie** [comment]
No notification currently in place for tty's echo setting changing; nothing is sent to the client in terms of escape sequences, the server just stops sending back those characters. The by-design of local-echo makes this a nasty scenario; worst case we've already shown some characters of the password in xterm before the server has even received the keystrokes, or even before the "passwd" or other program has finished starting up. I will extend the matching as you suggest. Plus the shorter local-echo suppression window with the subproc checking changes makes it better, too, but I haven't tried over a higher-latency server connection.

**Comment by gtritchie** [comment]
So far don't have a way to support local-echo and be 100% reliable on turning off password echo (but, at most, a small subset of characters are slipping through in the worst cases). The painful hack to watch for variations of password: and passphrase: can occasionally reduce the slippage by a character or two, but I'd be fine with leaving out that hack to see if what I've got is already acceptable, and try to brainstorm a more elegant solution if it's not!

**Comment by jmcphers** [comment]
We have an escape hatch here since there is an option which turns off local echo entirely; users who are worried about accidentally having their passwords echoed can just disable echo! That in combination with the heuristics you've added here (don't echo when busy, don't echo when it looks like a password prompt) are a good first run in my view. 

I'm not extremely well versed in TTY data structures but clearly there's state somewhere that is mutated when the terminal turns off echo, and I'd be surprised if there wasn't *some* way to read that state from the `/dev/ttyX` device. So if we do have to revisit this that's a possible avenue for investigation, but I think we've invested the right amount of effort in this for now. Thanks for making this change!

**Pull request merged**
