### PR TITLE
Enable snippet autocompletions

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: Not ready for merge, but this branch will encompass the addition of snippets to the IDE.

This PR currently bundles all available Ace snippets.

## TODO

- [x] Enable snippets in R mode -- wire up Ace's snippet manager to our UI.
- [x] Enable snippets in C/C++ mode -- similar wiring.
- [ ] Tweak snippet popup / insertion behaviours; add our own snippets as the default Ace ones aren't great.
- [ ] Consider UI for adding new snippets.
- [ ] Add documentation (e.g. something akin to `keyboard.htm`)

### CODE REVIEW

**Comment by kevinushey** [comment]
@jjallaire, what do you think is the most appropriate place that snippet completions could be handled in C/C++ mode? Ie,

1. Where could we insert available snippets into the completion list, and
2. Where could I take over the insertion behaviour (to ensure that applying the current 'completion' triggers the snippet expansion)?

**Comment by jjallaire** [comment]
I think the best place is CppCompletionRequest.updateUI. This is called
whenever a completion relevant keystroke is received and takes care of
filtering the completions as appropriate and then calling
showCompletionPopup with the filtered list. You could modify the type that
is passed to showCompletionPopup to also encompass snippets.

Note that if we want to use <tab> in order to move between snippets we'll
also need to track when we've got a snippet insertion active and not
intercept <tab> in that case.

**Comment by jjallaire** [comment]
A related thought: now that we show completions automatically I'm wondering
if we need the <tab> key to be bound to completions anymore? If we could
stop using <tab> for completions (at least in the source editor where you
wouldn't have snippets anyway) it seems like it would make the
implementation much simpler.

**Comment by kevinushey** [comment]
@jjallaire, I think I've achieved a nice compromise for the snippet insertion here -- now, you can press `SHIFT + TAB` to attempt an automatic snippet completion; that is, if the 'token' at the cursor matches the name of an available snippet, that snippet will get inserted. If no snippet is available, we instead perform the regular unindent action attached to `SHIFT + TAB`. This way we can sidestep some ambiguity about whether a snippet vs. a completion was desired on a `TAB` / `CMD + SPACE` keypress.

We can still maintain the combination of completion results + snippets in the popup for R and C/C++, but I do feel quite strongly that the current set of R snippets are relatively poor and we might even want to just hide / turn them off there, or ensure we get our own curated set patched in.

Thoughts?

**Comment by jjallaire** [comment]
If we always show snippets at the top of the completion list then I don't
think we need the SHIFT+TAB gesture at all as the user can simply press TAB
to accept the completion. That has the nice benefit of consistency with the
gesture in other modes (it might be hard to explain that the gesture works
differently depending on the mode). Let's discuss when you get in.

**Comment by jjallaire** [comment]
After playing with this a bit I think it would be good to have an explicit
key-combo especially for shorter snippets. Could we make Ace also respect
SHIFT+TAB in the modes where it manages completions?

**Comment by jjallaire** [comment]
Noticed an interesting buglet: anytime what I've typed exactly matches a
snippet (e.g. 'lib') the completion list does not show after typing 3
characters. However, if I type a key-combination that doesn't match a
snippet (e.g. 'sum') then the completion list does show.

**Comment by jjallaire** [comment]
I noticed that Ace also includes snippets within their completion list
which is great. If we could make Shift+Tab work under Ace then I think we'd
have a great overall story.

**Comment by jjallaire** [comment]
Playing some more, now I'm not so sure about Shift+Tab being necessary. As
it stands now if you press <Tab> on e.g. "cl" you see the completion list
with the "cl" snippet at the top. After that it's just a matter of pressing
enter to get the snippet. To me keeping <tab> as the consistent gesture
that inserts and "completes" a snippet is worthwhile so if we don't
absolutely *need* Shift+Tab I'd rather we not use it.

**Comment by jjallaire** [comment]
Further analysis, the <Tab> key actually works to include "short"
completions via our auto-accept behavior. That is after I made this change
on the C++ side (you might need something similar on the R side):

https://github.com/rstudio/rstudio/commit/5c20b1b0d1868760407379429d21e2eb9a8de3ac

e.g. in C++ mode if you type 'ns' and press <tab> you get the snippet
automatically inserted. However if you type 'fr' and <tab> you choose
between the "friend" snippet and several global functions that start with
fr. To me this seems like exactly the right behavior, and in the case that
you *always* want "fr" to mean "friend" you just need to hit Enter. To me
this one extra keystroke is no big deal especially as it allows us to
maintain consistent behavior with other Ace modes.

I'm going to provisionally remove the Shift+Tab behavior, we can put it
back if I'm missing something or you feel strongly to the contrary.

**Comment by jjallaire** [comment]
I won't remove Shift+Tab until we talk and until you can confirm that it's
straightforward to get R mode to auto-accept short snippets via <Tab>. You
can try the "ll" snippet as a test case (since it doesn't have any other
matches within standard completion search).

**Comment by kevinushey** [comment]
The buglet re: `lib` is actually an intended behaviour -- we intentionally don't auto-popup if the prefix matches some commonly-used tokens, e.g. `library` or `function`. But if you're seeing that for other snippets (that don't match commonly-used tokens) then that would be a bug.

**Comment by kevinushey** [comment]
I am a little bit torn on the `SHIFT + TAB` issue -- while I definitely agree that we should make using snippets with `TAB` as seamless as possible, I also would prefer to avoid popping up the completion list if there is an exact match. For example, suppose I have this snippet:

    dig -> devtools::install_github("|")

and something in the search path:

   dig_more <- function(x) {}

If I type `dig<TAB>`, do you think it's okay to auto-accept / insert the `dig` snippet, or should the completion list be popped up? I do feel like, if someone intended to insert one specific snippet, having the completion popup + extra keystroke is just enough to be annoying.

**Comment by jjallaire** [comment]
I think it's completely fine to have the completion popup for the dig case.
The user *only* needs to press enter to confirm which isn't a burden. This
is also exactly the same behavior as any other case where entered text is
ambiguous (e.g. a function named 'dig' and another function named
'dig_more') so will in no way be surprising or annoying.

The Shift+Tab gesture also IMHO buys you much less than you think it would
because it requires users to read the documentation on Snippets to discover
it (whereas Tab is already a natural gesture based on previous experience
with the IDE and bash.

**Comment by kevinushey** [comment]
Okay, I'm convinced -- let's take out the `SHIFT + TAB` binding.

**Comment by jjallaire** [comment]
Okay, I'll do this in my next commit.

**Comment by kevinushey** [comment]
Any thoughts on whether we should go the extra mile and allow for user-generated snippets in this push? We could do something like:

1. Ask users to place snippet files as e.g. `~/.R/snippets/r.snippets`,
2. Check and load those snippet files on startup.

We could refer users to the Ace documentation re: snippets, and provide some simple UI that opens that file for editing in RStudio (and reloads it on save)

**Comment by jjallaire** [comment]
Let's chat about this in a few minutes (have to just test one thing)

**Pull request merged**
