### PR TITLE
provide messages when R asks for permissions

### LINKED ISSUE #4579: macos: declare required privacy permissions for Mojave
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1335
    OS Version      : macOS 10.14.4
    R Version       : 3.5.3

### Steps to reproduce the problem

Run the following code in RStudio:

```
if (!requireNamespace("opencv"))
  install.packages("opencv")

library(opencv)
ocv_video(ocv_edges)
```

### Describe the problem in detail

RStudio crashes.

### Describe the behavior you expected

RStudio requests use of the webcam, and then proceeds without issue.

### Notes

We may need to declare privacy access messages in Info.plist. Example from Qt Creator:

https://codereview.qt-project.org/#/c/251414/4/src/app/app-Info.plist,unified

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #4579.

### CODE REVIEW

**Comment by kevinushey** [comment]
Screenshot of the dialog presented to the user when access is requested.

Screen Shot 2019-04-04 at 4 45 51 PM

**Comment by kevinushey** [comment]
We might want to tweak the message text -- e.g.

- An R package wants to access the camera.
- The R session wants to access the camera.

Since it's not really R itself requesting access.

**Comment by jeroen** [comment]
Thanks! Looks great.

**Comment by muschellij2** [comment]
Is this fix applicable also to the microphone?  I have found the same issue with that in RStudio vs. terminal:

## In RStudio Version 1.2.1502

``` r
library(audio)
x <- rep(NA_real_, 50000)
# start recording into x
record(x, 22000, 1)
Sys.sleep(2)
range(x, na.rm = TRUE)
#> [1] 0 0
range(x)
#> [1] 0 0
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## In the Terminal

``` r
library(audio)
x <- rep(NA_real_, 50000)
# start recording into x
record(x, 22000, 1)
Sys.sleep(2)
range(x, na.rm = TRUE)
#> [1] -0.6424448  0.5763577
range(x)
#> [1] -0.6424448  0.5763577
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Pull request merged**
