### PR TITLE
immediate bindings don't have external pointers

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #12456

### Approach

Based on: 

```c
#define BNDCELL_TAG(e)	((e)->sxpinfo.extra)

static R_INLINE SEXP BINDING_VALUE(SEXP b)
{
    if (BNDCELL_TAG(b)) {
	R_expand_binding_value(b);
	return CAR0(b);
    }
    if (IS_ACTIVE_BINDING(b)) return getActiveValue(CAR(b));
    else return CAR(b);
}
```

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
The error in #12456 is from this function in `Rinlinedfuns` : 

```c
INLINE_FUN SEXP CAR(SEXP e)
{
    if (BNDCELL_TAG(e))
	error("bad binding access");
    return CAR0(e);
}
```

so the idea here is to avoid calling `CAR()` on those bindings that have `BNDCELL_TAG != 0` but I'm not sure this is enough. 

`envir.c` defines `BINDING_VALUE` as: 

```c
static R_INLINE SEXP BINDING_VALUE(SEXP b)
{
    if (BNDCELL_TAG(b))
    {
        R_expand_binding_value(b);
        return CAR0(b);
    }
    if (IS_ACTIVE_BINDING(b))
        return getActiveValue(CAR(b));
    else
        return CAR(b);
}
```

with `R_expand_binding_value()` : 

```c
attribute_hidden void R_expand_binding_value(SEXP b)
{
#if BOXED_BINDING_CELLS
    SET_BNDCELL_TAG(b, 0);
#else
    int typetag = BNDCELL_TAG(b);
    if (typetag)
    {
        union {
            SEXP sxpval;
            double dval;
            int ival;
        } vv;
        SEXP val;
        vv.sxpval = CAR0(b);
        switch (typetag)
        {
        case REALSXP:
            PROTECT(b);
            val = ScalarReal(vv.dval);
            SET_BNDCELL(b, val);
            INCREMENT_NAMED(val);
            UNPROTECT(1);
            break;
        case INTSXP:
            PROTECT(b);
            val = ScalarInteger(vv.ival);
            SET_BNDCELL(b, val);
            INCREMENT_NAMED(val);
            UNPROTECT(1);
            break;
        case LGLSXP:
            PROTECT(b);
            val = ScalarLogical(vv.ival);
            SET_BNDCELL(b, val);
            INCREMENT_NAMED(val);
            UNPROTECT(1);
            break;
        }
    }
#endif
}
```

so this approach does not call `R_expand_binding_value()` to expand the binding, it just assumes that because `BNDCELL_TAG` is not 0, that means that this will be an immediate binding and therefore won't have a chance to have external pointer. 

But maybe there's a chance that `BNDCELL_TAG` would not be zero on something else than REALSXP, INTSXP and LGLSXP. In which case `R_expand_binding_value()` would have done nothing but perhaps the `CAR0()` would have an external pointer somewhere ... ?

**Comment by romainfrancois** [comment]
Reworked `frameHasExternalPointer()` so that it makes sure to unset the `->extra` bits before calling `CAR()`, or avoid calling it (in case of immediate bindings: they scalar they would expand to would not have external pointers).

**Comment by kevinushey** [comment]
LGTM, but I'm starting to wonder if this is going too far into the weeds -- e.g. could we safely just ignore active bindings and assume they don't have null external pointers?

If we start finding more issues with the current implementation I think we should consider taking a step back and ask if there's a simpler way forward, even if it might miss some certain cases.

**Review by kevinushey — APPROVED** [review]

**Comment by romainfrancois** [comment]
> could we safely just ignore active bindings and assume they don't have null external pointers?

That's what this does, I don't think we need to look further, but we could certainly look if the function associated with the active binding has external pointers

> If we start finding more issues with the current implementation I think we should consider taking a step back and ask if there's a simpler way forward, even if it might miss some certain cases.

yeah, let's keep an eye on this

**Pull request merged**
