### PR TITLE
remove profvis from build if requirements not met

### PR DESCRIPTION
**Pull request by javierluraschi**
still hitting the compilation issue in build machine since profvis requires R 3.0+. Will have to rethink this approach, in the meantime, disabling to unblock build.

### CODE REVIEW

**Comment by jjallaire** [comment]
One approach would be to maintain a fork or branch of profvis with that requirement removed (or we could do this with e.g. sed on the build machine). That would unblock the build, and we could still enforce the version requirement within the IDE by removing the profiling commands for R < 3.0

**Comment by javierluraschi** [comment]
Point taken... changed `CMAKE` as well to unblock the build.

**Comment by javierluraschi** [comment]
@jmcphers @jjallaire, @winston helped us merge a small changed to unblock builds in R<3:

https://github.com/rstudio/profvis/pull/25

This change, at least, unblocks the build machine and therefore, this PR is no longer needed, I believe. Will validate this once the build finishes, but for now, closing.

**Comment by javierluraschi** [comment]
BTW. The build finished on the mac build machine, installed the `dmg` and, so far, is looking good.

**Comment by jmcphers** [comment]
Okay, great! Since we have convincing evidence this will work I think we'll just let the daily build pick this up tonight and run with it.

**Pull request closed without merging**
