### PR TITLE
Emoji completion :tada: 

### PR DESCRIPTION
**Pull request by romainfrancois**
This adds slack (or GitHub) like emoji completion (with narrowing) , i.e. when you type `:cat` in some context, the completion popup offers emoji completions: 

This is based on the function `ji_completion` in the emo 📦, with a failsafe in case the package is not installed .... 

```
.rs.addFunction("getCompletionsEmoji", function(token)
{
  tryCatch( {
      results <- emo::ji_completion(sub("^[:]","", token))
      .rs.makeCompletions(
         token = token,
         results = unname(results),
         packages = names(results),
         quote = FALSE,
         type = .rs.acCompletionTypes$EMOJI,
         overrideInsertParens = TRUE,
         excludeOtherCompletions = TRUE
      )
  }, error = .rs.emptyCompletions() )

})
```

(but this could be reworked to eliminate the dependency on the package, by e.g. hosting some json file on the client side

emoji completions are triggered based on the regex `"[:][a-zA-Z0-9_]+"` in these contexts: 
- in a single line string (assuming that matching the regex means we are not in business for file completion) 
 - in a multi line string
 - in comments
 - in the text of a markdown doc. 

I've only tested it on my 💻 , idk what it looks like on e.g. windows. no idea if ace or chrome render the emojis correctly. 

I started this based on the master branch. Not sure I can easily rebase it on some other branch if needed, but I guess I could redo the edits if necessary.

### CODE REVIEW

**Comment by jmcphers** [comment]
@kevinushey could you review this in detail?

@romainfrancois a few high-level remarks:

1) could you remove the whitespace changes?

2) we're close to shipping RStudio 1.1 and aren't taking changes of this magnitude for the release; we will merge this onto 1.2 when we take it (you can rebase onto 1.2 now if you prefer and PR onto that branch)

**Comment by romainfrancois** [comment]
I'll try to rebase using git, but it's not something i do often and master seems quite different from 1.2. 

The changes however only involve a few files, so i guess i can do it manually. 

I've been using this for a few days, writing a few md files etc i love it, and i think people will too. And this was an excuse to get familiar with the codebase, so hopefully (time permitting etc ...) there should be more. 

@kevinushey, i guess it makes more sense to wait for a new pr against 1.2.

**Comment by romainfrancois** [comment]
And also, I found the setting in atom that caused many unintentional whitespace changes. the next PR should be much more readable . 🙊

**Comment by romainfrancois** [comment]
Closing this, as this was replaced by #1462 which is cleaner (re whitespace changes) and based on v1.2

**Pull request closed without merging**
