### PR TITLE
quarto preview open in window

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

adress #11096 

### Approach

Also call `showInViewer()` when `QuartoPreview` is already running and needs a refresh. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
When the "Preview in Viewer pane" is first selected, the preview appears in the viewer pane, and does get refresh if the render button is used again, but if the preference is changed, then a window is not open. This PR does open the window. 

Unfortunately, this means that a new window appears each time the button is pressed, which is unfortunate. 

An alternative would be to keep track of the viewer type when the `QuartoPreview` object is created, and have something like: 

```cpp
      if (s_pPreview && s_pPreview->isRunning() && (s_pPreview->port() > 0) &&
          (s_pPreview->previewFile() == previewFilePath) &&
          (s_pPreview->format() == format &&
           !s_pPreview->hasModifiedProject()) && 
           s_pPreview->rmdViewerType() == prefs::userPrefs().rmdViewerType() // <<<<<< 
      )
      {
         json::Object eventJson;
         eventJson["id"] = s_pPreview->jobId();
         module_context::enqueClientEvent(ClientEvent(client_events::kJobsActivate, eventJson));
         return s_pPreview->render(editorState);
      }
     else
      {
         return createPreview(previewFilePath, format, editorState);
      }
```

so that the preview object is recreated when the preference has changed. 

Or should the preview open a satellite window instead of a browser window ?

**Comment by jjallaire** [comment]
I don't think it's worth the bother of a window appearing every time you hit the button (but I could be missing something?)

**Comment by romainfrancois** [comment]
Trying another way. 

The `QuartoPreview` job remembers the viewer type from when it was created, so that `quartoPreviewRpc()` can recreate it if it differs from the current viewer type: 

 - "Preview in Viewer pane" is first selected, so Render opens or update the Viewer pane
 -  then "Preview in Window" is selected, a new job replaces the old one and a browser window is open
 -  Clicking again on Render does *not* open a new window

**Comment by jgutman** [comment]
Additionally, if I make a change to the qmd file and re-render, I have to manually click refresh in my browser tab in order to view the new output. This seems like a poor experience. Maybe it would be better to go back to opening a new window/tab each time you render, but closing the previously opened one if possible? Or otherwise, forcing a refresh and activation of focus at the least; but I'm not really familiar with what's possible here

**Review by jgutman — CHANGES_REQUESTED** [review]
I don't think it's a good UX for the user to have to manually navigate back to the browser window if they've lost focus, manually hit refresh on the browser window, and manually navigate and reopen the file if they've closed the browser window/tab entirely

**Comment by romainfrancois** [comment]
I agree, the problem is this goes to a browser window, and we can't control that. Maybe there's a reason for this instead of a window that is managed by the ide (as it's the case for Rmarkdown) document: 

image

Here you can ultimately go to a browser, and then it's ok to lose control, but the satellite is managed by rstudio, and so does refresh as needed.

**Comment by romainfrancois** [comment]
In the meantime, perhaps we can remove the "Preview in window" choice ? The user can always have it in a browser window by clicking this in the viewer: 

image

> Is there a reason, or have we just not done that yet? Can we file an issue to do that same behavior for quarto similar to how we do it for Rmarkdown?

I'm not why "Preview in window" actually does "preview in a browser window" for quarto documents. cc @jjallaire

**Comment by romainfrancois** [comment]
I'll merge this, as it improves on the current situation where: 
 - quarto render with "Preview in Viewer" is first selected
 - Then "Preview in Window" is selected
 - Nothing seems to happen when render again. 

With this PR, a browser window is open in that case, which I believe fixes the issue reported in https://github.com/rstudio/rstudio/issues/11096

We can follow up with an issue to actually open in a rstudio managed window instead of browser.

**Pull request merged**
