### PR TITLE
fix compilation errors that occur as a result of GCC concept checks

### PR DESCRIPTION
**Pull request by jjallaire**
@kevinushey Could you review and merge as a sanity check?

### CODE REVIEW

**Comment by howarthjw** [comment]
This change fails to compile against the Apple Clang 6.1 compiler using libc++ on darwin14 when applied to rstudio -0.98.1103. The error is...

cd /sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/build/src/cpp/core && /usr/bin/c++   -DBOOST_ASIO_DISABLE_KQUEUE -DBOOST_ENABLE_ASSERT_HANDLER -I/sw/Library/Frameworks/R.framework/Versions/3.2/Resources/include -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -std=c++11  -stdlib=libc++ -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -isystem /sw/opt/boost-1_58/include -I/sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/src/cpp/core/include -I/sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/build/src/cpp/core    -Wall -pthread -o CMakeFiles/rstudio-core.dir/StringUtils.cpp.o -c /sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/src/cpp/core/StringUtils.cpp
In file included from /sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/src/cpp/core/StringUtils.cpp:29:
/sw/src/fink.build/rstudio-desktop-0.98.1103-4/rstudio-0.98.1103/src/cpp/core/include/core/json/Json.hpp:81:15: error: no matching member function for call to 'push_back'
      results.push_back(val[i]);
      ~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:697:36: note: candidate function not viable: no known conversion
      from 'const_reference' (aka '__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >') to 'const value_type' (aka 'const
      json_spirit::Value_impl<json_spirit::Config_map<std::__1::basic_string<char> > >') for 1st argument
    _LIBCPP_INLINE_VISIBILITY void push_back(const_reference __x);
                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:699:36: note: candidate function not viable: no known conversion
      from 'const_reference' (aka '__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >') to 'value_type' (aka
      'json_spirit::Value_impl<json_spirit::Config_map<std::__1::basic_string<char> > >') for 1st argument
    _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                   ^
1 error generated.
src/cpp/core/CMakeFiles/rstudio-core.dir/build.make:655: recipe for target 'src/cpp/core/CMakeFiles/rstudio-core.dir/StringUtils.cpp.o' failed

**Comment by jjallaire** [comment]
Just made a change that should resolve this. Could you try compiling again?

**Comment by howarthjw** [comment]
I don't know if it makes sense but using a cast of json::Array allows this change to compile on Clang 6.1 against libc++ on darwin14.

      results.push_back((json::Array)val[i]);

**Comment by howarthjw** [comment]
I can confirm that...

results.push_back(val[i] ? true : false);

also eliminates the compile error with Clang 6.1 and libc++ on darwin14.

**Comment by kevinushey** [comment]
Thanks! This looks good to me as well so I'll merge it.

**Comment by jjallaire** [comment]
That compiles but would actually break the feature!

Did you try the variation I just pushed?

On Apr 25, 2015, at 7:15 PM, howarthjw <notifications@github.com> wrote:

I don't know if it makes sense but using a cast of json::Array allows this
change to compile on Clang 6.1 against libc++ on darwin14.

  results.push_back((json::Array)val[i]);

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rstudio/pull/395#issuecomment-96290485>.

**Comment by howarthjw** [comment]
Yes, the use of results.push_back(val[i] ? true : false); also solves the
compilation issue on darwin14.

**Pull request merged**
