### PR TITLE
Upgrade to Electron 22.0.0

### PR DESCRIPTION
**Pull request by timtmok**
### Intent
Address #11734 

### Approach
Add node-abi dependency to ensure it is on a version that supports the Electron version.

### Automated Tests
Electron unit tests pass

### QA Notes
None 

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
LGTM!

**Comment by kevinushey** [comment]
Should we consider updating the version of `node` used by RStudio internally as well?

**Comment by timtmok** [comment]
> Should we consider updating the version of `node` used by RStudio internally as well?

That's a good idea. It looks like it wasn't updated since February and I guess 16.14.0 was the latest LTS at the time.

**Comment by timtmok** [comment]
Create issue #12424

**Pull request merged**
