### PR TITLE
publish single rmd website shiny withoiut wizard

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #9873

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
I don't think it is quite there yet because I'm getting: 

image

As opposed to this from the rendered shiny app in the viewer pane: 

image

**Comment by jjallaire** [comment]
I would ask @jmcphers about what might be going wrong here

**Comment by kevinushey** [comment]
@romainfrancois are you still planning to take a look at this?

**Comment by romainfrancois** [comment]
I'd happily give it back, I'm not that comfortable about the publishing aspect.

**Pull request closed without merging**
