### PR TITLE
Remove 'Classic' theme and supporting resources

### PR DESCRIPTION
**Pull request by jmcphers**
### Intent

This change removes the RStudio Classic theme, with the goal of addressing (in the most brutal way) a couple of issues with this theme while reducing the test matrix and code complexity.

Addresses https://github.com/rstudio/rstudio/issues/9738.

### Approach

If this change looks dramatic, it is: the two "modern" themes are, as it turns out, just wallpaper over the Classic theme. Many decorative images, elements, and styles that make up the Classic theme start out visible but are then hidden, removed, or overridden by the modern themes. 

As part of the goal of this change is to reduce surface area and improve code quality, I've gone through and removed all of the decorative images and, where appropriate, entire HTML elements that were only used to support Classic. CSS rules only active in Classic have been removed and recombined. This made the change quite a lot riskier but also leaves us with very little (hopefully no) vestigial code. 

For CSS files (the bulk of this change), the procedure is to remove the `.rstudio-themes-flat` selector and then push any rules it contained as new defaults, working backwards and removing images, then elements that are no longer referenced.

### Automated Tests

No new functionality is introduced by this PR, so nothing new to test. 

### QA Notes

The good news is that this change is almost purely visual; the bad news is that anything visual could be affected. I would recommend a quick sanity pass over all windows and dialogs, spot checking various combinations and looking for color or alignment issues:

- Dark vs. Light
- Desktop vs. Server
- Modern vs. Sky

While undergoing this work I noticed a number of visual nits, some of which I corrected ... and some of which I let be. Before filing a bug, compare to a copy before the change to so you can note that it's a regression (but file the bug either way!). 

If a user previously had the Classic theme enabled, they should see "Modern" show up instead. 

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
Whew! So much glorious red.

Will there need to be any similar tweaks in rstudio-pro for pro-only UI?

**Comment by jmcphers** [comment]
No, there's nothing in the Pro UI that gets themed (aside from common UI elements already covered here) AFAIK. I will check after merge, though.

**Comment by GCRev** [comment]
For reference: what is the design intent behind having a separation between "Editor Theme" and "RStudio Theme?" Is the Editor theme just meant for source editors and similar panes, while the RStudio Theme is for the rest of the UI, like menus and floating windows (pop-ups)?

**Comment by jmcphers** [comment]
That's right, there are a ton of editor themes but only two RStudio themes now (Modern and Sky). The editor themes only affect the source editor in principle, but since their CSS is injected at the top level it is possible to use them to override UI elsewhere and make a full-blown IDE theme. See the rsthemes package for lots of daring examples:

https://github.com/gadenbuie/rsthemes

**Comment by GCRev** [comment]
I've tested server and QT desktop, both with modern, sky, and various dark themes. I haven't seen anything egregious, as far as layout is concerned, which is caused directly by changing the styles.

@jmcphers you mentioned in the description that you fixed a couple of visual nits... 

Are we focusing on just verifying that there aren't any unwanted layout adjustments, or are we also verifying that dark themes work without doing something strange... like what happens when you have a dark theme and you look in the markdown quick reference:

image

If not, and those issues can be addressed in another ticket, then we should be able to close the [original issue](https://github.com/rstudio/rstudio/issues/9738). I scanned over every reference in CSS to the "alternate" theme and never saw any layout-changing styles; they were only colors or "outline," which doesn't affect layout. We should be able to assume that the layout between the "sky" and "modern" themes are identical, and if there aren't any layout issues with "modern," then there won't be any in "sky" either.

Also... this might be radical idea (and not for PT), but I think we should remove the IDE theme selector altogether, eventually, and clean out even more of the css files. Since we give editor themes the ability to inject over the entire IDE, it should be those themes which ultimately have control over everything. This is particularly evident when using dark editor themes, where the dark IDE theme implicitly overrides the user's selection of "modern" or "sky" anyway. We can keep our light and dark themes internally for editor themes that do not provide overrides, which is how it works currently.

**Comment by jmcphers** [comment]
>  like what happens when you have a dark theme and you look in the markdown quick reference:

Does that happen in dark themes _before_ the change? This change should not introduce any regressions, so if it was that way before then just file an issue.

> but I think we should remove the IDE theme selector altogether, eventually, and clean out even more of the css files

I'm a fan!

**Comment by GCRev** [comment]
@jmcphers I verified that this visual quirk has been there since before the refactor, so it isn't a regression.

**Pull request merged**
