### PR TITLE
avoid querying clipboard while modal active

### LINKED ISSUE #1587: File Open dialog slow on RStudio Desktop for Linux
https://support.rstudio.com/hc/en-us/community/posts/115007856187-Dialog-file-slowness-under-Fecora-Core-26-rstudio-1-1-

> Since version 1.1, the file dialog is incredibly slow under my Fedora Core 26. Each time I have to "open" a file, the dialog freezes as soon as I try to type a few character or to change the path. Is this a known issue? How can I help?

https://community.rstudio.com/t/save-as-dialog-very-slow-in-rstudio-preview-on-ubuntu/1669

> When selecting “Save As…” from the “File” menu, the dialog opens immediately but it takes up to seconds until the window is filled with contents. Typing a file name also feels very sluggish. This does not occur in 1.0.153, only in 1.1.379 (and also the previously released preview version). I’m on Ubuntu 17.04.
... 
> I have the same problem here! Sometimes it completely blocks RStudio and I need to reopen

### PR DESCRIPTION
**Pull request by kevinushey**
This should fix #1587.

### CODE REVIEW

**Comment by krlmlr** [comment]
If you could make a `.deb` available, I can give it a try. The most recent nightly doesn't fix the problem yet (of course).

As a side note, the clipboard override that happens in the affected routine looks dubious to me. I did notice the `"\x01"` characters appearing in the clipboard under some circumstances, but maybe there's a way to fix this problem at the root? The problem didn't affect me that much because I'm using a clipboard ring -- if we can't fix at the root and need to work around, maybe the RStudio IDE could implement a clipboard ring internally and filter the `"\x01"` when pasting (and also when the main window loses focus)?

**Comment by lepennec** [comment]
I can confirm it solves the issue with Fedora 26. Thanks!

**Comment by krlmlr** [comment]
Thanks! Solves the problem for me in Ubuntu GNOME.

**Comment by cranedroesch** [comment]
Glad you guys have fixed the problem, but would appreciate if you could let me (and my fellow muggles) know how to access your fix.  It's not a problem solved by `apt-get update && apt-get upgrade` yet.

**Comment by rmflight** [comment]
@cranedroesch probably by installing a daily build from https://dailies.rstudio.com/

**Pull request merged**
