### PR TITLE
make Shift+Command+Zero the sole shortcut for restartR on Mac

### PR DESCRIPTION
**Pull request by gtritchie**
### Intent

Prompted by #7695

On Mac there are two shortcuts for Restart R. <kbd>Shift+Command+F10</kbd> (which is the shortcut on Windows and Linux as well), and the undocumented Mac-only <kbd>Shift+Command+0</kbd>.

<kbd>Shift+Command+F10</kbd> is shown in the keyboard shortcuts dialog, on the Session menu, and in the keyboard shortcut help, though it is shown as <kbd>Shift+Command+0</kbd> on the command palette. This is makes it unclear what to do if a user wants to change or remove this shortcut.

Initially proposed removing <kbd>Shift+Command+0</kbd> shortcut altogether, but in a poll of users, those who knew about it strongly preferred it, and used it frequently.

### Approach

On Mac make <kbd>Shift+Command+0</kbd> the only shortcut for `restartR` command, removing <kbd>Shift+Command+F10</kbd>.

### Automated Tests

No existing tests for individual keyboard shortcuts. I checked and we don't reference F10 in any of our Selenium automation so this shouldn't break, even if run on Mac.

### QA Notes

Verify that hitting <kbd>Cmd+Shift+0</kbd> on Mac triggers Restart R, and is shown in shortcuts dialog, Session menu, command palette, and keyboard shortcut help (both variations, the popup shown when screen reader accessibility is off, the other, a web page, shown when screen reader is enabled).

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
I like this shortcut and intentionally use it pretty regularly though :-/

**Comment by kevinushey** [comment]
That's not a particular convincing argument, but I'm guessing that there are others who have muscle memory for this shortcut built in who do intentionally use it. We could argue that either we leave it on and ask users to disable the shortcut if they don't want it, or flip it around and ask those of us who do like it to add the shortcut ourselves.

**Comment by gtritchie** [comment]
I have no opinion on it, not using it (or having accidentally triggered it that I know of) myself.

If it is widely used we could just leave it as-is, or do something yucky like show a dialog the first time command is triggered by that shortcut asking if they meant it with option to continue, cancel, remove shortcut, etc.

But might all be overkill. Definitely wait and see what Jonathan thinks, too.

**Comment by jmcphers** [comment]
We already have a shortcut for restarting R so I think having this secret *second* shortcut is kind of weird. It's also much easier to add a custom shortcut than it is to disable a built in shortcut (in fact, I'm not even sure that's possible), so I'm inclined to take this change. 

I do worry a little bit that more people might use this than we think, so I just posted a quick poll to Slack to see how what volume of cheese might be transported by this change.

**Comment by gadenbuie** [comment]
I just want to publicly state on the record that <kbd>Cmd + Shift + 0</kbd> is my second favorite shortcut (it was my first favorite shortcut prior to the command palette) and I use it dozens of times a day. Function keys are such a pain on Macs that a shortcut involving functions keys with modifiers isn't really a shortcut. It is a little odd, though, that <kbd>Cmd + Shift + 0</kbd> doesn't even show up in the Keyboard Shortcuts menu. And I wouldn't mind explicitly choosing one over the other if I could only choose one.

**Comment by gtritchie** [comment]
So, perhaps the best approach would be to make <kbd>Cmd+Shift+0</kbd> the only shortcut on Mac for this command (so it shows up in the shortcuts dialog, the menu, etc) and get rid of <kbd>Cmd+Shift+F10</kbd> (again, only on Mac)?

**Comment by kevinushey** [comment]
Or perhaps make Cmd + Shift + 0 the "primary" shortcut, so it shows up first in documentation etc., and have Cmd + Shift + F10 be the fallback?

**Review by jmcphers — APPROVED** [review]

**Pull request merged**
