### PR TITLE
Merge "Clean and Rebuild" and "Install and Restart" into "Install Package"

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #4289  

### Approach

Remove the "Clean and Rebuild" for packages, and only use "Install and Restart", which is renamed "Install Package".

The `--preclean` option is controlled by a "Clean before install" project option, that is checked by default. 

image

The build toolbar gains a `Test` button: 

image

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
This has (but does not use yet): 

image

But I was wondering if this should instead of a project option in: 

image

either just on the install and restart options: 

image

or as an additional checkbox, but here.

**Comment by romainfrancois** [comment]
The other thing is that "Clean and Rebuild" can't entirely go away because it's used for Makefile type projects. Maybe it can be reamed "Make" ?

**Comment by kevinushey** [comment]
Spitballing here, but...

1. We could rename "Install and Restart" to "Install Package",
2. I'm mildly in favor of adding `--preclean` to the `R CMD INSTALL` additional options default text. We might need to decrease the font size a bit to accommodate the extra options, though. Or, I think the "Clean before install" checkbox preference should live as part of that options dialog, just below the "Package directory" UI.

It'd also be nice to add a "Test" button directly to the Build pane toolbar, since I think running tests without a full R CMD check is more common?

**Comment by romainfrancois** [comment]
Updated to use "Install Package". 

I went for the extra checkbox because adding text to the text box would not affect existing projects that would just read the .Rproj: 

```
PackageInstallArgs: --no-multiarch --with-keep.source --install-tests
```

The project file gains a : 

```
PackageCleanBeforeInstall: Yes/No
```

When the setting is not set in the file, the default (true) takes over. Maybe the default should be false considering that historically "Install and Restart" was not doing `--preclean` so that there would be no difference for existing projects. 

Should the global option have a setting that pilots this option when creating a new package project ?

**Comment by romainfrancois** [comment]
> It'd also be nice to add a "Test" button directly to the Build pane toolbar, since I think running tests without a full R CMD check is more common?

Maybe we can remove "Package" here, and have: `Install | Test | Check | More v`

image

Is there an icon we can use for "Test" ?

**Comment by kevinushey** [comment]
> When the setting is not set in the file, the default (true) takes over. Maybe the default should be false considering that historically "Install and Restart" was not doing --preclean so that there would be no difference for existing projects.

I think `--preclean` by default is the right behavior, and I can't think of any common package development scenarios that would be broken by this change so I think it's okay to turn it on by default.

> Maybe we can remove "Package" here, and have: Install | Test | Check | More v

I like that idea.

> Is there an icon we can use for "Test" ?

Maybe this one?

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/commands/testShinytestFile_2x.png

**Comment by romainfrancois** [comment]
I think we can consider a follow up pull request to rebrand "rebuildAll" as "Make" since at this point it's only used for Makefile projects, but I can deal with it here too.

**Comment by MariaSemple** [comment]
Rebasing to `main` as that is now the SW branch.

**Review by kevinushey — APPROVED** [review]
LGTM!

**Comment by jgutman** [comment]
@romainfrancois checking if you wanted to create an issue for tracking the renaming for Makefile projects?

**Pull request merged**
