### PR TITLE
Implement special behaviours for setup chunk popup

### PR DESCRIPTION
**Pull request by kevinushey**
This PR implements special behaviours for the setup chunk.

setup-chunk

Basic outline of how it works:

1. The client asks the server to parse the chunk and scrape out the `opts_chunk$set` calls within,
2. The UI is initialized based on the output of that parse,
3. On each synchronization, the appropriate `knitr::opts_chunk$set` call is emitted at the bottom of the chunk, replacing the old call if it exists.

I believe this is ready for merge, although we might prefer to refine some behaviours:

- Should we make an attempt to preserve the original option order, or is it okay to take over and attempt to sort them in a sensible way? (ie by grouping options with similar functionality together in output)

- Any other tweaks (additions or otherwise) we'd want to make to the setup chunk?

### CODE REVIEW

**Comment by jjallaire** [comment]
This looks great! Here's the final refinements I recommend:

1. I think it's okay if we don't preserve the original option order (users that don't like our re-writing can just not use the UI)

2. Let's have the option icon be right aligned in the setup chunk (i.e. where the Run button is in other chunks).

3. I think we discussed *not* having the figure options be in the setup chunk (since they can/should be set in the YAML potentially on a per-format basis).

4. We should have a header that indicates that these options are the document defaults. This could be in the form of bringing back the header element that I believe we stripped out of this component when we ported it from elsewhere in the code or it could just be some bolded text. I think the header should be: "Default Chunk Options"

5. What do you think our default Rmd document should include for the setup chunk? We could have a call to `knitr::opts_chunk$set` *or* we could just have a simple comment saying: 

```r
# setup chunk (load libraries, set chunk options, etc.) 
```

I say this because it seems strange that we'd include a call to `knitr::opts_chunk$set` that just reflects the default Rmd options. Let me know what you think.

**Comment by jjallaire** [comment]
Considering the topic of the default template some more, I think that we should include some default settings so that the user is not confronted with the concept of another level of "default" (those set by rmarkdown::render) that is inherited. I propose we do this:

```r
knitr::opts_chunk$set(echo = TRUE)
```

Which I believe corresponds to "Show Output and Code"

We'd also want to include an option like "(Use Default Options)" which indicates we want to inherit whatever the default is for the current format.

**Comment by kevinushey** [comment]
Just to make sure -- did you mean something like this for the setup chunk?

screen shot 2015-06-24 at 10 44 37 am

**Comment by jjallaire** [comment]
Yes (but I think we want the default to be "Show Output and Code" as per my
other comment on the PR

**Comment by kevinushey** [comment]
Great -- I updated the template to just use `knitr::opts_chunk$set(echo = TRUE)` and the popup automatically reflects that when shown.

**Comment by jjallaire** [comment]
Excellent, I think we've got it nailed!

**Comment by kevinushey** [comment]
Sorry, one more bit to fix -- character options can lose their quotes on synchronization.

**Pull request merged**
