### PR TITLE
Exposes GWT CSS classes as requested.

### LINKED ISSUE #3368: Add stable CSS class names for themeable elements
### System details

    RStudio Edition : Desktop
    RStudio Version : current master
    OS Version      : 10.13.4
    R Version       : 3.5.1

screen shot 2018-08-24 at 2 58 45 am

I have been working on customizing the theme of RStudio via a custom [rstheme](https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme). In there, I have to override the style for a number of UI classes. For example,
```css
/* pane toolbar */
.GOLWFGSBG-B, .GOLWFGSBJAC, .GOLWFGSBEV {
     background: #404040 !important;
}
/* popup */
.rstudio-themes-flat.rstudio-themes-dark-menus .GOLWFGSBI1 .popupMiddleCenter {
     background: #404040 !important;
}
```
The UI items do not have proper names and have only the generated names (they are generated by gwt!?). The random generated names make theming RStudio hard and the resulting theme may not be as well portable.

### PR DESCRIPTION
**Pull request by MariaSemple**
This PR exposes the GWT CSS classes as requested in #3368. (See https://github.com/rstudio/rstudio/issues/3368#issuecomment-418568294).
Closes #3368.

### CODE REVIEW

**Comment by kevinushey** [comment]
Do we need a mechanism that helps us enforce the fact that these CSS classes should not change (to support custom themes)?

@randy3k would you be willing to confirm that this PR gives you enough for your own dark theme with stable class names?

**Comment by randy3k** [comment]
One more class and all is good.
```
.org-rstudio-core-client-theme-res-ThemeStyles-minimizedWindowObject .org-rstudio-core-client-theme-res-ThemeStyles-center
```
screen shot 2018-09-13 at 12 12 35 am

**Comment by jmcphers** [comment]
I'd suggest two small improvements:

1. We should have some kind of decoration at the selector that indicates that we've exposed it externally and shouldn't change its name without consideration. I don't think it's worth building a system to mechanically enforce this (just a comment at the declaration site is fine)

2. I think that all selectors exposed in this way should have a common prefix (such as `rstheme`) to make them possible to locate mechanically should we need to do so in the future.

**Comment by randy3k** [comment]
I actually need to override some other classes with prefix `gwt-`, not sure if they are stable or not.

**Comment by jmcphers** [comment]
@randy3k Those are stable unless GWT changes them (very unlikely!)

**Pull request merged**
