### PR TITLE
Update EVP to work with OpenSSL1.1.0

### PR DESCRIPTION
**Pull request by JanMarvin**
In addition to a previous pull request of mine.

I assume this part of code was introduced after the release of 1.1. I use this to build locally for a while. Once this gets merged https://github.com/JanMarvin/rstudio-archlinuxpkg/blob/master/rstudio/openssl11.diff is the only pending change required to build with OpenSSL 1.1.0

Sincerely,
Marvin

### CODE REVIEW

**Comment by JanMarvin** [comment]
Hm, probably it is not backwards compatible https://www.openssl.org/docs/man1.0.2/crypto/EVP_EncryptInit.html

**Comment by JanMarvin** [comment]
`EVP_CIPHER_CTX_new()' was introduced in OpenSSL 0.9.8b (May 2006) should be good to go

**Comment by jmcphers** [comment]
Thanks! I think @kfeinauer is most familiar with this code so I'll defer to his judgement. I saw that you've also made [a few other contributions](https://github.com/rstudio/rstudio/commits?author=JanMarvin); have you signed a CLA for us before?

**Comment by JanMarvin** [comment]
Yes I have already signed one. Thanks

**Comment by kfeinauer** [comment]
@JanMarvin This compiles against older versions of libssl so it would probably be okay. However, I'm confused as to how this gets us to OpenSSL1.1.0 compatibility, since the docs say the following (https://www.openssl.org/docs/man1.1.0/crypto/EVP_CIPHER_CTX_free.html) about one of the functions still in use:

```
EVP_CIPHER_CTX was made opaque in OpenSSL 1.1.0. **As a result, EVP_CIPHER_CTX_reset() appeared and EVP_CIPHER_CTX_cleanup() disappeared.** EVP_CIPHER_CTX_init() remains as an alias for EVP_CIPHER_CTX_reset().
```

It looks like the pattern of allocation/deallocation should be reworked if we are going to target 1.1.0. See this stackoverflow answer: https://stackoverflow.com/a/39762336

**Comment by JanMarvin** [comment]
@kfeinauer I have changed the `_cleanup()` to `_free()` as suggested in the OpenSSL wiki and in the stackoverflow article you linked. Is that what you requested?

**Comment by kfeinauer** [comment]
@JanMarvin Looks good to me. Will leave the final merge up to @jmcphers.

I also wrote a unit test for this functionality (since it is not a frequent code path) just to make sure it is working as expected. I'd recommend adding it to the PR so we can get the test in when the PR merges.


*src/cpp/core/system/CryptoTests.cpp*
```cpp
/*
 * CryptoTests.cpp
 *
 * Copyright (C) 2017 by RStudio, Inc.
 *
 * Unless you have received this program directly from RStudio pursuant
 * to the terms of a commercial license agreement with RStudio, then
 * this program is licensed to you under the terms of version 3 of the
 * GNU Affero General Public License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
 *
 */

#include <core/system/Crypto.hpp>

#include <tests/TestThat.hpp>

namespace rstudio {
namespace core {
namespace system {
namespace tests {

context("CryptoTests")
{
   test_that("Can AES encrypt/decrypt")
   {
      // generate a random 128-bit key and IV
      std::vector<unsigned char> key;
      std::vector<unsigned char> iv;
      Error error = core::system::crypto::random(16, &key);
      REQUIRE_FALSE(error);
      error = core::system::crypto::random(8, &iv);
      REQUIRE_FALSE(error);

      // construct the data to encrypt
      std::string payload = "Hello, world! This is a secret.";
      std::vector<unsigned char> data;
      std::copy(payload.begin(), payload.end(), std::back_inserter(data));

      // encrypt the data
      std::vector<unsigned char> encryptedData;
      error = core::system::crypto::aesEncrypt(data, key, iv, &encryptedData);
      REQUIRE_FALSE(error);

      // decrypt the encrypted data
      std::vector<unsigned char> decryptedData;
      error = core::system::crypto::aesDecrypt(encryptedData, key, iv, &decryptedData);
      REQUIRE_FALSE(error);

      // verify that the decryption gives us back the original data
      std::string decryptedPayload;
      std::copy(decryptedData.begin(), decryptedData.end(), std::back_inserter(decryptedPayload));
      REQUIRE(payload == decryptedPayload);
   }
}

} // end namespace tests
} // end namespace system
} // end namespace core
} // end namespace rstudio

```

**Comment by JanMarvin** [comment]
Thanks, applied your unittest.

**Comment by jmcphers** [comment]
@kfeinauer Thanks for leading the review on this one. 

@JanMarvin Very much appreciate the contribution!

**Pull request merged**
