### PR TITLE
add ui toolbar menu to insert alternate notebook chunks

### PR DESCRIPTION
**Pull request by javierluraschi**
screen shot 2016-08-05 at 10 55 54 pm

### CODE REVIEW

**Comment by jjallaire** [comment]
Let's add icons for these. To do that you just add a PNG with the same name as the command here: https://github.com/rstudio/rstudio/tree/master/src/gwt/src/org/rstudio/studio/client/workbench/commands

You can find the icons to use in the filetypes package: https://github.com/rstudio/rstudio/tree/master/src/gwt/src/org/rstudio/studio/client/common/filetypes

(not that you will need to make a copy of the icon, we don't currently have a way of sharing these icons across contexts).

**Comment by javierluraschi** [comment]
Much better! 

screen shot 2016-08-06 at 9 29 02 am

**Comment by jjallaire** [comment]
Here's another refinement:

screen shot 2016-08-06 at 10 15 58 pm

The idea is to omit the "Chunk" suffix which in a vacuum would make the menu too narrow but adding the keyboard shortcut to "R" I think closes the gap enough. Let me know what you think.

Committed here: https://github.com/rstudio/rstudio/commit/195742706d23fefc52e9501de61e6388d49a6f56

**Comment by javierluraschi** [comment]
Looks great!

**Pull request merged**
