### PR TITLE
update to pdf.js 1.3 series (from 1.0)

### PR DESCRIPTION
**Pull request by kevinushey**
Not quite ready for merge -- this PR encompasses the work done by @jmcphers; the checklist just marks remaining checklist items.

## TODO

- [x] Verify that SyncTex works,
- [x] Verify PDFs don't fail to open on FireFox,
- [x] Test on Qt (RStudio Desktop on Linux, Windows)

### CODE REVIEW

**Comment by kevinushey** [comment]
Unfortunately updating pdf.js doesn't fix the Firefox issue. I do see some errors in the JS console though when the page fails to open:

```
TypeError: this.pdfRenderingQueue is null
PDFViewerApplication.forceRendering()
 viewer.js:193
PDFViewerApplication.switchSidebarView()
 viewer.js:195
E2e/r()
 rstudio-1.js:1677
E2e/s/d()
 rstudio-1.js:1677
```

which suggests to me that there's some kind of timing issue with the rendering queue. I'll dig in and see if I can find an appropriate fix.

**Comment by kevinushey** [comment]
Okay, I think I have a fix -- we have loader code that waits for the `PDFView` object to be ready; we merely checked that such a thing existed and was an object -- now we also ensure that the object is actually initialized as well (by checking the `initialized` field).

**Comment by jjallaire** [comment]
Terrific! Let me know when you think the branch is ready for merge (are
there indeed other API changes we have to work through?)

**Comment by kevinushey** [comment]
I think we're good to go. `pdf.js` is unfortunately still a bit buggy on desktop (tested on Ubuntu) but it seems these issues all existed with the older `pdf.js` as well.

**Pull request merged**
