### PR TITLE
enable reindent, soft-wrap for Stan

### PR DESCRIPTION
**Pull request by kevinushey**
Requested here: https://community.rstudio.com/t/feature-request-re-stan-support-in-rstudio-1-2/25272

This change should be small and safe enough but I understand if we'd rather get this in for v1.2-patch or v1.3.

### CODE REVIEW

**Comment by jmcphers** [comment]
Ordinarily I'd hold this since it's not critical but since we haven't made an RC build yet and it appears extremely scoped I think we can take it.

**Comment by ebuhle** [comment]
Thanks! I know these seem minor, but IMO (1) having auto-indent enabled and (2) being able to turn off automatic line-wrapping will make the difference between usability and non-usability for all of the rich support for Stan code in RStudio v1.2. I'm looking forward to it!

**Comment by ebuhle** [comment]
In testing the v1.2 preview release, I've noticed that auto-indent for Stan files doesn't work the same way it does for R scripts. Expressions following `for` and `if` statements are only auto-indented if those expressions are enclosed in curly braces. So, for example, auto-indent in a Stan file would produce the following:

```
for(i in 1:N) {
  x[i] = i;
}
```

```
for(i in 1:N)
x[i] = i;
```

whereas in an R script, both would be properly indented.

**Comment by kevinushey** [comment]
@ebuhle would you mind filing that as a separate issue so we don't lose track of it?

**Pull request merged**
