### PR TITLE
ensure head, tail align properly on UTF-8 characters

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/rstudio/issues/5689.

### CODE REVIEW

**Comment by kevinushey** [comment]
This PR deserves a test; I'm going to try and add one.

**Comment by kevinushey** [comment]
Bleh. Our test harness fails to run because of the way the helper encoder / decoder is injected.

**Comment by kevinushey** [comment]
Try as I might, I cannot get our unit test harness to run these tests.

It seems like the (?) use of native browser APIs (e.g. Uint8Array) causes problems for the headless unit test executor?

**Comment by jmcphers** [comment]
Yeah, the browser is simulated in the unit tests. http://www.gwtproject.org/doc/latest/DevGuideTestingHtmlUnit.html

**Pull request merged**
