### PR TITLE
Use appropriate source markers for different test results

### PR DESCRIPTION
**Pull request by javierluraschi**
Fix for https://github.com/rstudio/rstudio/issues/2483 to support warnings and infos as well:

screen shot 2018-03-22 at 3 55 10 pm

### CODE REVIEW

**Comment by jjallaire** [comment]
I'd say that we should only open the Issues by default if there is a warning or an error (as the navigation to issues is a cue to the user that something needs addressing)

**Comment by javierluraschi** [comment]
@jjallaire looks like this is already implemented by default since we borrowed the same code for other type of warnings and errors.

**Comment by javierluraschi** [comment]
Actually, the behavior today is to only open the issues if there is an error, warnings and infos remain unopened, but my guess is that this is the behavior we would want as well.

**Comment by jjallaire** [comment]
Yes, I think that sounds like exactly the right behavior.

**Comment by jjallaire** [comment]
A couple of things to follow up on here. In one dimension I think the new behavior may make things worse: when a test fails you often need to see the related output to diagnose it (in fact this is more valuable than navigating to the source code of the test). testthat actually does some truncation of output to ~ 12 lines (or at least it used to) and this can even obscure things (whereby you need to dig into the logs on disk to find the output). 

With this UI we are hiding the test output / error messages entirely. I don't think you can actually fix a test without seeing this output. We could try adding the output within the error item (and expanding the error item to show all of the output when you click it).

Also, highlighting info items doesn't seem that useful as I saw an info item and clicked on it -- this resulted in navigation to a source location but no actual display of the "info".

@wch and @hadley Interested to get your takes here.

**Comment by hadley** [comment]
Yeah, it definitely needs to show the failing error text, and ideally it would have a call stack/tree with clickable line numbers. I'm happy to make a custom reporter for RStudio if that makes things easier.

(testthat only shows 12 lines of code when run inside R CMD check because that's what CRAN wants)

**Comment by wch** [comment]
I have comments about the Output/Issues views in general. When I've been working on C/C++ code and have errors, it shows them in the Issues panel. I like that the Issues view makes it easy to see all the errors and to navigate to the corresponding code. However, sometimes the information in the Issues view isn't detailed enough, and there have been a number of times where I've puzzled over the text for a while, before finally remembering that I could click on Output to see more context. For a long time, it wasn't clear to me that (A) those were two views (full vs summarized) of the same information, and (B) that I even could click on Output at all. 

It might help a bit if Ouptut and Issues were tabs instead of buttons, but I'm not completely sure.

Another thought: what if there was an icon on the right side of each issue, where, if you clicked on it, it would switch to the Output pane and highlight the corresponding text?

**Comment by jjallaire** [comment]
I think Winston's idea of the icon on the right side is a great one as this is indeed a problem with summarized views of diagnostics. We actually already have that UI for LaTeX compilation errors:

screen shot 2018-03-27 at 7 38 38 pm

**Comment by hadley** [comment]
In an ideal world you'd get an expando so you could see the detail in-line, but I understand that would be more UI work (and possibly hard to generalise).

**Comment by jjallaire** [comment]
I agree that the expando would be better (the selected item could show the detail). I actually don't think this would necessarily be too difficult to pull off. I'll talk to @javierluraschi about it and see what we can do.

**Comment by javierluraschi** [comment]
Expando work tracked with https://github.com/rstudio/rstudio/pull/2484#issuecomment-375674412, hoping I can take a look at that for 1.2.

**Pull request merged**
