### PR TITLE
color indent guides

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #11023 

### Approach

css :nth-child() magic. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Can we use `linear-gradient()` : 

```css
.ace_line .ace_indent-guide:nth-child(7n){
  background: linear-gradient(to left, #ed90a4bb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+1){
  background: linear-gradient(to left, #d3a263bb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+2){
  background: linear-gradient(to left, #99b657bb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+3){
  background: linear-gradient(to left, #33c192bb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+4){
  background: linear-gradient(to left, #00bdcebb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+5){
  background: linear-gradient(to left, #94a9ebbb 1px, transparent 1px, transparent);
}
.ace_line .ace_indent-guide:nth-child(7n+6){
  background: linear-gradient(to left, #dc91dbbb 1px, transparent 1px, transparent);
}
```

gives: 

image

This should probably have a setting similar to `[ ] Rainbow parentheses` that would inject/remove the styles ?

**Comment by kevinushey** [comment]
> This should probably have a setting similar to [ ] Rainbow parentheses that would inject/remove the styles ?

I think so. What do you think about adding a new section to the Options -> Code -> Display pane, to collect some of these options? For example:

## Syntax

- [ ] Highlight R function calls
- [ ] Enable preview of named and hexadecimal colors
- [ ] Use rainbow parentheses
- [ ] Use rainbow indent guides

I'm not sure if you already have some ideas for how to toggle these styles on and off, but a potential way would be to hide these styles behind a custom class, e.g.

```
.rstudio_rainbow_ident_guides .ace_indent-guide { ... }
```

And then, whenever this preference is enabled, we'll toggle that class on the Ace editor instances.

**Comment by romainfrancois** [comment]
Currently at: 

image

But I'm wondering if we should rather have: `Indent guides` be a choice between "none", "default", and "rainbow"

**Comment by romainfrancois** [comment]
Unfortunately because I believe of `line-height:` we get a discontinuity in the indent guides: 

image

where a `line-height` of 1 gives a continuous: 

image

Not sure how to deal with this.

**Comment by kevinushey** [comment]
> But I'm wondering if we should rather have: Indent guides be a choice between "none", "default", and "rainbow"

I think that's a good idea; otherwise someone might be confused with the current scheme where indent guides are disabled but they tried to enable rainbow indent guides. (We could also have options like "rainbow line" versus "rainbow fill" if you wanted to add an option for highlighting the whole indent.)

> line-height is causing other issues, e.g. in console output for things like cli::boxx() :

We could explore changing this in a separate PR; we'd just have to double-check it doesn't cause any other kinds of regressions in how things are displayed.

**Comment by romainfrancois** [comment]
Options: 

image

Rainbow lines: 

image

Rainbow fills: 

image

This uses the same colors as "rainbow parentheses", so it's not really rainbow, should it ?

**Comment by kevinushey** [comment]
> This uses the same colors as "rainbow parentheses", so it's not really rainbow, should it ?

I like the idea of the guide color matching the rainbow parenthesis colors, I think... but maybe we can iterate on that later?

**Review by kevinushey — APPROVED** [review]
LGTM!

**Pull request merged**
