### PR TITLE
Add i18n for all options menus

### PR DESCRIPTION
**Pull request by rohank07**
### Intent

See #9083 for more context on i18n efforts.
This PR enables i18n for all menus under Options->* (or Tools->Global Options on desktop). This excludes most of the values produced by the settings (preferences) json files, though there is some preliminary work there. The rest will be addressed in a separate PR.

### Approach

This is a larger PR as there were many UI components involved in these menus and widgets, most of which required updating the java code and creation of the corresponding constants interface and _en.properties file.
Implementation follows the same pattern from [#9485](https://github.com/rstudio/rstudio/pull/9485) as described in gwt/tools/i18n-helpers/README.md. Running the create_dev_locale.sh will create all the new "dev" locale from any new "en" properties files for easier visual confirmation. Refer to [README](https://github.com/rohank07/rstudio/blob/rohan/i18n-all-options-menu/src/gwt/tools/i18n-helpers/README.md) for more information.

### Automated Tests

No additional testing is added. We are interested in feedback on what testing would be appropriate.

### QA Notes

This change is believed to be fully working without changing the user experience, but feedback is welcome. To confirm i18n is working for the the Options->* menus, while running RStudio in devmode you can do one of:
Modify an entry in one of the new _en.properties files, and refresh RStudio with ant in devmode.
Run create_dev_locale.sh to clone all _en properties files, which will add a prefix of "@" to each constant and message. Then open RStudio using http://localhost:8787/?locale=dev and browse to the Options->* menus. You can also view in desktop mode by swapping the locale element value attribute from value="en" to value="dev" in RStudio.gwt.xml.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

cc @gtritchie

### CODE REVIEW

**Comment by gtritchie** [comment]
Hi, thanks for this great work!

We're nearing end of our current release coding phase and entering a stabilization period, so this will need to wait until we've released and branched before we can look at merging it. Sorry for the delay. Probably closer to the end of August (rough guess).

**Comment by skyeturriff** [comment]
Hi @gtritchie ! Thanks for the update! Just to confirm - are you guys still reviewing/giving feedback on new PRs in the meantime, or is it a hard stop on both reviews and merges?

**Comment by gtritchie** [comment]
Not intentionally stopping giving feedback on PRs, just a lack of time at the moment. I will try to take a look this week!

**Comment by gtritchie** [comment]
Sorry for long delay in looking at this PR. Is this one still valid or is it superseded by the other PR? I will review the smaller one first!

**Comment by skyeturriff** [comment]
This one is still valid but can definitely be looked at after the smaller one! I'll address those conflicts today!

**Comment by gtritchie** [comment]
I wasn't clear, are we still wanting to apply this change? If so it's quite out of date (my fault it has taken so long) and will need to have main merged and any new options UI dealt with before I can review again.

**Comment by skyeturriff** [comment]
No problem at all, we'll get it up to date! 

Did I see correctly - we should look out for some new options UI elements that have been added that will need i18n?

**Comment by gtritchie** [comment]
Yes, I didn't check, but strongly suspect there is some new UI in the Global Options since this was last merged.

**Comment by skyeturriff** [comment]
Hey @gtritchie, everything should be up to date now!

**Comment by skyeturriff** [comment]
Also @gtritchie, realistically, when should we aim to have our PRs in for things we are hoping to have included in your next release?

**Comment by gtritchie** [comment]
> Also @gtritchie, realistically, when should we aim to have our PRs in for things we are hoping to have included in your next release?

Getting this work in by the end of December would be ideal. After that we'll only take critical fixes.

**Comment by skyeturriff** [comment]
I think some of the change requests you left on the other PRs will apply to this one as well, so I can look into those!

**Comment by gtritchie** [comment]
> As another note, I think some of the change requests you left on the other PRs will apply to this one as well, so I can look into those!

Yes, thanks. I haven't re-reviewed this one yet so ping me when it's ready. I'm looking at the others first.

**Comment by gtritchie** [comment]
Note, was told this will be closed and a new PR created.

**Pull request closed without merging**
