### PR TITLE
Fix issue that would keep Secondary (Satellite) Windows Open

### PR DESCRIPTION
**Pull request by matheustavaresdev**
### Intent

This aims to fix an issue that would make Secondary ( Satellite ) Windows open after being closed by clicking on the `X` button.

### Approach

Added a custom `onclose` event for Satellite windows, and disabled that regular window event for those windows. 

### Automated Tests

None

### QA Notes

Refer to #10906

### Checklist

- [X] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [X] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [X] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [X] This PR passes all local unit tests

Addresses #10906

### CODE REVIEW

**Comment by kevinushey** [comment]
This change doesn't feel right to me; the `closeEvent()` implementation specifically checks `window.opener`:

https://github.com/rstudio/rstudio/blob/128552161df9c8463cc92c376d5bc0c2304de261/src/node/desktop/src/main/desktop-browser-window.ts#L272-L291

so it seems like it's intentional that this could would be run for satellite windows as well. (That said, I still don't quite understand the underlying issue here; just that this change doesn't feel quite right)

**Comment by gtritchie** [comment]
I didn't get a chance to review this today, will do so tomorrow. I agree this doesn't look quite right but I only glanced at it.

**Comment by matheustavaresdev** [comment]
> This change doesn't feel right to me; the `closeEvent()` implementation specifically checks `window.opener`:
> 
> https://github.com/rstudio/rstudio/blob/128552161df9c8463cc92c376d5bc0c2304de261/src/node/desktop/src/main/desktop-browser-window.ts#L272-L291
> 
> so it seems like it's intentional that this could would be run for satellite windows as well. (That said, I still don't quite understand the underlying issue here; just that this change doesn't feel quite right)
@kevinushey this code was written before my change

**Comment by matheustavaresdev** [comment]
What I did was to run the same code that was running when the user would press `CMD+W` for when the user would click on the X button as follows:

https://github.com/rstudio/rstudio/blob/bugfix/secondary-editor-keeps-open/src/node/desktop/src/main/satellite-window.ts#L44-L46

Then, I disabled the code that would run simultaneously for when the user would click the `X` button:

https://github.com/rstudio/rstudio/blob/bugfix/secondary-editor-keeps-open/src/node/desktop/src/main/desktop-browser-window.ts#L256-L260

If I didn't make the last change above, something would be messed up and the window would still reopen after app relaunch. The code below would always be triggered, adding a new pending window on app relaunch, and then reopening the satellite window that should be closed.

https://github.com/rstudio/rstudio/blob/bugfix/secondary-editor-keeps-open/src/node/desktop/src/main/gwt-callback.ts#L465-L479

**Comment by gtritchie** [comment]
I'll take a closer look today.

**Comment by gtritchie** [comment]
This is definiltely not the right fix and can cause data loss.

For example, open a file in a satellite window, then modify it but don't save. Then close the window via the [x]. By not calling SatelliteWindow.onClose and letting it cancel the window close operation, we bypass code that checks for modified files and gives the user the chance to save/discard/cancel the close operation.

I have an idea what the problem is; might actually need to be fixed in GWT and not Electron. I'll add more notes once I've dug into that a bit more closely.

**Comment by gtritchie** [comment]
Also, Cmd+W is not supposed to be the same as clicking the [x]. The [x] should close the entire window (even if it has multiple editor tabs in it), whereas Cmd+W should only close the active document. If there is only one document, then it will also close the window.

**Comment by matheustavaresdev** [comment]
> This is definiltely not the right fix and can cause data loss.
> 
> 
> 
> For example, open a file in a satellite window, then modify it but don't save. Then close the window via the [x]. By not calling SatelliteWindow.onClose and letting it cancel the window close operation, we bypass code that checks for modified files and gives the user the chance to save/discard/cancel the close operation.
> 
> 
> 
> I have an idea what the problem is; might actually need to be fixed in GWT and not Electron. I'll add more notes once I've dug into that a bit more closely.

Oh probably that's most likely the case. The code seemed right on the electron side. I did this change to fix the issue for the window reopening on app relaunch. Didn't notice those other case scenarios for testing my fix. Probably will have to undo it and dig it on GWT.

**Comment by gtritchie** [comment]
Closing this PR, will open a new one when we find the right fix.

**Pull request closed without merging**
