### PR TITLE
use unique_ptr to release memory on exit

### PR DESCRIPTION
**Pull request by kevinushey**
This fixes a (likely rare) memory leak that can occur if `runCommand` or `runProcess` were to fail and exit early.

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
LGTM!

**Comment by olivroy** [comment]
I am experiencing more RStudio crashes today..  For example when I try to interrupt the viewer taking a long time.  I don't know how to reproduce, but could this be related to this change?

**Comment by kevinushey** [comment]
It's possible, but it seems unlikely. Are you able to share a reproducible example?

**Comment by olivroy** [comment]
Ok, thanks! I will open a new issue if I notice a pattern!

**Pull request merged**
