### PR TITLE
revise chunk popup options

### PR DESCRIPTION
**Pull request by kevinushey**
Not quite ready for merge, but represents an initial bit of work implementing some of the suggestions we had re: the chunk options popup.

chunk-options

### CODE REVIEW

**Comment by jjallaire** [comment]
Some UI feedback:

* Let's left-align the chunk name and output combo widgets. I think at the same time we should change the caption of "Chunk name" to just "Name".

* I think the default output list item should be "(Use Document Default)" rather than "(Use Current Settings)". My concern is that the use of the word "Current" implies that this state somehow gets toggled within a chunk and that subsequent chunks would then inherit the "Current" state.

* Eliminate the question mark after the checkboxes (it's implied by the checkbox)

* Let's use the phrase "output" rather then "generated document", e.g. "Show warnings in output"

* I think the "Show..." options should be above the figure size option.

* I think there should be a bit more air above the widgets at the bottom (help link and action buttons).

**Comment by kevinushey** [comment]
I think I agree with all of these, but let's confirm what we want each of the options on the Output combo box to do.

- (Use Document Default): unset `eval`, `echo`
- Show Code and Output: set `eval=TRUE, echo=TRUE`
- Show Output Only (Hide Code): set `eval=TRUE`, `echo=FALSE`

Does that sound correct?

**Comment by jjallaire** [comment]
Yup, that sounds right to me!

**Comment by kevinushey** [comment]
Current display:

screen shot 2015-06-18 at 11 38 08 am

I decided to use a similarly themed checkbox for the 'show figure' option just because it felt somewhat awkward seeing a differently-styled checkbox below the tri-state checkboxes; on the other hand the different styling also helped to separate it from the 'standard' type of checkbox. What do you think -- do you prefer default styling on the figure checkbox or is it okay like this?

**Comment by jjallaire** [comment]
Agree that the checkbox should be similarly themed.

Some more tweaks:

- The "name" text box and Output combo box should be exactly aligned (same
width and horizontal position). This will make the UI look at lot cleaner.

- More uniform spacing between check boxes (I like the amount of space left
above "Use custom figure size")

- Width and height should read e.g. "Width (inches):" (i.e. remove the "in")

- Width and height should be indented to emphasize their containment within
the "Use custom figure size option"

**Comment by kevinushey** [comment]
With better alignment + the added output option to suppress all evaluation:

screen shot 2015-06-19 at 10 54 10 am


screen shot 2015-06-19 at 10 54 25 am

**Comment by kevinushey** [comment]
Improved alignment on buttons + help link:

screen shot 2015-06-19 at 11 01 16 am

**Comment by jjallaire** [comment]
Looking good!!!!

A few small tweaks to language based on the email thread we had with Yihui,
Garrett, and Hadley:

1. Options should read:

(Use Document Default)
Show Output
Show Code and Output
Show Nothing (Run Code)
Show Nothing (Don't Run Code)

2. I think we still need to make the whitespace between the checkboxes
consistent (I think the two "show" options are too close togeter).

3. I'd give the bottom area a bit more vertical air so the controls don't
run right into the link and button.

4. I think we can truncate the option names to "Show warnings" and "Show
messages" (so as not to overplay the use of the word "output"

**Comment by kevinushey** [comment]
Here's how we look now:
screen shot 2015-06-19 at 11 21 31 am

screen shot 2015-06-19 at 11 21 37 am


screen shot 2015-06-19 at 11 21 41 am

I still wanted the spacing for the 'message' and 'warning' checkboxes to be a bit smaller (I wanted those two options to be visually 'grouped together', with the 'figure' checkbox being a slightly bit separate). Any preference? Should I just use consistent spacing between the checkboxes?

**Comment by jjallaire** [comment]
Okay, now that I am seeing it I think we should change the first option to
"Show Output Only" (so it has a width more consistent with the others)

I think introducing grouping with this few options is a distraction so I
think the spacing should be even (the larger spacing being preferred).

**Pull request merged**
