### PR TITLE
Add support for format on save

### PR DESCRIPTION
**Pull request by kevinushey**
### Intent

Addresses https://github.com/rstudio/rstudio/issues/2563.

### Approach

This PR adds support and UI for configuring a code formatter to be run on document save, or when explicitly requested on a code selection via Cmd + Shift + A. Currently, the `styler` package, and an external arbitrary application are supported.

In both cases, we launch a separate process to handle the formatting. When configured to use `styler`, we start an R process that invokes `styler`, rather than invoking it in the main process; otherwise, we invoke the command provided directly, with the file path as an included argument.

### Automated Tests

Basic automation for 'format on save' was added.

### QA Notes

Test via notes in https://github.com/rstudio/rstudio/issues/2563.

### Documentation

Would be worth documenting in the user guide once complete.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
I wonder if, in addition to the user preference, we should also have a source document preference associated with "reformat on save"? This could be added to the editor toolbar:

Screenshot 2024-07-25 at 3 51 48 PM

I can think of a few options:

1. Add a small dropdown menu button next to "Source on Save", and include "Reformat on Save" in that list.
2. Add "Reformat on Save" to the toolbar itself.
3. Create a "gear" icon to encompass both "Source on Save" and "Reformat on Save".

I'm leaning towards (1) or (3), just because there's not much horizontal space available in the toolbar.

**Comment by kevinushey** [comment]
I think we'll also want to consider filters for which files we'll actually run the formatter on; however, I'm not sure what that filter should look like, or how users should register those filters. Do we need to provide UI for that?

**Comment by jthomasmock** [comment]
> I think we'll also want to consider filters for which files we'll actually run the formatter on; however, I'm not sure what that filter should look like, or how users should register those filters. Do we need to provide UI for that?

Yah we have so little space to work with I think that 1. makes most sense and perhaps inspired by Run button, albeit with multi-select like in the gear icon

image

image

**Comment by jthomasmock** [comment]
> I think we'll also want to consider filters for which files we'll actually run the formatter on; however, I'm not sure what that filter should look like, or how users should register those filters. Do we need to provide UI for that?

State of the art is probably Ruff, and there are a ton of example settings/options for includes/excludes:  https://docs.astral.sh/ruff/settings/#include

Ruff extension uses a `.toml` file across projects: 
image

Given this Format on Save is built into RStudio, I don't think we want to automatically go full `.toml` or other separate config file, but we should probably see what the `styler` folks want to do. I see this: https://github.com/r-lib/styler/issues/319 which links to an issue you've recently worked on: https://github.com/rstudio/renv/issues/1865

Perhaps a configuration option in Save (messy mockup below)?

image

**Comment by kevinushey** [comment]
I added a small dropdown next to the "Source on Save" button we show for R documents:

Screenshot 2024-08-02 at 10 26 54 AM

Similarly, for R Markdown / Quarto documents:

Screenshot 2024-08-02 at 10 27 39 AM

**Comment by kevinushey** [comment]
There are still a few TODOs to resolve, but I think this PR is otherwise ready for review.

There are still enhancements that I think we'll want to consider (e.g. restricting "format on save" to specific files in some way) but one could also argue it is `styler`'s responsibility to implement support for this.

**Review by gtritchie — APPROVED** [review]
✅

**Pull request merged**
