### PR TITLE
rework `.rs.flattenFrame()` so that matrix columns are shown

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

deal with #10332

### Approach

Improve `.rs.flattenFrame()` so that matrices are also flattened. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

```r
library(tibble)
set.seed(123)

my_matrix <- matrix(c(1:20, 1:20), ncol = 2)
df_col <- data.frame(x = 1:20, y = 1:20)

# unnamed matrix
tbl <- tibble(x = letters[1:20], y = 1:20, mat_col = my_matrix, df_col = df_col)
View(tbl)
```

should display: 

image

filter and sort should work just fine. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
This takes inspiration from the way tibbles are printed (for the column names). 

``` r
library(tibble)
set.seed(123)

my_matrix <- matrix(rnorm(4), nrow = 2)
df_col <- data.frame(x = 1:2, y = 3:4)

# unnamed matrix
tbl <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl)
#>   x mat_col[, 1]   [, 2] df_col$x $y
#> 1 a      -0.5605 1.55871        1  3
#> 2 b      -0.2302 0.07051        2  4
tbl
#> # A tibble: 2 × 3
#>   x     mat_col[,1]   [,2] df_col$x    $y
#>   <chr>       <dbl>  <dbl>    <int> <int>
#> 1 a          -0.560 1.56          1     3
#> 2 b          -0.230 0.0705        2     4
```

image


```r
# named matrix
colnames(my_matrix) <- c("a", "b")
tbl <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl)
#>   x mat_col[, "a"] [, "b"] df_col$x $y
#> 1 a        -0.5605 1.55871        1  3
#> 2 b        -0.2302 0.07051        2  4
tbl
#> # A tibble: 2 × 3
#>   x     mat_col[,"a"] [,"b"] df_col$x    $y
#>   <chr>         <dbl>  <dbl>    <int> <int>
#> 1 a            -0.560 1.56          1     3
#> 2 b            -0.230 0.0705        2     4
```

image

**Comment by romainfrancois** [comment]
Perhaps this should rather be like this as there is less concern about saving space than in the console: 

image

**Comment by romainfrancois** [comment]
tibble has extra attention to detail: 

```r
tbl
#> # A tibble: 2 × 3
#>   x     mat_col[,"a"] [,"b"] df_col$x    $y
#>   <chr>         <dbl>  <dbl>    <int> <int>
#> 1 a            -0.560 1.56          1     3
#> 2 b            -0.230 0.0705        2     4
```

e.g. how the `.` line up and the column type extra information

**Comment by romainfrancois** [comment]
Also these don't get the correct size initially, but I don't know where in `dtviewer.js` the sizes are calculated: 

image

**Comment by kevinushey** [comment]
> Perhaps this should rather be like this as there is less concern about saving space than in the console:

I agree with that.

> Also these don't get the correct size initially, but I don't know where in dtviewer.js the sizes are calculated:

I'm not positive either. The main thing I notice is that the initial width is "correct" for labels that wouldn't normally be wrapped, e.g.

```
df <- data.frame(
  aaa = 1,
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 2,
  "a a a a a a a a a a" = 3,
  check.names = FALSE
)

View(df)
```

Screen Shot 2022-01-12 at 11 43 28 AM

So I suspect we're letting the browser "guess" the column width, but allowing wrapping (perhaps unexpectedly, for these cases?)

**Comment by kevinushey** [comment]
You could probably cheat by replacing the whitespace with a unicode non-breaking space? E.g.

```
df <- data.frame(
  aaa = 1,
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 2,
  "a a a a a a a a a a" = 3,
  check.names = FALSE
)

names(df)[3] <- gsub(" ", "\u00a0", names(df)[3])
View(df)
```

Screen Shot 2022-01-12 at 11 49 07 AM

**Comment by romainfrancois** [comment]
nbsp seem to work just fine. Thanks @kevinushey. 

``` r
library(tibble)
set.seed(123)

my_matrix <- matrix(rnorm(4), nrow = 2)
df_col <- data.frame(x = 1:2, y = 3:4)

# unnamed matrix
tbl1 <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl1)
#>   x mat_col[, 1] mat_col[, 2] df_col$x df_col$y
#> 1 a      -0.5605      1.55871        1        3
#> 2 b      -0.2302      0.07051        2        4
```

image


```r
# named matrix
colnames(my_matrix) <- c("a", "b")
tbl2 <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl2)
#>   x mat_col[, "a"] mat_col[, "b"] df_col$x df_col$y
#> 1 a        -0.5605        1.55871        1        3
#> 2 b        -0.2302        0.07051        2        4
```

image

**Comment by romainfrancois** [comment]
Actually there is no real need for spaces there: 

``` r
library(tibble)
set.seed(123)

my_matrix <- matrix(rnorm(4), nrow = 2)
df_col <- data.frame(x = 1:2, y = 3:4)

# unnamed matrix
tbl1 <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl1)
#>   x mat_col[,1] mat_col[,2] df_col$x df_col$y
#> 1 a     -0.5605     1.55871        1        3
#> 2 b     -0.2302     0.07051        2        4
```

image


```r
# named matrix
colnames(my_matrix) <- c("a", "b")
tbl2 <- tibble(x = letters[1:2], mat_col = my_matrix, df_col = df_col)
.rs.flattenFrame(tbl2)
#>   x mat_col[,"a"] mat_col[,"b"] df_col$x df_col$y
#> 1 a       -0.5605       1.55871        1        3
#> 2 b       -0.2302       0.07051        2        4
```

image

**Comment by kevinushey** [comment]
Great!

One other thing to double check: does sorting and filtering still work as expected with these pseudo-columns?

**Comment by romainfrancois** [comment]
Sorting and global filtering seems to work fine. It will be easier to check with this `tbl`: 

```r
library(tibble)
set.seed(123)

my_matrix <- matrix(c(1:20, 1:20), ncol = 2)
df_col <- data.frame(x = 1:20, y = 1:20)

# unnamed matrix
tbl <- tibble(x = letters[1:20], y = 1:20, mat_col = my_matrix, df_col = df_col)
View(tbl)
```

**Review by kevinushey — APPROVED** [review]

**Pull request merged**
