### PR TITLE
exclude directory `cloud.noindex` from search

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

Adresses #10529

### Approach

Add `--exclude-dir=cloud.noindex` to the grep command. 

This is a bit brute force, but we don't think we would ever want to search in this directory. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Alternatively we could have some ui to pilot `--exclude-dir`. cc @DavisVaughan

**Comment by romainfrancois** [comment]
Also, I'm not sure `--exclude-dir=` is universally available. [Apparently](https://stackoverflow.com/questions/6565471/how-can-i-exclude-directories-from-grep-r) it's available from gnu grep 2.5.2

**Comment by jgutman** [comment]
> Also, I'm not sure `--exclude-dir=` is universally available. [Apparently](https://stackoverflow.com/questions/6565471/how-can-i-exclude-directories-from-grep-r) it's available from gnu grep 2.5.2

On Windows, we now use gnu grep 3.0, but we already have an argument for excluding directories from search: grepOptions.excludeArgs() -- maybe you should add it to there instead?

**Review by jgutman — APPROVED** [review]

**Comment by romainfrancois** [comment]
Thanks @jgutman. I'll merge this one here and open an issue for discussing a more general ui for `-exclude-dir=`

**Pull request merged**
