### PR TITLE
Always use advisory locks for notebook path map on Windows

### PR DESCRIPTION
**Pull request by jmcphers**
This change resolves a problem that breaks the notebook path/ID cache on Windows. We use a lockfile-based mutex to ensure that two RStudio sessions do not both try to update the cache at the same time. The problem is that on Windows, link-based file locks aren't supported (even though they're the default):

https://github.com/rstudio/rstudio/blob/5aebf29369ba3bc6c1e031fb4a1a569ad33db9a4/src/cpp/core/file_lock/LinkBasedFileLock.cpp#L246

...so we never acquire the lock and never update the cache. For the most part there's enough resiliency in the system that it works anyway, but without the mappings notebooks with identical filenames (but in different directories) can experience crosstalk.

@kevinushey Would you be willing to review this? I was tempted to just make the default lock type `LOCKTYPE_ADVISORY` on Windows everywhere, but that's obviously a larger change, and I suspect there's some reason this isn't already the case.

### CODE REVIEW

**Comment by jjallaire** [comment]
As far as I can recall the link based file locks were put in for RStudio Server so it should in fact be safe to use advisory locks on Windows. @kevinushey will know for sure.

**Comment by kevinushey** [comment]
We implemented link-based file locks specifically for older NFS systems, where advisory file locks could be unreliable (IIRC we wanted a bit of extra resiliency against temporary mounting / unmounting of a NFS).

We might want to just change the default here:

https://github.com/rstudio/rstudio/blob/5aebf29369ba3bc6c1e031fb4a1a569ad33db9a4/src/cpp/core/file_lock/FileLock.cpp#L127

That is, when on Windows, default to advisory locks rather than link-based locks.

**Comment by jmcphers** [comment]
@kevinushey @jjallaire I want to take this change for 1.0 because while no users have reported problems, it's a bit of a time bomb (no one's going to hit this with their first couple of notebooks but eventually they're going to get bitten). How would you feel about taking this change for 1.0, and the change Kevin describes for 1.0-patch?

OTOH, if we feel very confident in the change Kevin describes, we could just take that one for 1.0.

**Comment by kevinushey** [comment]
I think this is safe for v1.0 -- note that we should normally be using advisory file locks by default in Desktop mode (I think we expicitly choose the lock type based on server vs. desktop in other places they're constructed), and we've been using advisory file locks by default throughout all past releases of RStudio, so I'm fairly confident this change is safe.

**Comment by jjallaire** [comment]
+1, let's take it all for v1.0

**Comment by jmcphers** [comment]
Okay, I'll open a new PR with that change. Appreciate the insight!

**Pull request closed without merging**
