### PR TITLE
Includes a chunk caching toggle for RMarkdown chunks

### LINKED ISSUE #4704: Add caching as a selectable chunk option in Rmarkdown
Caching is a relatively frequently used feature of RMarkdown, especially where one is iteratively developing presentations or other work products that involve complicated calculations or external API calls. It would be very useful and make life easier for many of us if instead of having to manually add `cache=T` or a cache level to the chunk specification, this could be accomplished from the handy little chunk options panel. A potential implementation could look like this:

Screenshot 2019-04-25 at 12 24 57

Since this is basically just replicating the other chunk option features, I am happy to give implementing it a try.

### PR DESCRIPTION
**Pull request by chrisvoncsefalvay**
When selected, this adds `cache = TRUE` (equivalent to `cache = 3`) to the current chunk.

Closes #4704.

### CODE REVIEW

**Comment by jmcphers** [comment]
Thank you for the contribution!

Did this change compile successfully? It looks like it's adding a new member variable `cacheChunkCb_` that isn't declared. (If you don't want to set up your system for compilation, run the `docker-compile.sh` script to perform a compile inside a local Docker container for testing.)

**Comment by chrisvoncsefalvay** [comment]
@jmcphers As far as I could tell it worked in Vagrant, but I'll do a dockerised compile tomorrow and make sure it's all sound. Thanks!

**Comment by chrisvoncsefalvay** [comment]
As it stands, this compiles for me on docker.

**Comment by jmcphers** [comment]
Okay, it all looks sound now. Very much appreciate the addition!

**Pull request merged**
