### PR TITLE
pass along HTTPUserAgent when installing dependencies

### LINKED ISSUE #5369: RStudio HTTP user agent not used in the Install Required Packages prompt
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.424 (also in 1.2-patch)
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem
1. Trigger the "Install Required Packages" prompt by creating a new R Markdown document (File -> New File -> R Markdown) without having some of `rmarkdown` or its dependencies installed.

image

2. Click yes to install package dependencies. When installing packages, the default user agent will always be the R default (e.g. `libcurl/7.47.0`), rather than the RStudio default (e.g. `RStudio Desktop (1.3.424); R (3.6.1 x86_64-pc-linux-gnu x86_64 linux-gnu)`) or a custom `HTTPUserAgent` option.
This means that R 3.6 users won't be able to install Linux binary packages from RStudio Package Manager through this prompt (see #4826 for the original issue).

image

Note: you can also reproduce this by creating a new Shiny app or Plumber API, publishing to Connect, etc., without having all the required package dependencies installed. R Markdown was just one example.

### Describe the problem in detail
This was originally discovered in RStudio Cloud here: https://community.rstudio.com/t/rmarkdown-package-install-dependencies-not-detected-via-file-popup/37972

According to @jmcphers, the RStudio HTTP user agent is only set in the main R session, not the slave R sessions that run those package installations. Also, those slave R sessions are run with `--vanilla`, so any `HTTPUserAgent` setting changes in an Rprofile.site or .Rprofile are ignored.

The original issue about user agents: #4826 

### Describe the behavior you expected

When installing package dependencies through the IDE prompt, we should be able to install binary packages from RSPM and Cloud in R 3.6. I was expecting that either the default RStudio user agent or a custom `HTTPUserAgent` setting would be used.

(cc @stevenolen)

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #5369.

### CODE REVIEW

**Comment by jspiewak** [comment]
Could this be back-ported to 1.2 as well please?

**Comment by kevinushey** [comment]
cc @jmcphers -- I think this would be safe to backport, but it would be coming in pretty hot. What do you think?

**Comment by jmcphers** [comment]
I will backport it to 1.2; we can get it on the next bus if it misses Elderflower (which is in final certification)

**Comment by jmcphers** [comment]
Backported in https://github.com/rstudio/rstudio/commit/7074cb12f7c11399544eca0bdbbd005046b41b97

**Pull request merged**
