### PR TITLE
Fix build issues with clang6.

### PR DESCRIPTION
**Pull request by yurivict**
Submitted by Thomas Mueller <thmu7@freenet.de> in the FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228289

### CODE REVIEW

**Comment by yurivict** [comment]
Please test it with clang5 and clang6 before merging.
This patch came from one user. I tried it, and couldn't succeed to build with clang5, it only worked with clang6.

It is possibly related to https://github.com/rstudio/rstudio/issues/2289
This patch here fixes 2289 but breaks clang5.

Somebody innately familiar with the rstudio code should test and fix both issues.

**Comment by jmcphers** [comment]
This change breaks most of our builds, with the same error named in the FreeBSD bug report (re: clang5 compilation).

**Comment by kevinushey** [comment]
Those attempts to assign `NULL` / `nullptr` should likely just be calls to the `.clear()` method.

**Comment by jmcphers** [comment]
Superceded by https://github.com/rstudio/rstudio/pull/2807.

**Pull request closed without merging**
