### PR TITLE
ace-based completion and diagnostics for other languages

### PR DESCRIPTION
**Pull request by jjallaire**

### CODE REVIEW

**Comment by jjallaire** [comment]
@kevinushey Take a look and let me know if this looks alright (I used the second method of loading ext-language_tools.js that you recommended and things seemed to work fine).

The reason I only added completion for web types is that some modes I tried have really wonky behavior (inserting extra characters, etc.). This might have something to do with how they tokenize keywords, I'm not sure. Anyway, the web file types will be the most commonly used/requested and I'd rather not get into a constant discussion about which languages should have this and which shouldn't -- web file types are nice clean line to draw since they are used with R Markdown, Shiny, htmlwidgets, etc.

**Comment by jjallaire** [comment]
Also added support for ace diagnostics.

The overall user-experience for these features is significantly more "chatty" than the R and C/C++ modes. This is partly becomes the "live" completer kicks in after 1 character (with no delay semantics) and partly because diagnostics are shown pretty aggressively even while you are typing a statement. As a result it may make sense for us to also:

1. Modify Ace to apply the R/C++ completion throttling behavior.

2. Throttle diagnostics the same we are planning to for R and C++ (perhaps this will come for free from the work on the linter branch).

**Comment by kevinushey** [comment]
Quick glance, everything looks good to me -- I'll take a deeper look start of next week re: throttling and diagnostics.

Would it make sense to enable completions for SQL as well (maybe not since we get into the trap of supporting all SQL flavors, eg SQLite vs MySQL etc)

I can look into whether it's simple to remove the chatiness, and fix the bugs with extra characters inserted on completion.

**Comment by jjallaire** [comment]
I'd like to enable completions for everything by default, but I think there are 3 things we need to do first:

1. Figure out why a couple of our custom modes have bizzaro behavior with extra characters being inserted. The ones I saw this with were stan and mermaid (both of which we wrote rather than Cloud9 so there could be something we're not doing)

2. Implement our completion throttling preferences for Ace (# of characters and millisecond delay)

3. Tweak the Ace completion popup CSS to look a bit more like ours

For diagnostics I also think we should enable all the ace diagnostics by default but have them be subject to our logic for making diagnostics less chatty (hopefully whatever you do for R and C++ mode will just automatically flow to the other modes).

**Comment by kevinushey** [comment]
For the 'bizarro behaviour', it looks like the Ace language tools completion expects the highlight rules constructor to be a part of the mode, with e.g. `this.HighlightRules = StanHighlightRules` for Stan (Ace attempts to automatically generate completions from the highlight rules). I'll run through our languages we want to activate completions for and add this in.

**Comment by kevinushey** [comment]
The issue with ace completions in stan + mermaid should be resolved now -- basically, any mode for which we want to enable autocompletions for needs to cache the highlight rules locally (as `$highlightRules`), as the autocompletion system attempts to pull out keywords from the highlight rules.

I'm now working on the completion throttling for Ace modes (have time based throttling ready, but not yet character-based). I also made a similar API request upstream at Ace (to see if they'd be interested in implementing completion throttling there as well)

**Comment by kevinushey** [comment]
Okay, the Ace completion modes are now character + timer aware.

I noticed that the completion preferences don't get synced when (only) the completion character limit or the delay are changed. @jjallaire, what's the best way to coordinate that? (sync the completion options if any of those change)

**Pull request merged**
