### PR TITLE
ansi escapes in custom source markers

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #12425 

### Approach

Avoid to create an `AceAnnotation` with both `.text` and `.html` because otherwise `.text` is prefered as per this code in ace: 

```js
var annoText = annotation.text;
annoText = annoText ? lang.escapeHTML(annoText) : annotation.html || "";
```

_Alternatively, the ace code could use `annotation.html ?` instead of `annotation.text ?` so that the html version would have priority._ 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

Save this file as `test.R` in the current working directory: 

```r
tmpfile <- "test.R"

foo <- cli::bg_br_white(cli::col_red("I am red!"))
bar <- cli::bg_br_yellow(cli::col_cyan("I am cyan!"))

markers <- list(
  list(
    type = "error",
    file = tmpfile,
    line = 6,
    column = 1,
    message = structure("<i>I am Groot</i>", class = "html")
  ),
  list(
    type = "info", 
    file = tmpfile,
    line = 12,
    column = 1,
    message = bar))

.rs.api.sourceMarkers("Test Name", markers)
```

and then run it. 

Expected: 

Markers tab: 

image

Annotations: 

image

image

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Related to https://github.com/rstudio/rstudio/pull/12048, an orthogonal follow up could be to support annotations to carry an html widget. This would be safer as they are wrapped around an `<iframe>`

**Comment by romainfrancois** [comment]
TODO: this breaks the source markers: 

https://user-images.githubusercontent.com/2625526/207598348-021d2feb-3d10-4cf3-aeeb-228ec07cb759.mov

**Review by timtmok — APPROVED** [review]
Nice!

**Comment by romainfrancois** [comment]
Following up on https://github.com/rstudio/rstudio/pull/10278 I think we have to give up on the `structure(, class = "html")` because e.g. we could have `message = structure('<i onclick = "alert(42)">I am Groot</i>', class = "html")` which does `alert()` : 

image

**Comment by romainfrancois** [comment]
Disabled it so that custom source markers can't emit already prepared html content: 

```r
tmpfile <- "test.R"

foo <- cli::bg_br_white(cli::col_red("I am red!"))
bar <- cli::bg_br_yellow(cli::col_cyan("I am cyan!"))

markers <- list(
  list(
    type = "error",
    file = tmpfile,
    line = 6,
    column = 1,
    message = structure('<i onclick = "alert(42)">I am Groot</i>', class = "html")
  ),
  list(
    type = "info", 
    file = tmpfile,
    line = 12,
    column = 1,
    message = bar))

.rs.api.sourceMarkers("Test Name", markers)
```

gives: 

image

image

markers that we make internally may be html, but I don't think this is used at the moment. 

We can consider a followup where we would allow creating markers/annotations that would consist of some html widget, that we could embed as an `<iframe>` so be less risky.

**Review by timtmok — APPROVED** [review]

**Pull request merged**
