### PR TITLE
add Mac OSX launchd plist and admin script

### PR DESCRIPTION
**Pull request by randy3k**
The admin script is missing for mac, this PR adds support for Mac OX.

### CODE REVIEW

**Comment by jjallaire** [comment]
Nice! We don't technically support RStudio Server on OS X but as you know it can be made to work. Could you give us a contributor agreement: https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

**Comment by randy3k** [comment]
I have signed it #527, I have to sign again?

**Comment by randy3k** [comment]
I found no problem in installing RStudio server on a Mac (except the missing admin script, so I made this PR). Additionally, RStudio Server (Desktop) and Boost could be linked against `libc++` with an appreciate patch.
https://support.rstudio.com/hc/en-us/community/posts/211702327-Build-RStudio-against-libc-

**Comment by jjallaire** [comment]
No, that will be fine.

J.J.

**Pull request merged**
