### PR TITLE
Enable connections pane and list supported package connections

### PR DESCRIPTION
**Pull request by javierluraschi**
This change enables the connection panel (one line change), but also proposes to prepopulate the "New Connection" wizard with packages that support connections as the starting experience. Once selected, the wizard will prompt users to install the package. Currently, only `odbc` and `sparklyr` support the connections contract but we can grow this list in the near future as more package adopt this interface.

Notice that currently, the packages fail to install since the required versions are not available in CRAN, daily-build users will have to notice that the version is not available in CRAN and use `devtools` instead.

We will have to update CRAN for `odbc` and `sparklyr` before the IDE releases. For `sparklyr`, we need to update the package regardless of this change since the IDE is not backwards compatible with the previous contract.

screen shot 2017-04-04 at 4 32 02 pm

screen shot 2017-04-04 at 4 11 53 pm

### CODE REVIEW

**Comment by jjallaire** [comment]
I'd be in favor of waiting to enable this by default until we have the requisite versions of sparklyr and obbc on CRAN.

**Comment by jmcphers** [comment]
That makes sense. Perhaps we could use a UI pref or just test for the odbc package; the motivation for this change is that after the odbc package began supporting the pane, it was necessary to install the sparklyr package to test the odbc package's integration. 

Also, @javierluraschi in my view the New Connection list should just be a flat list of connections that aggregates all of the connections provided by all of the installed packages (i.e. instead of ODBC > Mongo, just list Mongo at the top level). That will simplify the UX, and in practice I think the total number of connections available to most users will be small enough to fit on one dialog. Let me know what you think.

**Comment by javierluraschi** [comment]
@jmcphers that's how it works, all connections are top level. However, I was planning to send a PR to the ODBC package to support a connection `DCF` file to allow users to choose their own `ODBC` connection string. So `ODBC` here means, any `ODBC` connection (say using a `DNS`), if they install additional drivers, they will appear correctly on the top level. 

I'll test for the ODBC package instead of making this fully available.

**Comment by javierluraschi** [comment]
Merging this one. I can follow up with feedback afterward if needed.

**Pull request merged**
