### PR TITLE
don't trim trailing whitespace on save for Python scripts

### LINKED ISSUE #4215: Error in python scripts with non indented blank lines
When running python scripts in RStudio, non indented blank lines inside functions are interpreted as end of the function. Therefore giving error.
Same (non-indented) scrypt works when running `python script.py` in bash.

Example (with '.' = 'blank space'):
Not works
`def ff(n):`
`..b = 2 `
` `
`..n*b`
Works
`def ff(n):`
`..b = 2 `
`..`
`..n*b`
Works:
`def ff(n):`
`..b = 2 `
`..n*b`

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2
    OS Version      : windows
    R Version       : 3.3

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #4215.

### CODE REVIEW

**Comment by Iuiu1234** [comment]
There is any daily build which the feature is available?

**Comment by jmcphers** [comment]
Yes, this is available as part of our preview release:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by Iuiu1234** [comment]
When saving py file with white spaces, nothing changes.
How shall I activate this feature? 

Using RStudio-1.2.1322. 2019-03-08 daily build on windows

**Comment by jmcphers** [comment]
> When saving py file with white spaces, nothing changes.

That's the point of this change, I think (see #4215).

**Comment by Iuiu1234** [comment]
¿?
#4215 is to be able to run py file
`def ff(n):`
`..b = 2 `
` `
`..n*b`
``
`ff(34)`
line by line. Where  line 3 is a non indented blank line.
If we don't change py file at saving, neither runing the hole `ff` function as a block.
How this pull fix the issue?

**Comment by Iuiu1234** [comment]
any update?

thx

**Comment by kevinushey** [comment]
Sorry, no update. Un-indented holes within function definitions are not handled yet.

**Pull request merged**
