### PR TITLE
format date as yyyy-mm-dd in new R markdown ui

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

adresses #10152

### Approach

Using `new Date().toISOString().replace(/T.*$/, "")`

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Not sure why adding the date is conditioned on whether there is an author: 

```js
public final void applyCreateOptions(String author, String title, 
                                        String format, boolean isShiny)
   {
      setTitle(title);
      if (author.length() > 0)
      {
         setAuthor(author);
         addDate();
      }
      if (isShiny)
      {
         setRuntime(SHINY_RUNTIME);
      }
      if (format != null)
      {
         setOutputOption(format, RmdFrontMatterOutputOptions.create());
      }
   }
```

**Comment by romainfrancois** [comment]
Alternatively, maybe a `Date: ` field can be added to the window, under `Author` and populated with what we get automatically ?

image

**Review by kevinushey — APPROVED** [review]
LGTM!

**Comment by kevinushey** [comment]
> Not sure why adding the date is conditioned on whether there is an author

I have a vague recollection that there was some `rmarkdown` behavior that was keyed off of this ... but even if that was the case, I'm not sure if that's true anymore.

For the `Date` field, I think it's somewhat common practice to use something like:

```
Date: `r Sys.Date()`
```

so that the "current" date is used when rendering a document. At least, I see that somewhat commonly for vignettes:

https://github.com/rstudio/rmarkdown/blob/745c1477d02708938febb7065b85b552c7dc420f/inst/rmarkdown/templates/html_vignette/skeleton/skeleton.Rmd#L4

I wonder if using that for the Date field is a sensible default?

**Pull request merged**
