### PR TITLE
avoid invalid with/height redirects & increase maximum plot size

### LINKED ISSUE #4968: "invalid width" in rstudio-server zoomed plot
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.463
    OS Version      : Ubuntu 16.04.5 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

Zoom plot on `sp::SpatialPolygons`

### Describe the problem in detail

Apparently a long-standing issue, as seen here from 5 years ago:

https://support.rstudio.com/hc/en-us/community/posts/200640338-Zoom-of-graphics-window-doesn-t-work-

I plot some polygons:

Screenshot 2019-06-18 at 7 30 38 PM

And when I click Zoom, it crashes with the error "Invalid Width"

Screenshot 2019-06-18 at 7 30 47 PM

Is there any way around this? It seems to be related to monitor resolution...

### PR DESCRIPTION
**Pull request by jan-glx**
fixes #4968 for a few years

### CODE REVIEW

**Comment by jan-glx** [comment]
Wow. That was fast. I should say that I did not actually test this. (Did expect some CI system to build it for me 😇). When will it be on https://dailies.rstudio.com/ or is there another place to get builds w/o going through the trouble myself?

**Comment by jmcphers** [comment]
I tested this earlier this morning and found that the commas cause the querystring to stop concatenating after adding the width, so fixed here:

https://github.com/rstudio/rstudio/commit/b47e8b05046573274bf448e51f4669b24f36ff87

After that change this patch tested fine for me.  1.3.665 should be available for you to try later today.

**Comment by jan-glx** [comment]
Damn, sorry for the extra work! @self: No more blind coding!

**Comment by jan-glx** [comment]
I tested this in RStudio-1.3.668 and it works :) no more `invalid width error` :)

**Comment by jmcphers** [comment]
Glad to hear it!

**Pull request merged**
