### PR TITLE
enabe begin + end fold markers everywhere

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: not quite ready for merge as there's one outstanding issue with folding for e.g. the R chunk in a C++ code document.

This PR ensures that begin + end fold tokens are generated within all documents, as in the following screenshots (see both the 'up' and 'down' arrows in the gutter):

screen shot 2015-09-22 at 1 04 13 pm

screen shot 2015-09-22 at 1 04 26 pm

Prior to this, up arrow fold tokens were only drawn for chunks; this PR enables them for closing brackets as well.

We could also consider making this available as a UI pref but I think most users would prefer seeing both up and down fold tokens -- any thoughts?

### CODE REVIEW

**Comment by jjallaire** [comment]
I think we definitely need a UI pref for this as when we originally added folding though the end marker created too much visual business so excluded it.

The question is what the default should be? I'm open to defaulting it on if both @kevinushey and @jmcphers agree that it's better to default to begin/end (you can toggle between begin and begin/end using the ace kitchen sink demo).

**Comment by jmcphers** [comment]
I prefer off as the default -- when not looking directly at the gutter the difference between the arrows is negligible so in this example it's the lines that *aren't* decorated that stand out to me! I very rarely use folding, though, so if this was a change requested by several people that *do* use folding I'm willing to defer to their judgement.

**Comment by jjallaire** [comment]
I think I agree we should leave it off by default.

**Comment by kevinushey** [comment]
I guess I am in the minority here :)

I'll make this a UI pref with the default to off.

**Comment by kevinushey** [comment]
With the UI pref:

screen shot 2015-09-22 at 2 40 32 pm

**Comment by jjallaire** [comment]
Looks good! Is this ready to merge from your standpoint?

**Comment by kevinushey** [comment]
There's one more minor buglet re: code folding of block comments in C / C++ mode (mainly related to the R code chunk) which I think should be fixed before merge -- I'll ping when that's ready.

**Comment by jjallaire** [comment]
We probably also need to subscribe to changes in the UIPref to dynamically update editors. We have a place where we do that for other prefs here: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L5297

**Comment by kevinushey** [comment]
I think this is okay to merge, but I also feel a little bit hesitant about making a change like this so soon before release (a number of changes in block comment folding were necessary). What do you think about waiting until we branch to merge?

**Comment by jjallaire** [comment]
I agree that given where we are in the release we should hold off on merging this.

**Comment by kevinushey** [comment]
Reviewed this and I think it should be good to go now. Reminder to self to update NEWS after merge (avoid potential merge conflicts for now)

**Comment by jjallaire** [comment]
Let's update NEWS with this.

**Pull request merged**
