### PR TITLE
Use relative source file paths from src/cpp in the repo root instead of the absolute path

### LINKED ISSUE #5423: Report relative (not absolute) path to .cpp files (etc.) in error logs
RStudio's error messages currently name the full path to the file that logged the error. As it's resolved at compile time, the path is to a file on the build machine. For example:

> 24 Apr 2019 14:06:37 [rsession-lrevilla] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333

This has been an endless source of confusion for customers. We've fielded a lot of questions about what these paths are, and queries about why they are referring to files that don't exist (_`/var/lib/jenkins` doesn't exist on my machine, where is that file?_) 

We've even had these flagged as security vulnerabilities, since full paths in error messages are sometimes considered to be an inappropriate leak of system information. Of course, they don't leak any information about the system on which RStudio is installed, but the scanning tools don't know that.

It is very useful to us to know where errors originated and where they were logged, but the absolute path is not necessary; all we need to know is the path from the repo root. We propose changing the logger so that it only reports this relative path. For example, the error above would be reported as:

> 24 Apr 2019 14:06:37 [rsession-lrevilla] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1333

### PR DESCRIPTION
**Pull request by kfeinauer**
This change makes it so that file locations reported in an error log only use relative paths from `src/cpp` instead of the actual full file path where the project was built.

Closes #5423.

### CODE REVIEW

**Comment by kevinushey** [comment]
A couple things I saw when running `cmake` with this PR:

1. The `SessionTests.cpp` file gets a duplicated `STRIPPED_FILENAME` (probably ultimately not an issue):

> 199:# Custom defines: session/CMakeFiles/rsession.dir/modules/SessionTests.cpp.o_DEFINES = STRIPPED_FILENAME="src/cpp/session/modules/SessionTests.cpp";STRIPPED_FILENAME="src/cpp/session/modules/SessionTests.cpp"

2. Some desktop files are not stripped correctly:

> 97:# Custom defines: desktop/CMakeFiles/RStudio.dir/moc_DesktopGwtCallback.cpp.o_DEFINES = STRIPPED_FILENAME="src/cpp/desktop//Users/kevinushey/rstudio/src/build-test/desktop/moc_DesktopGwtCallback.cpp"
99:# Custom defines: desktop/CMakeFiles/RStudio.dir/moc_DesktopGwtWindow.cpp.o_DEFINES = STRIPPED_FILENAME="src/cpp/desktop//Users/kevinushey/rstudio/src/build-test/desktop/moc_DesktopGwtWindow.cpp"
101:# Custom defines: desktop/CMakeFiles/RStudio.dir/moc_DesktopInfo.cpp.o_DEFINES = STRIPPED_FILENAME="src/cpp/desktop//Users/kevinushey/rstudio/src/build-test/desktop/moc_DesktopInfo.cpp"
< ... >

I also wonder if quotes should be included in the stripped filename, since the build command looks like:

```
session/CMakeFiles/rsession.dir/prefs/PrefTests.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/rsession.dir/prefs/PrefTests.cpp.s"
	cd /Users/kevinushey/rstudio/src/build-test/session && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) -DSTRIPPED_FILENAME=\"src/cpp/session/prefs/PrefTests.cpp\" $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/kevinushey/rstudio/src/cpp/session/prefs/PrefTests.cpp -o CMakeFiles/rsession.dir/prefs/PrefTests.cpp.s
```

noting, in particular:

```
-DSTRIPPED_FILENAME=\"src/cpp/session/prefs/PrefTests.cpp\"
```

**Comment by jmcphers** [comment]
If it's difficult to get the right filenames into the the error messages, maybe we could just post-process the filename right before it's logged?

**Comment by kevinushey** [comment]
That seems reasonable to me as well -- just chomp out everything before `/src/cpp` at runtime?

**Comment by kfeinauer** [comment]
I think this approach I have here will work, just need to see why the `moc` files are not being generated properly. 

And of course, if we can do this at compile time, we get the added benefit of this being faster at run-time.

**Comment by kfeinauer** [comment]
@kevinushey Updated to fix the `moc` paths. As far as the `-DSTRIPPED_FILENAME` arguments being passed to the compiler, the escaping is correct when sent to CMake (`-DSTRIPPED_FILENAME="src/cpp/..."`) but CMake is changing this when writing the command to the compiler for whatever reason. However, this seems to be working fine and is not causing any trouble (logs show up with the correct modified source file path).

**Pull request merged**
