### PR TITLE
make 'yank' commands rebindable

### PR DESCRIPTION
**Pull request by kevinushey**
This PR is a second attempt at making the 'yank' commands rebindable. It adds a new command handler intended to dispatch events to editor (Ace) instances as appropriate.

This should provide a mechanism for us to implement commands that need to dispatch to the currently focused editor, and will be useful for making other hard-coded commands (e.g. the ` <- ` insertion command) rebindable and accessible to all Ace instances.

### CODE REVIEW

**Comment by kevinushey** [comment]
@jmcphers, if you have time can you review + sanity check?

**Comment by jmcphers** [comment]
Nice!

It looks like we formerly ignored these in Vim/Emacs mode -- is that unnecessary now?

**Comment by kevinushey** [comment]
Good catch -- I'll add that logic back in.

**Comment by jmcphers** [comment]
Looks good now -- feel free to merge (would do it myself but there are conflicts which you're probably best equipped to resolve)

**Pull request merged**
