### PR TITLE
save/load cursor position on restore

### PR DESCRIPTION
**Pull request by kevinushey**
This PR adds the cursor position and top scroll line as part of the document properties, and restores those when a document is opened (effectively, saving + loading the cursor position when closing and opening documents).

### CODE REVIEW

**Comment by kevinushey** [comment]
This initial approach leads me to think that we might instead want to make it possible to submit a document property bag alongside the autosave events that we periodically do, rather than having a separate RPC call just to save these few items.

**Comment by jmcphers** [comment]
re: autosave, I agree that'd be nice, but probably can be done separately (seems like we might need to disambiguate on the call site whether it's a property update which should happen immediately vs. one that can wait some period of time for an opportunistic autosave). 

We already save/restore cursor position when a document is popped out:

https://github.com/rstudio/rstudio/blob/8b2d9f2111e852e84d265c5d8f96bb4f15d0426d/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L1908-L1923

https://github.com/rstudio/rstudio/blob/440b6b3f2f3980e1e159eba983cfd78e6e651c7b/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L867-L890

This position could be different in some circumstances as it's read instantly rather than off a timer, and I don't think we want two different codepaths that restore the cursor position. I suspect that we can just remove most of the two blocks above and use the mechanism you've added.

**Comment by kevinushey** [comment]
Ah, more fundamentally -- the autosaves only occur if the document contents are mutated, whereas we want this to happen even when no document change has occurred. The extra chattiness here is probably fine now (especially since we've disentangled the document properties from the document contents; those now live in separate files)

**Comment by jmcphers** [comment]
Indeed! Thanks for cleaning that code up; this looks great.

**Pull request merged**
