### PR TITLE
use DebouncedCommand for autosave (prevent autosave while typing)

### PR DESCRIPTION
**Pull request by kevinushey**
This PR switches away from using a `TimeBufferedCommand` to a `DebouncedCommand` for autosave. The intention here is to:
1. Avoid creating + running timers so eagerly, and
2. Resolve an issue where autosaves could run while the user was actively typing.

The `TimeBufferedCommand` class actually generates new timers very eagerly -- every time it is `nudge()`d, it generates a new timer -- and we often call this `nudge()` method within event handlers that occur often, e.g. value changed handlers, as in this case.

It also does not debounce as one might expect (although perhaps that was not the intention of the class?) In other words, after nudging a TimeBufferedCommand that is set to run every 2000 milliseconds, it will _definitely_ run after 2000 seconds, even if re-nudged in that time interval. This implies that if a user begins typing, they will get interleaving autosaves every 2 seconds while they type.

This change should also fix a performance issue that can occur when editing near the start of large R Markdown documents. Because these autosaves are running eagerly, and those autosaves can force a rebuild of the scope tree (since they need knowledge of chunks in the document), they can effectively 'freeze' the editor for a short period of time (enough to be perceptible as a 'lagginess' in typing).

We might also want to audit other uses of `TimeBufferedCommand` to see if we really do want the semantics of that class, or if debouncing fits better.

Note that the `DebouncedCommand` class intentionally tries to mimic the interface of the `TimeBufferedCommand` class (for 'passively-triggered' commands), so that it can act as a drop-in replacement when appropriate.

### CODE REVIEW

**Comment by jjallaire** [comment]
Yes, `TimeBufferedCommand` is definitely intended to *always* run within the specified interval (but I agree that we need the `DebouncedCommand` semantics and that some uses of `TimeBufferedCommand` really are looking for the new `DebouncedCommand`.

**Comment by jjallaire** [comment]
I guess the big downside here is that if you are actively typing for a minute or two and then experience a crash you'll lose up to a minute or two of data. It seems unlikely that someone would type continuously for that long and crashes are pretty infrequent so this seems okay to me. Perhaps worth considering whether there would be a negative impact to bringing the schedule time down to 1 second.

**Comment by kevinushey** [comment]
I agree it would be a good idea to take the schedule time down to one second.

**Comment by jmcphers** [comment]
Great, let's take it for the patch release then, but keep a close eye on it. @kevinushey if there isn't already a bug on this, can you create one and then resolve it with some notes for @dfalty to test this?

**Comment by kevinushey** [comment]
Will do!

**Pull request merged**
