### PR TITLE
Use bash for git hook set-up. Change to echo -e.

### PR DESCRIPTION
**Pull request by GCRev**
See: https://github.com/rstudio/rstudio/issues/14207

### Intent

Original script uses `sh`, which has some issues with the way `read` is invoked.

### Approach

Switch to using bash to fix some of the conditionals and usage of `read`.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by sharon-wang** [comment]
Script runs for me on Mac in `zsh`, but I'm getting formatting issues:
image

**Review by sharon-wang — APPROVED** [review]
all good now! LGTM

image

**Review by sharon-wang — COMMENTED** [review]
changes to `run-detect-secrets` work for me on Mac zsh as well.

Ran each of the `run-detect-secrets` commands and they all worked, no weird formatting 👍

**Review by sharon-wang — COMMENTED** [review]
pre-commit hook switch to bash continues to work on Mac zsh 👍 Tested by pulling the changes, running `set-up-git-hooks` and trying to commit with a linting/secret issue.

While you're in here, would you mind switching `git_hooks/hooks/pre-push` to bash as well? There shouldn't be any formatting issues, but we might as well have all these scripts be bash.

**Comment by GCRev** [comment]
@sharon-wang done.

**Review by sharon-wang — COMMENTED** [review]
pre-push works for me too (Mac + zsh) 👍

Tested by changing the main branch in the pre-push script to `main_branch="refs/heads/my-test-branch"`, running `./set-up-git-hooks` and trying to push a change to `my-test-branch`.

**Pull request merged**
