### PR TITLE
re-implement markdown completions with new completion engine

### LINKED ISSUE #3996: Markdown image autocompletion does not trigger
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1170
    OS Version      : MacOS 10.14

### Steps to reproduce the problem

1. Create two PNG files in a directory, `test.png` and `test2.png`
2. Create a new R Markdown document in that same directory
3. Type `foo

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3996.

### CODE REVIEW

**Comment by jmcphers** [comment]
Do we still need this existing Markdown link completion logic?

https://github.com/rstudio/rstudio/blob/20bcc8a2fe08ed2a402cf351f431bcf453fb949e/src/cpp/session/modules/SessionRCompletions.R#L2104-L2136

**Comment by kevinushey** [comment]
I think we can get rid of this now.

**Comment by jmcphers** [comment]
Do you want to remove the dead code in this PR? (Or should we file a followup issue?)

**Comment by kevinushey** [comment]
I've removed the now-unused Markdown link completion code from the R completion manager.

**Pull request merged**
