### PR TITLE
add snowflake server option

### PR DESCRIPTION
**Pull request by skyeturriff**
### Intent

Companion OS commit for rstudio/rstudio-pro#6522

### CODE REVIEW

**Review by GCRev — APPROVED** [review]
I think so

**Comment by zachhannum** [comment]
I think you need to update the function declaration for `addOverlayOptions` in `ServerOptionsOverlay.gen.cpp` as well by running `generate-options.R`

**Review by zachhannum — APPROVED** [review]
Assuming build is happy!

**Comment by skyeturriff** [comment]
That's what I get for being lazy and not building locally first 🙃

**Pull request merged**
