### PR TITLE
Change visual mode key command from ctrl+shift+F12 to ctrl+shift+F4

### PR DESCRIPTION
**Pull request by adamconroy**
### Intent

Old key command had a conflict with nextTab.

Fixes https://github.com/rstudio/rstudio/issues/7717

### QA Notes

Ensure new key command Ctrl+Shift+F8 works correctly.

### CODE REVIEW

**Review by gtritchie — CHANGES_REQUESTED** [review]
This was previously <kbd>Ctrl+Shift+F8</kbd> but got changed to <kbd>Ctrl+Shift+F12</kbd> by @jjallaire in this commit: 320d5cec with comment "fix shortcut conflict".

Please follow up with him to find out what motivated this before putting it back.

Once you do decide on the appropriate shortcut, make sure it is also correct in `src/gwt/www/docs/keyboard.htm` (it was still <kbd>Ctrl+Shift+F8</kbd> which is why I discovered it had been changed relatively recently to <kbd>Ctrl+Shift+F12</kbd>).

**Comment by adamconroy** [comment]
@gtritchie I thought about this a bit more and, especially for quick development if someone likes switching often I really like Ctrl+Shift+V. I see no conflicts here and it's less confusing (to me at least) than all of the overloaded F keys up there, particularly since they're heavily used for debugging.

**Comment by jmcphers** [comment]
We use <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>V</kbd> for Paste with Indent.

https://github.com/rstudio/rstudio/blob/192afaa17c3720ca8d4c7eb65066c2e1eb0b3aab/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#L683-L684

**Review by gtritchie — APPROVED** [review]
LGTM! Thanks for also adding the missing paste-with-indent!

**Pull request merged**
