### PR TITLE
implement 'Ctrl+Click' URL navigation

### PR DESCRIPTION
**Pull request by kevinushey**
This PR implements Ctrl+Click navigation in two contexts:

1. For Markdown-style links, e.g. `[URL](http://www.google.com)`, Ctrl+Clicking on the URL itself will attempt navigation to that path. Both web links and server-located files are allowed.

2. In other contexts, command-clicking on a URL (a string beginning with `http`) will attempt navigation to that URL. Note that this is tricky because of what characters are considered valid for a URL, but we try to catch some common cases where the URL is enclosed in e.g. parentheses or quotes. This means that e.g. Ctrl + Clicking in text in R code like:

```
# Please see (http://www.rstudio.com) for more information.
# Learn about the Joker playing card at [https://en.wikipedia.org/wiki/Joker_(playing_card)].
```

should successfully navigate you to the expected location.

### CODE REVIEW

**Comment by jjallaire** [comment]
2 additional enhancements which I think would really take this feature over the top:

1. Provide special syntax highlighting (e.g. blue link color w/ underline) for hyperlinks (I know we already do this in markdown but I don't think we do for R scripts, I'm also not sure if it's done in 100% of cases for markdown, worth checking).

2. Show a tooltip when the user hovers over the hyperlink indicating they can Ctrl+Click to navigate to it.

**Comment by kevinushey** [comment]
I think there's a few highlight behaviors we could consider here for hyperlinks -- we could:

1. Always underline them (e.g. as we do in Markdown documents now),
2. Only underline them when the user is holding down Ctrl,
3. Only underline them when the user is holding down Ctrl, _and_ mousing over the link.

Any thoughts on which of these is preferable (or something different)? I do feel that the unconditional underline of Markdown links is a bit heavyweight, but that's been the behavior for a while now in the IDE so I think users are okay with it.

**Comment by jjallaire** [comment]
I think always underlining links is fine within comments (that's the
behavior I've seen in other IDEs and it never bothered me because within a
comment it's always technical reference).

Within strings I agree it's a bit too aggressive -- honestly I think we
could do with no special highlighting/underlining at all within strings as
I think this would mostly be an unpleasant distraction (since URLs in
strings are often just links to datasets or REST APIs not something you'd
want to click on).

**Comment by kevinushey** [comment]
Alright, I'll target highlighting of strings within comments -- agree this is a good way to go!

**Comment by JanMarvin** [comment]
While your at this, is it possible to extend this to local paths? For instance in bigger projects I like to include R files like header files. Being able to open them clicking on the path behind `source` would be nice.

**Comment by jjallaire** [comment]
For now we're not going to do links within R string but rather just within
comments. If we do support R strings then I agree it would be nice to
include header files (we could also implement navigation to files
referenced in strings via F2).

**Comment by kevinushey** [comment]
Closing this (obsoleted by aforementioned PR)

**Pull request closed without merging**
