### PR TITLE
WIP: initial rename fromNewSparkConnectionDialog into NewConnectionDialog

### PR DESCRIPTION
**Pull request by javierluraschi**
TODOs:
- [ ] Rename code, resources, labels from Spark to generic connections.
- [ ] Generalize "Create Connection Panel".

### CODE REVIEW

**Comment by javierluraschi** [comment]
@jmcphers do you want to work in a branch or merge changes directly to v1.1 as er make progress?

**Comment by jjallaire** [comment]
I think the PR should be against master (since that is currently the v1.1 line). LGTM!

**Comment by javierluraschi** [comment]
Also, do we want to work in this branch or in master directly? It does seem that there is little risk of regressions (Spark UI aside), so it seems that it would make sense to work in master directly, thoughts?

**Comment by jmcphers** [comment]
Yup, we're now doing 1.1 feature development on master.

**Pull request merged**
