### PR TITLE
remove the `"Run Examples"` link from help pages

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #12170

### Approach

Remove the `Run Examples` link from the rendered help page. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
image

The user can still select the example code and press `[Cmd] + [Enter]`. 

Alternatively, we could have the link call some other javascript function that would call back into the ide to do something, presumably just send code to the console ?

**Comment by romainfrancois** [comment]
Given the problems described in #12170, should this go into Elsbeth ?

**Comment by kevinushey** [comment]
I don't think we should remove the "Run Examples" link whole-sale; it works fine for "regular" help pages like `?rnorm`.

Instead I'd argue that this should either be handled in `shinyjs`, or we should find some way of shimming `interactive()` so that it returns `FALSE` when running examples.

**Comment by kevinushey** [comment]
I filed a bug report with R regarding the changed knitr options + loading of `knitr`: https://bugs.r-project.org/show_bug.cgi?id=18420

> Code is formatted differently, through knitr::knit() You do get graphics and all, but you lose the rest of the documentation. If you want it back you have to back.

That seems okay to me though? Your proposal is obviously better, but I still think the current implementation is good enough; at least, it seems better than nothing.

> In https://github.com/rstudio/rstudio/issues/12170, it's not just a shinyjs thing, but is also an issue for (non shiny) html widgets.

Do you think there's a way forward where we somehow disallow running of Shiny applications here? Presumedly we could hook into this somewhere in SessionHelp.cpp. If we wanted to, we could even hook up our own processing of the `Example` endpoint and use our own rendering routines (e.g. render out-of-process using `rmarkdown` and then open the rendered HTML document in a separate window)

**Comment by kevinushey** [comment]
Either way, I'm still leaning towards not taking the PR in its current form and instead considering alternatives or workarounds; given that this is already targeted for Cherry Blossom I think we can take a bit of time to get it right?

**Comment by romainfrancois** [comment]
I'll close this now, and open another PR later.

**Pull request closed without merging**
