### PR TITLE
improve semi-colon insertion rules

### PR DESCRIPTION
**Pull request by kevinushey**
This improves upon the old semi-colon insertion rules by using the tokenizer + token cursor rules for C++ mode. The rewritten heuristics are far more readable and easier to reason about, and should lead to fewer 'false positives' wherein we insert undesired semi-colons.

### CODE REVIEW

**Comment by jjallaire** [comment]
This looks fine. Any hesitation about merging it right before you leave (as users won't start running this code until next week). My bias would be to wait.

**Comment by kevinushey** [comment]
My bias is to wait as well -- although we are reasonably confident that, with the new TokenCursor on the JavaScript side there should be no more hangs caused by this kind of code, the 'benefit' to 'regression damage * regression probability' ratio makes me err on the side of caution as well.

**Comment by jjallaire** [comment]
Okay, let's hold off on this one until you are back.

**Comment by kevinushey** [comment]
We can merge this now, I think.

**Pull request merged**
