### PR TITLE
argument completion of R method when pipe

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #11627

### Approach

special case based on argument `chainObjectName`

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
I need to study some more what happens here, and if we ever get there: 

https://github.com/rstudio/rstudio/blob/710e8ec5601997f8e10bcc57126c5fb0b090ebf2/src/cpp/session/modules/SessionRCompletions.R#L2115-L2145

But what this pr does is inject the "chain object name" e.g. `mtcars` into the `functionCallString`, so that `.rs.getRCompletions()` can take advantage of it. 

image

BTW, should column names (mpg, cyl, etc ...) look a bit different in the completion popup besides not having the `=` ? Maybe a different icon, or font weight ?

**Comment by romainfrancois** [comment]
Trying out a different style when the source starts with "[" : 

image

But again I need to study some more to make sure "the source starting with a [" is the right test for things like this.

**Comment by romainfrancois** [comment]
Might also be useful to inform of the origin of these matches: 

image

**Comment by ntluong95** [comment]
it looks nice @romainfrancois. Why does the argument "data" have different icon color?

**Comment by kevinushey** [comment]
It'd also be nice if the column names were displayed first (rather than last) in the completion list. I also like the idea of including the origin of the matches.

**Comment by kevinushey** [comment]
Maybe this should happen in `.rs.sortCompletions()`?

https://github.com/rstudio/rstudio/blob/aa90ba6df9e8a8647c8ca007ba59447b6401615e/src/cpp/session/modules/SessionRCompletions.R#L1214-L1236

It would also need to handle the case where "token" is empty.

https://github.com/rstudio/rstudio/blob/aa90ba6df9e8a8647c8ca007ba59447b6401615e/src/cpp/session/modules/SessionRCompletions.R#L2571-L2572

**Comment by romainfrancois** [comment]
Currently at: 

image

I have not figured out yet how to sort the columns before the arguments.

**Comment by kevinushey** [comment]
Looks great so far!

> I have not figured out yet how to sort the columns before the arguments.

You might also need to look around here:

https://github.com/rstudio/rstudio/blob/79f339a38c19b1324adb035504b05670cc0d61b7/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java#L151-L217

(and perhaps other routines in that file)

For some feedback on the UI:

- For column name completions, can we also try a treatment where we use the "regular" data.frame icon, but with one column of the table shaded? (Just because I think a full-width icon may fit better; the single-column treatment feels too narrow)
- For the table name, I think I prefer the original treatment with the table name as `[mtcars]`. Do you have a strong opinion?

**Pull request merged**
