### PR TITLE
dial down restrictions in `ide:run:` links

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

follow up for #11273

### Approach

Dial down restrictions on `ide:run:`

options: 
 - code not of of form `<pkg>::<fun>(<args>)`, or `<args>` has a `;` : not allowed
 - `<pkg>` not loaded or on the allow list: only get copied, not executed
 - `<args>` has embedded function calls: also only copied, not executed
 - If `<pkg>` is loaded or in the allow list *and*. there are no embedded function calls: safe to execute

For examples: 

```r
# safe to execute
cli::style_hyperlink("show traceback", "ide:run:rlang::last_error()")

# copied
cli::style_hyperlink("show session info", "ide:run:sessioninfo::session_info()")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(a = rm(list = ls()))")

# denied
cli::style_hyperlink("show traceback ...", "ide:run:rm(list = ls())") # because no <pkg>
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(); rm(list = ls())") # because the ";"
```

I believe this would allow some variation of the examples here https://github.com/rstudio/rstudio/issues/11273#issuecomment-1154249848 to be usable. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Because timing is sensitive we can decide to stick to the current restrictions, but they might deny code that could be useful, e.g. https://github.com/rstudio/rstudio/issues/11273#issuecomment-1154249848 and allow code that would be potentially dangerous, e.g. under the current rules `base::source(<some url>)` would get executed directly.

**Comment by romainfrancois** [comment]
Was discussed in the stand up meeting today, and at that point (so close to SW release) we'll stick to the restrictions we have in place. 

It's not perfect as we have both false positives and false negatives: 
 - `base::source(<url>)` is allowed and automatic even though it's risky
 - `setwd(rstudioapi::getActiveProject())` is denied although it could be useful, that's a bit frustrating. 

But in the grand calculus of the multiverse what we have now (without this pr) is a pretty decent start for the feature. cc @Hadley @jennybc @mikebessuille 

Hopefully we can improve on that in the next release.

**Comment by kevinushey** [comment]
> under the current rules base::source(<some url>) would get executed directly.

Is it worth disallowing `base::source()` (and `base::sys.source()`, I guess ... anything else?) specifically just to avoid this issue?

I sort of wonder if we should just disallow `base` for now since that would also open the door to running `system()` and `system2()` with some arbitrary command, which could be considered unsafe as well. Presumedly, `base::system("rm -rf /")` would be accepted as "safe" with the current implementation as well.

Or, do we think there's any path forward where we can decide whether the hyperlink was generated in a "safe" context; that is, the hyperlink was created by a trusted R package as opposed to arbitrary user code that was reading a file?

**Comment by hadley** [comment]
I think the heuristic to only allow code from packages that user has loaded is solid; the problem is here that base is always loaded. So I think think it'd be fine to disallow any function from base, stats, utils, etc. That would be a very easy restriction for folks to work around if needed.

**Comment by mikebessuille** [comment]
I also think that we are better off being more restrictive now, and potentially loosening those restrictions when we have more time to think about iterating on this solution.  It's always harder to add restrictions later because people start relying on functionality.

**Comment by romainfrancois** [comment]
> Or, do we think there's any path forward where we can decide whether the hyperlink was generated in a "safe" context; that is, the hyperlink was created by a trusted R package as opposed to arbitrary user code that was reading a file?

`cli::style_hyperlink()` could leave some watermark in the params, based maybe on the `topenv()` and the `Sys.getenv("RSTUDIO_SESSION_PID")` hashed in some way, so that we'd know some context of how the link was created. 

```
> str(cli::style_hyperlink("text", "url", params = c(pid = Sys.getenv("RSTUDIO_SESSION_PID"), topenv = environmentName(topenv()))))
 'cli_ansi_string' chr "\033]8;pid=31271:topenv=R_GlobalEnv;url\atext\033]8;;\a"
```

Then we'd have some confidence that the url was generated by `cli::style_hyperlink()` in this session, called inside a package we can decide to trust. Perhaps `pid` and `topenv` could be encrypted in some way ?

**Comment by romainfrancois** [comment]
Closing this for now, I'll open another issue to reconsider in EG.

**Pull request closed without merging**
