### PR TITLE
use `--always-make` in addition to `--dry-run`

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

Another followup on #6384 

### Approach

`--dry-run` on the same directory, using `--output=<non existing so>` and `--always-make`

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
cc @DavisVaughan @kevinushey you might have a better idea to leverage `--always-make` in `tools:::.shlib_internal()`: 

https://github.com/r-devel/r-svn/blob/664e21e375936886ec76eb815a2ad94fa64162a8/src/library/tools/R/install.R#L2390

**Comment by romainfrancois** [comment]
It would be nice if we could add things in 

```r
cmd <- paste(MAKE, <<HERE>>, p1(paste("-f", shQuote(makefiles))), p1(makeargs),
                 p1(makeobjs))
```

but that would not help with previous versions of R. Maybe we can do some refactoring of the parts we need from `.shlib_internal()` into an `.rs.*` function and then just call that.

**Comment by kevinushey** [comment]
Here's a really gross hack. R just passes the output from `--output=` as-is to the `make` invocation, so...

```
kevin@MBP-P2MQ:~/r/pkg/ps/src [main]
$ R CMD SHLIB --dry-run px.c
make cmd is
  make -f 'Makevars' -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' -f '/Users/kevin/.R/Makevars' SHLIB='px.so'

make would use
make: Nothing to be done for `all'.
kevin@MBP-P2MQ:~/r/pkg/ps/src [main]
$ R CMD SHLIB --dry-run px.c --output="--always-make"
make cmd is
  make -f 'Makevars' -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' -f '/Users/kevin/.R/Makevars' SHLIB='--always-make'

make would use
if test  "zinit.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o" != "z"; then \
          echo clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o --always-make init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
          clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o --always-make init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
        fi

```

**Comment by kevinushey** [comment]
Maybe one option is to specify an output that doesn't exist? For example:

```
kevin@MBP-P2MQ:~/r/pkg/ps/src [main]
$ R CMD SHLIB --dry-run --output=dummy.so px.c
make cmd is
  make -f 'Makevars' -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' -f '/Users/kevin/.R/Makevars' SHLIB='dummy.so'

make would use
if test  "zinit.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o" != "z"; then \
          echo clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o dummy.so init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
          clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o dummy.so init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
        fi
kevin@MBP-P2MQ:~/r/pkg/ps/src [main]
$ R CMD SHLIB px.c
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -L/opt/homebrew/lib -o px.so init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
kevin@MBP-P2MQ:~/r/pkg/ps/src [main]
$ R CMD SHLIB --dry-run --output=dummy.so px.c
make cmd is
  make -f 'Makevars' -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' -f '/Users/kevin/.R/Makevars' SHLIB='dummy.so'

make would use
if test  "zinit.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o" != "z"; then \
          echo clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o dummy.so init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
          clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L"/Library/Frameworks/R.framework/Resources/lib" -L/opt/R/arm64/lib -L/opt/homebrew/lib -o dummy.so init.o api-common.o common.o extra.o dummy.o error-codes.o posix.o api-posix.o macos.o api-macos.o arch/macos/process_info.o   -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation; \
        fi
```

**Comment by romainfrancois** [comment]
Now doing: 

  - `R CMD SHLIB --dry-run --output=<non-existing>.so`

This gives a `make` cmd, and then runs it with `-n` (aka `--dry-run`) by `.shlib_internal()` here: https://github.com/r-devel/r-svn/blob/3860555d86812fa3cfec56062d35ddf31fd0d737/src/library/tools/R/install.R#L2713

We disregard this output, and then just run the same `make` command with *both* `--dry-run` and `--always-make`

**Comment by romainfrancois** [comment]
I tried it with `rlang`, `ps` and `readxl`, both when `.o` and `.so` already exist and not. I think this works.

**Comment by DavisVaughan** [comment]
> We disregard this output

Why do you disregard it? Is the output of `R CMD SHLIB --dry-run --output=<non-existing>.so` not already what you wanted?

**Comment by romainfrancois** [comment]
it is unless there would have nothing to do, adding `--always-make` makes it work even if all the `.o` are there already

**Review by kevinushey — APPROVED** [review]
LGTM!

**Pull request merged**
