### PR TITLE
Use brightness instead of drop shadow in dark themes

### PR DESCRIPTION
**Pull request by jmcphers**
### Intent

Make the icons for R and Python look more consistent with the rest of our icons in dark themes. 

Before:

image

image

After:

image

image

### Approach

Remove drop-shadow filter, add brightness filter.

### Automated Tests

None, style only change.

### QA Notes

No QA needed.

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
The icons look a bit washed out, IMHO. Is there anything else we can do to bump the contrast a bit? Either experimenting with a very light drop-shadow, or perhaps a thin black stroke around the icon?

**Comment by jmcphers** [comment]
I realize the washed-out lower-contrast look is not as true to the original icons, but it's very much in keeping with the rest of our icons in dark mode, which are also low saturation (washed out).

image

**Comment by kevinushey** [comment]
Do you think we could do anything to tweak the R logo to make it a bit more visible? Something like adjusting the hue / saturation a bit more just to give it a color that stands out a bit more on our dark theme background?

**Comment by jmcphers** [comment]
@kevinushey How do you feel about this? 

image

**Comment by kevinushey** [comment]
That might be a little bit too bright. I think we can stick with the first iteration (sorry for the nitpicking!)

**Comment by jmcphers** [comment]
No worries, this is a high visibility item so worth the extra scrutiny!

**Pull request merged**
