### PR TITLE
improve auto completion for `[.data.table`

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #11202

### Approach

This needs more work, but trying to get more sensible completions for these situations : 

```r
library(data.table)
dt <- data.table(
  col1 = 1:10,
  col2 = 101:110
)
dt[, <TAB>
dt[, by = <TAB>
```

So that we get the [data.table special symbols](https://rdatatable.gitlab.io/data.table/reference/special-symbols.html) i.e. `.SD`... 

`j =` completions:

https://user-images.githubusercontent.com/2625526/199554041-8ba0faeb-2518-46eb-822e-62d2a1339469.mov

`by = ` completions

https://user-images.githubusercontent.com/2625526/199554384-0dfe0a97-3b40-43c9-92db-891e2c7f69e3.mov

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
The `by = by` completion should not be there, I'll investigate. 

Also, I guess the special symbols should also be offered in nested cases, but is currently not: 

image

I'm sure there are other cases where completions could be more useful for `data.table` users

**Comment by romainfrancois** [comment]
🤔 now in the situation where arguments of `[.data.table` are wrongly offered:

image

image

**Comment by romainfrancois** [comment]
Currently: 

columns and arguments: 

image

`j` completion. columns, arguments, and special symbols:

image

The yellow popup displays symbol specific information, extracted from `help("special-symbols")`. 

`by` completion have the extra `.EACHI` 

image

(the `by = by` thing is a bug unrelated to this PR).

We also get the special symbols for these cases: 

image

image

cc @mattdowle @david-cortes 

This could be more fine tuned, perhaps we can reconsider as part of #12057, but I believe this PR already improves the situation.

**Review by kevinushey — APPROVED** [review]
LGTM!

**Pull request merged**
