### PR TITLE
implement improved roxygen highlighting

### PR DESCRIPTION
**Pull request by kevinushey**
Note: not quite ready for merge; would like to get some feedback from @hadley et al. on other things that might be worth tweaking (or not tweaking) for Roxygen highlighting.

This PR currently does two things:

1. Highlights the first term after certain roxygen tags (e.g. `@param`, `@slot`)

2. Highlights R code within an `@examples` block as R code.

Example from `dplyr` sources:

screen shot 2016-08-12 at 3 08 01 pm

### CODE REVIEW

**Comment by kevinushey** [comment]
This PR also resolves some issues in the multiline expression execution logic, when attempting to execute the R expressions within an `@examples` block.

**Comment by jjallaire** [comment]
@hadley We are trying to decide if syntax highlighting R code within "@examples" is a good thing or whether it's visually confusing. As you know we already have code execution working and this PR also brings in code completion. Note that another possibility would be to color it distinctly but not to fully syntax highlight it.

**Comment by hadley** [comment]
I like the idea, but agree it might be too much visually. Could you fade the highlight somehow?

**Comment by jjallaire** [comment]
I don't think we can do an alpha over the entire palette (this might
involve creating or deriving custom colors for all the themes) and I'm not
sure that would solve the problem unless we faded it quite a bit.

A nice alternative might be to use the doxygen keyword color (same color we
use for Rcpp attributes) since this color is optimized for display within
comments. I believe this color is "comment.doc.tag".

**Comment by lionel-** [comment]
How about adjusting the background color of the whole roxy block, like with Rmd chunks? That should work well with most color schemes.

**Comment by jjallaire** [comment]
That still might be too distracting. I'm thinking that the background color
is going to be pretty heavyweight and that plus the syntax highlighting
will make the "@examples" the dominant feature of the source file. In Rmd
this is of course on-purpose as want the R chunks to dominate but for
roxygen we want the entire roxygen section to recede.

**Comment by kevinushey** [comment]
IMHO one alternative we might want to think about in the future is making it easier to edit + use examples with the `@example` tag. E.g. for the roxygen

```
#' @example examples/foo.R
```

I think it would be pretty nice if we could e.g. Cmd + Click on the file name to open the examples file, and have that open in a split window (e.g. not as a whole separate source window, but in the same Source pane). This way you'd get to view the roxygen + function context while writing up examples.

The tricky UI part would likely be reconciling that with the tabs on the Source pane, since the split window might not be coherent with that. I imagine if we made it easier to work with `@example` it could potentially become more useful than `@examples`, as long examples in roxygen can become unwieldy.

**Comment by kevinushey** [comment]
I'm going to merge this without the `@examples` code highlighting just because it's a bit contentious whether that's universally better; in addition it also exposes a number of other issues that we have in roxygen chunks (e.g. auto-indentation doesn't quite work as expected; nor does autocomplete and friends).

If we want to highlight roxygen example R code then I think we need to do the extra work to make it behave as though it were just regular R code.

**Pull request merged**
