### PR TITLE
chain completions before search path completions

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #11749

### Approach

just have them added sooner to `completions` in `.rs.rpc.get_completions`

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

```r
library(dplyr)
tab <- tibble(shotsOnTarget = 1)
tab %>% select(sho
```

image

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
But snippets always come first by design. Should this be overuled when completions of type `COLUMN` are involved ? I'd believe this is more likely to be what the user wants: 

image

**Comment by romainfrancois** [comment]
Or would we want to not offer snippets when there is a chain ? At the moment, it is governed by: 

https://github.com/rstudio/rstudio/blob/0995e6a6a2912a2f5852e43ad1b7492b28e9b664/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java#L332-L337

but here is a hint that we may want more cases ? is this one of them ?

https://github.com/rstudio/rstudio/blob/0995e6a6a2912a2f5852e43ad1b7492b28e9b664/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java#L456-L459

**Comment by kevinushey** [comment]
> But snippets always come first by design. Should this be overuled when completions of type COLUMN are involved ? I'd believe this is more likely to be what the user wants:

I would agree with that. Perhaps the completion system could also set a flag about whether it thinks snippet completions are appropriate in the current context? (Or we can just disable snippets if we have COLUMN completions as you said)

**Review by kevinushey — APPROVED** [review]
PR as-is LGTM but I'll let you choose whether to merge or amend with snippet-related tweaks.

**Comment by romainfrancois** [comment]
I can do another one for snippets next week.

**Pull request merged**
