### PR TITLE
allow user to control behavior of autocomplete + Tab key

### PR DESCRIPTION
**Pull request by kevinushey**
### Intent

Addresses https://github.com/rstudio/rstudio/issues/13446.

##### TODO

- [x] Confirm that Tab works as expected here.
- [x] Provide a command / keyboard shortcut for requesting Copilot suggestions.
- [x] Prefer displaying the code completion panel on top, so it doesn't obscure ghost text.

### Approach

This PR gives the user some options controlling how GitHub Copilot's code suggestions will live + work together with the existing autocompletion system.

Screenshot 2023-08-18 at 12 55 53 PM

The intention here is that, for users who'd still like to get as-you-type autocompletions, they can enable the preference, and then when a user is in this state:

Screenshot 2023-08-18 at 12 57 38 PM

they can still use Tab to insert the Copilot code suggestion, rather than the selected completion from the list. (The Enter key can be used to insert that completion.)

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by kevinushey** [comment]
Example of the display:

Screenshot 2023-08-29 at 1 18 32 PM

In this state, pressing Tab will accept the Copilot code suggestions, while pressing Enter will accept the completion candidate. If the user wants to dismiss the completion popup so they can view the ghost text, they can use the Escape key.

**Comment by jgutman** [comment]
Just taking a look at this now, but I notice that I can enable the copilot code completions setting from the Command Palette, but it does not display in Global Options, as you showed in the above screenshot. Is there a reason this isn't showing there?

image
image

**Comment by jgutman** [comment]
One note, and I think this is unavoidable, but this will have weird behavior if the user has enabled `Code > Completion > Show code completions: Manually (tab)`

With that setting enabled, you would get a scenario where pressing tab prior to the Copilot keyboard idle delay displays the code completions, but pressing tab after the Copilot delay once the Copilot suggestion has appeared will accept the suggestion. I don't really see a way around that, since the manual tab completions don't really play nicely with the Copilot suggestions, but wanted to point that out

**Comment by jgutman** [comment]
Also, it seems like if the setting is set to Tab inserts completions, then neither tab nor enter inserts the Copilot suggestion. How do you get the Copilot suggestion if you've set Tab to prefer the completion?

**Comment by kevinushey** [comment]
> Just taking a look at this now, but I notice that I can enable the copilot code completions setting from the Command Palette, but it does not display in Global Options, as you showed in the above screenshot. Is there a reason this isn't showing there?

I'm sort of thinking (after playing with this for a bit) we shouldn't expose those options in the UI, as they make it a bit too easy to make Copilot awkward to use.

That is, I think we should:

1. Respect the user's preference for as-you-type code completions, and continue showing those as normal;
2. Adjust the behaviour of Tab so that it prefers inserting Copilot suggestions (when visible) as opposed to a selected code completion.

We can leave them behind as accessible from the command palette if we find out we're wrong and users _do_ want to adjust this behavior?

> Also, it seems like if the setting is set to Tab inserts completions, then neither tab nor enter inserts the Copilot suggestion. How do you get the Copilot suggestion if you've set Tab to prefer the completion? By deactivating/escaping and then tabbing?

That's right. It's not a particularly useful configuration...

**Pull request merged**
