### PR TITLE
Add keyboard shortcuts for debugging functions

### PR DESCRIPTION
**Pull request by igitur**
Add keyboard shortcuts (modelled on Visual Studio shortcuts):
F11: Step into function
Shift+F11: Finish function/loop

### CODE REVIEW

**Comment by jjallaire** [comment]
The problem here is that F11 is used by some window managers (e.g. on Mac OS X it is used to "Show Desktop"). @jmcphers and @kevinushey Any suggestion for how we should handle this? (we could have distinct or no shortcuts for OS X?)

**Comment by igitur** [comment]
Ah ok, wasn't aware of that. How about Shift+F10 ?

**Comment by kevinushey** [comment]
It looks like on OS X the combination of `CMD + F11` is not handled by the window manager, so that could be an alternative.

**Comment by jjallaire** [comment]
Note that Shift+F11 is also taken by the OS X window manager.

**Comment by jjallaire** [comment]
I like the suggestion Shift+F10 for step into. For "Finish" perhaps we could use another combo entirely (e.g. Shift+F4) since some of the other debugging commands are Shift+<Fn>

**Comment by jjallaire** [comment]
I'll try Shift+F10 + Shift+F4 on another branch and test on the various browsers/platforms before merging.

**Comment by jjallaire** [comment]
Keyboard shortcuts are a nightmare. Shift+F10 doesn't work on Windows QtWebkit (it opens a context menu). I switched it to Alt+F10 and on Ubuntu this opens the networking menu. Argh!

**Comment by jjallaire** [comment]
Ended up having to use Shift+F4 and Shift+F6: https://github.com/rstudio/rstudio/pull/375/files

**Pull request closed without merging**
