### PR TITLE
use custom menu styles for Windows + GNOME 3

### LINKED ISSUE #3052: tweak styling of menus with GNOME 3 / Ubuntu 18.04
See e.g.

screen shot 2018-06-21 at 8 07 15 am

It'd be nice if we could reduce the contrast a little bit -- the menus are a bit too 'bright' by default.

### PR DESCRIPTION
**Pull request by kevinushey**
Before:

screen shot 2018-07-25 at 3 06 40 pm

After:

screen shot 2018-07-25 at 3 05 47 pm

Closes #3052.

@jjallaire, let me know what you think.

Also let me know what you think about the display of mnemonics. It looks like GNOME 3 explicitly removed support for 'auto' mnemonics (e.g. toggling the display of mnemonics by pressing the <kbd>Alt</kbd> key -- why, I have no idea) so we have no choice but to either always display them or never display them.

(Or, we could try to manage their display ourselves -- some applications seem to attempt this, e.g. LibreOffice -- but the experience there is far from perfect and the mnemonics seem to flicker a lot)

### CODE REVIEW

**Comment by jmcphers** [comment]
I think people with dark themes might be annoyed that the menus are always bright white (in the case of dark RStudio + dark desktop theme, they could be pretty jarring). Would it be easy to load a reverse-video stylesheet when using a dark theme? 

Does this fix https://github.com/rstudio/rstudio/issues/3217, too? (If not, maybe the `gnome` test needs to be more permissive?)

**Comment by kevinushey** [comment]
Now with support for dark themes:

screen shot 2018-07-25 at 4 31 39 pm

Note to self: take the time to properly bundle + load the CSS styles rather than just embedding them in the C++ source ...

**Comment by kevinushey** [comment]
I think it's probably worth the time to match the main menu theme to the IDE theme. The difference in color between the main menu and the IDE itself is a bit jarring.

**Comment by kevinushey** [comment]
And now with themes adapted for Windows:

screen shot 2018-07-27 at 1 59 39 pm

Note: I wish we could also adjust the title bar colon, but as far as I can tell Windows nor Qt expose any APIs for doing this. That said, it certainly must be possible as e.g. one can enable a dark theme Microsoft Edge which gives a dark-colored title bar.

**Comment by kevinushey** [comment]
Looking at this further, it's not possible to style the title bar on an application-specific basis in Windows. Rather, the application must instead 'fake it' and implement its own menu-titlebar hybrid.

This implies making the window frameless. Unfortunately, making a window frameless implies turning off Windows' default resize + move behaviors for Windows; one must instead explicitly implement the 'regular' window behaviors by hand; that is:

1. Choosing the appropriate cursor based on the cursor position (ie: drawing resize cursors near the window edge),

2. Implementing appropriate window resize behavior (ie: tracking mouse down, mouse move, and mouse up events to implement window resize)

3. Handle cases where the mouse is e.g. near the top border but actually hovering over a menu item,

4. Implement facades for the minimize, maximize, and close icons.

This is all doable, and doable in Qt, it's just rather involved and potentially bug-prone as IIUC we need to install a native event filter for processing these events (ie: implement our own WndProc overrides for certain mouse events)

Worth noting that once we get into the business of rendering our own menu bar, it no longer needs to happen in Qt: we could just implement it directly in GWT (as we do for RStudio Server) but hook up the appropriate desktop events in that case. Not sure if that's truly easier than implementing it in Qt, beyond that we'd get better support for certain things e.g. SVG animations + styling + transition effects for e.g. hover.

**Comment by jjallaire** [comment]
Okay, I would argue that given the effort required we shouldn't implement our own titlebar using a frameless window (too many small things to get right, we'd be chasing this one for a long time).

**Comment by jmcphers** [comment]
Agreed, in my view frameless windows can be made to look very cool but are expensive and hard to do tastefully!

@kevinushey given that we don't want to pursue more aggressive styling or control, is this PR ready to go as-is?

**Comment by kevinushey** [comment]
Yes, I think this PR should be ready to go!

**Pull request merged**
