### PR TITLE
fix issue discovered in multiline expr execution

### LINKED ISSUE #3582: multi-line statement detection failed in certain case
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.1015 Build 1018 (553888ce)

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.0.0
```

The code below should draw a ggplot plot. Note the plot is meaningless because it was modified from my code. Also the indent may seemed to be unnecessary here but it was needed because the original code is much longer.

If you select the whole statement and run it, there is no problem.

```r
library(ggplot2)
ggplot(mtcars) +
  geom_errorbarh(
    aes(xmin = disp, xmax = hp, y = mpg), 
    size = 0.45, height = 0.35) +
  guides(color = FALSE)
```

If you place cursor inside the statement and cmd-enter, only a part of statement was picked up:

```r
>     aes(xmin = disp, xmax = hp, y = mpg), 
Error: unexpected ',' in "    aes(xmin = disp, xmax = hp, y = mpg),"
>     size = 0.45, height = 0.35) +
Error: unexpected ',' in "    size = 0.45,"
>   guides(color = FALSE)
```

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3582.

### CODE REVIEW

**Comment by jmcphers** [comment]
Do we need this for 1.2?

**Comment by kevinushey** [comment]
I think we can live without this for v1.2.

**Comment by kevinushey** [comment]
I tried changing the base from master to v1.3 and things went bonkers. I can just cherry-pick this to v1.3 to avoid messing up the git history.

**Comment by kevinushey** [comment]
Cherry-picked to v1.3.

**Pull request closed without merging**
