### PR TITLE
Improve RStudio startup diagnostics

### PR DESCRIPTION
**Pull request by jmcphers**
### Intent

This change makes three important upgrades to RStudio's startup diagnostics:

- The RStudio build, version, and platform information is now included in the diagnostic report. Addresses https://github.com/rstudio/rstudio/issues/6628. 
- The report now ends in a large Copy Problem Report button that prepares a plain-text (Markdown) version of the report for pasting into support forums and/or Github. This ensures we see the whole report and that it's searchable.
- The "recent logs" section of the report now actually shows the most recent logs. Addresses https://github.com/rstudio/rstudio/issues/9117. 

image

....

image

### Approach

Include a second copy of the report in a hidden `<textarea>` and add Javascript to copy it; inject the user agent into the report; fix comparison that incorrectly selected oldest rather than newest logs.

### Automated Tests

None, diagnostics change only.

### QA Notes

A good (and easily reversible) way to break R so that it won't start is to mangle a few of the early bytes in `libR.dylib`. 

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by gtritchie — APPROVED** [review]
Nice! LGTM!

**Comment by R-Hannibal** [comment]
@jmcphers - are there any additional QA Notes available? 

In particular "Collect session logs for enough time that a .rotated.log session log file appears (or create one manually)" - how to do this, and "mangle a few of the early bytes in libR.dylib" - where is this file located?

**Comment by jmcphers** [comment]
Session logs live in `~/.local/share/rstudio/log`. You can create a new session log in there, `rsession-newer.log`, and it should get picked up by the diagnostics automatically.

`libR.dylib` is part of your R installation. Run `R.home()` in RStudio to see where your R installation lives. `libR.dylib` will be in its `bin` folder.

**Comment by R-Hannibal** [comment]
Ran `R.home()` which yields:

```
> R.home()
[1] "C:/PROGRA~1/R/R-40~1.4"
```

However I cannot find the `libR.dylib` file anywhere. All my R versions are installed at C:\Program Files\R, and looking in each version specific folder the file does not appear to be there (looked manually in bin and did a search of the entire folder).

@jmcphers - any ideas why I'm not seeing this file anywhere? Is it dynamically created by a certain user action, or should it just be there on install?

**Comment by jmcphers** [comment]
> However I cannot find the libR.dylib file anywhere.

It's because you're on Windows; `.dylib` is for macOS (on Windows it's a `.dll`)

**Pull request merged**
