### PR TITLE
Remove most usages of String.equals()

### PR DESCRIPTION
**Pull request by jmcphers**
Since upgrading to Java 8 / GWT 2.8.1, we've had a number significant regressions stemming from new behavior in `String.equals()`.

Snippets entirely broken: https://github.com/rstudio/rstudio/commit/1690899038ed5090be44b2afa2b247c2246182d2
Can't save new documents: https://github.com/rstudio/rstudio/commit/58d880a6890ee39f2508113bf4858c85e01fa015

What changed? In GWT 2.7, the generated JavaScript code made it okay to run `lhs.equals(rhs)` *even if `lhs` was null*. This is no longer okay, and throws a `NullPointerException`. 

In most cases, we tried to guard against this usage by ensuring that `lhs` was not null before calling `.equals()` on it. However, since no runtime error ensued from incorrect usage, we don't know how effective the guards are, and there are probably dozens or more of these bugs hiding in all corners of the product. 

This change replaces every instance of `lhs.equals(rhs)` with `lhs == rhs` (when lhs is a `String`), which gives us the most GWT 2.7-like behavior (i.e. it just returns false if `lhs` is `null`). Unfortunately such a change was not possible to make fully mechanically, and in the interest of brevity I've not removed the following usages of `String.equals()`:

- Cases wherein it is immediately obvious that `lhs` is a variable that cannot be `null` at the given point in control flow
- Cases wherein `lhs` is a string constant or static variable

There's always some risk in changing large swaths of code like this, but in my view it reduces risk on the balance given the behavior change (feedback/discussion welcome).

### CODE REVIEW

**Comment by gtritchie** [comment]
LGTM. Good to get in now and maximize time we have to shake out any other corner cases.

**Comment by jmcphers** [comment]
Spent a little time this PM trying to assure myself that we really need to do this. For some background, `String.equals()` eventually dispatches to this code in GWT 2.7, where `this$static_0_g$` is LHS and `other_0_g$` is RHS:

    function $equals_2_g$(this$static_0_g$, other_0_g$){
      return this$static_0_g$ === other_0_g$;
    }

So if called with an LHS of `null`, it's fine--testing `null === "foo"` is acceptable.

Finally, http://www.gwtproject.org/release-notes.html for 2.8.1 says:

> Specialize Objects.equals for strings.

Here's the equivalent decompiled JS from 2.8.1:

    function BVe_g$(this$static_0_g$, other_0_g$){
      return MLc_g$(Nhg_g$(this$static_0_g$)) === MLc_g$(other_0_g$);
    }
    
It's a little hard to tell because of the mangled method names, but in 2.8.1 there's a new reference check wrapper (obfuscated as `Nhg_g`) which validates that the LHS is in fact a reference to an object, and throws `NullPointerException` if it's not.

Finally, http://www.gwtproject.org/release-notes.html for 2.8.1 mentions this change:

> Specialize Objects.equals for strings.

This explains why we've never seen these errors before; we didn't have any reference checks on the LHS and were implicilty just using `===` previously, whereas we now must do so explicitly.

**Comment by kevinushey** [comment]
We might want to implement a `StringUtil.equals()` method that just delegates directly to `===`, since (IMHO) this is the behavior we typically prefer.

**Comment by jmcphers** [comment]
What's the advantage of this approach vs. just calling `==` ?

**Comment by kevinushey** [comment]
I guess my reasoning is somewhat pedantic. In Java, `==` checks for identical objects rather than 'equal' objects; e.g. this will return false:

```java
new String("abc") == new String("abc");  // false
```

An over-zealous GWT developer might decide one day that these semantics should be respected here as well, so suddenly our usages of `<string> == <string>` could break again. Being explicit about the fact that we want the JavaScript `==` behavior feels safer.

**Pull request merged**
