### PR TITLE
Upgrade Ace to v1.28

### PR DESCRIPTION
**Pull request by jgutman**
### Intent
Addresses #13592 -- upgrading Ace to get some bugfixes and accessibility improvements

Please see https://github.com/rstudio/rstudio-ace/commits/rstudio/ocean-storm for further info

### CODE REVIEW

**Comment by kevinushey** [comment]
LGTM but let's resolve the comment re: Ace's built-in autocompletion threshold before merge?

**Comment by jgutman** [comment]
Done -- removed both autocompletion threshold and autocompletion delay patches as discussed on the branch

**Comment by jgutman** [comment]
Do Ace upgrades need to get mentioned in NEWS, or no?

**Comment by kevinushey** [comment]
Good question; in the past I don't think we've mentioned them consistently. I think we should mention it, though -- especially if we can confirm that we'll be benefiting from their work on accessibility.

**Comment by resistor4u** [comment]
Not necessarily the place, but any thoughts on whether upgrading Ace impacts #12370 ?

**Pull request merged**
