### PR TITLE
use absolute path for rpostback-askpass

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/rstudio/issues/3805.

There is a bit of risk in this PR, as it looks like the original implementation (using the program name + modifying the PATH) was intentional:

https://github.com/rstudio/rstudio/commit/58dd0deacf1ac6b9f9c7173bbfa7d2c70fdcb3fe

However, it's quite possible that things have changed enough in 8 years that we can use full paths for GIT_ASKPASS / SSH_ASKPASS.

### CODE REVIEW

**Comment by jmcphers** [comment]
Did @jcheng5 clue us in on why the switch was originally made away from absolute paths?

**Comment by jcheng5** [comment]
Sorry, Kevin asked but I couldn’t remember.

**Comment by jcheng5** [comment]
If you really are curious maybe search in fogbugz? 😛

**Comment by jmcphers** [comment]
Couldn't find anything obvious there. _kicks down Chesterson's fence_

**Pull request merged**
