### PR TITLE
add commands for zooming/unzooming active pane

### PR DESCRIPTION
**Pull request by kevinushey**
NOTE: Not yet ready for merge (need to find a way to more properly ensure focus doesn't change on zoom).

This PR adds a command that makes it possible to zoom the console, or active source pane, to full size -- here I'm triggering the command with `Ctrl+X Ctrl+Z` via a custom binding.

maximize-pane

Other TODO items:

- [x] Consider 'exclusive' vs. 'maximized' view,
- [x] Consider enabling for plot pane etc.
- [x] Consider default keybinding for zoom / unzoom command
- [x] Invalidation of zoom 'cache' on manual resize / maximization

### CODE REVIEW

**Comment by jjallaire** [comment]
Great! People will love this. I'll do a code review tomorrow. One additional thing we may need here is a button that pairs with the Min/Max buttons that does a zoom. Alternatively we could have something on the Global Toolbar that allows you to choose a pane to fully zoom. Benefits of the latter approach would be:

1) Much easier to implement (if you look at the way min and max events propagate through the system you'll see that this touches a lot of code)

2) Allows for an easy toggle between e.g. zoomed console and zoomed plots (if the button was pane local you'd have to unzoom the first pane before zooming the second).

**Comment by jjallaire** [comment]
I've reviewed the code and it all looks fine. Here is what I propose we do to complete this feature:

1) As I described above, I think we need top-level user interface elements not just keyboard shortcuts for doing this (otherwise I think very few users will take advantage of it).

2) I propose that we add a "Zoom" sub-menu to the "View" menu with entries for all of the panes. For consistency with the shortcuts we already use for pane switching we could use e.g. "Shift+Ctrl+1", "Shift+Ctrl+2". Alternatively we could use corded "Ctrl+Z Ctrl+1", "Ctrl+Z Ctrl+1" (these would just be a bit harder to learn for users not familiar with corded shortcuts).

3) We should probably also add a button to the Global Toolbar for easier access. I think this could just be an icon next to the current Git/Svn icon (I don't think we'd need the text "Zoom" on it).

4) In cases where panes raise themselves now they still need to raise themselves when the IDE is in zoom mode (e.g. if you print a plot from the console it needs to switch to the plots pane). This raises the issue that you'd then want to go easily "back" to the console (the issue would also come up when executing code from the source pane). My proposal for this would be to move the Forward/Back icons off the source pane toolbar and onto the global toolbar (I think they'd fit nicely to the left of the Go to file/function search box, with the zoom button being to the right of the search, we'll have to try to be sure). The Forward/Back commands would then need a global implementation that delegates to the Source window when appropriate.

If all of this seems like too much we can certainly defer until the next release.

@jmcphers Let us know your thoughts as well.

**Comment by kevinushey** [comment]
> 1) As I described above, I think we need top-level user interface elements not just keyboard shortcuts for doing this (otherwise I think very few users will take advantage of it).

Good idea -- just to make sure I understand, are we thinking of another icon that would live with the 'min/max' icons for each pane? So we would then have `[min / max / zoom]` or something to that effect?

> 2) I propose that we add a "Zoom" sub-menu to the "View" menu with entries for all of the panes. For consistency with the shortcuts we already use for pane switching we could use e.g. "Shift+Ctrl+1", "Shift+Ctrl+2". Alternatively we could use corded "Ctrl+Z Ctrl+1", "Ctrl+Z Ctrl+1" (these would just be a bit harder to learn for users not familiar with corded shortcuts).

This sounds like a great idea as well; in particular it makes it easy to toggle zoom + focus for different parts of the IDE (it could be a nice way to switch to and from a maximized console, source window, etc)

> 3) We should probably also add a button to the Global Toolbar for easier access. I think this could just be an icon next to the current Git/Svn icon (I don't think we'd need the text "Zoom" on it).

Sounds good!

> 4) In cases where panes raise themselves now they still need to raise themselves when the IDE is in zoom mode (e.g. if you print a plot from the console it needs to switch to the plots pane). This raises the issue that you'd then want to go easily "back" to the console (the issue would also come up when executing code from the source pane). My proposal for this would be to move the Forward/Back icons off the source pane toolbar and onto the global toolbar (I think they'd fit nicely to the left of the Go to file/function search box, with the zoom button being to the right of the search, we'll have to try to be sure). The Forward/Back commands would then need a global implementation that delegates to the Source window when appropriate.

Sounds good -- I'll take a stab at this, although it might take a bit of iteration to figure out what really feels right.

**Comment by jjallaire** [comment]
On Aug 24, 2015, at 12:47 PM, Kevin Ushey <notifications@github.com> wrote:

Good idea -- just to make sure I understand, are we thinking of another
icon that would live with the 'min/max' icons for each pane? So we would
then have [min / max / zoom] or something to that effect?

No, I'd keep it just to the global level toggling discussed below.

**Comment by kevinushey** [comment]
Here's how things look right now (movement of the Forward / Back buttons from the source pane not yet done):

screen shot 2015-08-26 at 11 16 04 am

screen shot 2015-08-26 at 11 16 12 am

What do you think about moving the various 'activate' commands into the `Show` sub-menu? (I did this because the menu felt too cluttered when expanding the `Zoom` sub-menu when those were part of the 'main' `View` menu)

**Comment by jjallaire** [comment]
Yes, I think consolidating the Show items on a sub-menu makes good sense.

**Comment by kevinushey** [comment]
@jjallaire, I think this PR is ready for a second review now. I was correct in my prior speculation -- we can successfully transfer from zoom to zoom by first moving all windows to the 'normal' state, then immediately after transferring to a second zoom. This obviates the need to change any pre-existing logic.

This PR also modifies the activation logic to ensure that panes make themselves visible both vertically and horizontally; this implies that e.g. if you call `plot(1)` while only the console and source panes are visible, the plots pane will scroll into view as well. (In zoom mode, the plots pane becomes the new 'zoomed' pane)

**Comment by jjallaire** [comment]
Will review the implementation shortly. In the meantime some comments on user-level behavior / features:

1) I checked in Paul's version of the Pane Layout icon, let me know if you think it looks okay.

2) We still need the menus to use check marks to denote the current state

3) We still need a Pane Layout sub-menu for the View menu

4) I noticed that the Viewer pane isn't in the list (this is also the case for the tab switching commands). I think we should add the Viewer to both and perhaps take the keyboard shortcut for Packages (as I doubt it's used much). That would leave us with one too few numeric shortcuts. I'd advocate for bumping "Build" (as the Cmd+Shift+B shortcut already activates Build) and then perhaps giving it Ctrl+F1 (then the next pane we do is Ctrl+F2, etc.).

5) We need a keyboard shortcut for Show All Panes

6) I think that it would be natural and more clear to use "Source Only", "Console Only", etc. for the menu captions (to distinguish them clearly from merely "activating" the pane). Since they will all have the word "Only" it will basically wash out and be white noise to the user (in case you were worried about "Only" being too busy.

**Comment by jjallaire** [comment]
The implementation looks good to me so I'm going to merge it now. We can make the additional changes suggested above directly on master.

**Pull request merged**
