### PR TITLE
Add support for hyperlinks in job names

### PR DESCRIPTION
**Pull request by javierluraschi**
In sparklyr, jobs have not text output, instead, there is a detailed job url that would be more helpful to navigate to; additionally, I don't think it would be uncommon to have an url with additional information associated to jobs for other clusters technologies.

This PR adds a `url` parameter in `.rs.api.addJob`; when not specified, the Jobs UI remains unchanged with no hyperlink treatment. However, when specified, the Job name becomes a Url.

For sparklyr, this could be used for:

screen shot 2018-06-20 at 3 57 50 am

to navigate to...

screen shot 2018-06-20 at 4 01 28 am

### CODE REVIEW

**Comment by jmcphers** [comment]
How well does the Spark stage status page render in the Viewer pane? If it looks okay, then maybe it'd make more sense for the job output link `(>)` to load the URL given rather than the text output. That way you don't have a `(>)` link that shows an empty page, and you can watch the stage URL from inside RStudio. What do you think?

**Comment by jjallaire** [comment]
I don't love the appearance of the hyperlinks. Jonathan's suggestion is one way to resolve this (just have the arrow open the job info either in the Viewer or in an external browser). Another way would be to keep the text black but then have another icon right next to it that could be used to navigate.

**Comment by jmcphers** [comment]
If you decide to go the viewer route, we can (and probably should) use the job output pane as the "viewer", so that the UX is constrained within the Jobs pane -- i.e. just replace the text output widget with an RStudioFrame widget. You'll also get a slide in/out transition this way. :-) 

If you go the icon route, you might consider using a feature merged a couple of days ago which allows for jobs to have an arbitrary set of custom actions that can be performed on them; this mechanism exists in part so we won't have to change the API signature as often. You could e.g. add a custom action `open` or `view` with a function that browses to the URL, and then give that custom action special treatment in RStudio, as the `stop` action is today. We have plans for (but haven't implemented) some basic UI for actions that RStudio doesn't recognize.

**Comment by javierluraschi** [comment]
The challenge is that the Spark UI comes with a menu and assumes that there is a lot of vertical space available; I do like the idea a lot, but most user would want to expand this in a new window anyways to see any meaningful flow/sequence graphs. I'll close this PR and update `sparklyr` with the custom action.

**Pull request closed without merging**
