### PR TITLE
Initial Quarto Manuscript Support

### PR DESCRIPTION
**Pull request by dragonstyle**
### Intent

Add support for new Quarto Manuscript type projects in RStudio. Quarto Manuscripts are a substantial focus on Quarto 1.4 and will be marketed widely, so this change should be back ported to older versions of RStudio when possible. 

Currently, create project, render, and build are all working. Publishing is currently at the last minute with the following message (all the wizards steps appear to be populating correctly):

```
Preparing to deploy site...DONE
Uploading bundle for site: 9975...Error in inferAppMode(appDir = appDir, appPrimaryDoc = appPrimaryDoc,  : 
  Attempting to deploy Quarto content without Quarto metadata. Please provide the path to a quarto binary to the 'quarto' argument.
Calls: <Anonymous> -> withStatus -> force -> bundleApp -> inferAppMode
Execution halted
```
@jmcphers Any chance you could take a look at the publishing error?

### Approach

There are a handful of places that RStudio 'knows' about Quarto project types, so this adds knowledge of 'Manuscript' projects to those locations.

### QA Notes

Publishing manuscript projects isn't currently working. Everything else (rendering, building, creating new projects) should be.

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by ronblum** [comment]
@dragonstyle Is this the implementation of #13391?

**Comment by dragonstyle** [comment]
> @dragonstyle Is this the implementation of #13391?

Indeed it is (I didn't know that issue was open so ty for linking to it)!

**Comment by jjallaire** [comment]
We are hoping to get this merged and into a daily build before my talk at Bioconductor next week (and ideally even this week so that @mine-cetinkaya-rundel can create screen recordings that use this). I think the PR as it stands is fine and uncontroversial. 

@jmcphers Publishing seems to work until the very end when a low-level error in `rsconnect:::inferAppMode()` occurs. If you could take a look at that and see if there is an easy fix we could have that land in this PR. If you don't think you can look at it before Friday then I think we should merge this now so that we can prepare for Bioconductor. I was hoping that we could get this all into one squashed commit so its easy to back port to older versions (as we'll want that for customers eager to start using manuscripts). But again if its not practical to nail down the publishing in the next couple of days we can do that as a second step.

**Comment by jmcphers** [comment]
Based on the error message, I think it's coming from the rsconnect package rather than from RStudio itself, so would likely require that we bundle a dev version of rsconnect with manuscript support if we wanted this to work within the next week. 

It's also possible there's some other way around the error. I'll take a look.

**Comment by dragonstyle** [comment]
We did some poking around and had the suspicion that there was conditionality on what we were passing to reconnect and that the fact that this is a new type of project was likely the source of the issue (e.g. somewhere we were conditionalizing passing configuration data to reconnect based upon project type of `website`)... But appreciate any help you can provide!

**Comment by jmcphers** [comment]
Can you describe in more detail how you're publishing? i.e. what project are you publishing, what UI gesture are you using to publish, and where are you publishing to?

I checked out the PR branch, cloned the repository https://github.com/cwickham/manuscript-template-rstudio, then rendered and published from the Viewer pane to rsc.radixu.com. The bundle upload succeeded, but I got this back from Connect:

```
[Connect] 2023/07/26 22:04:54.762775953 ERROR: Unsupported project type manuscript
[Connect] 2023/07/26 22:04:54.762791193 
[Connect] 2023/07/26 22:04:54.762830128 Error: Unsupported project type manuscript
[Connect] 2023/07/26 22:04:54.762831516     at projectType (file:///opt/quarto/bin/quarto.js:58184:15)
[Connect] 2023/07/26 22:04:54.762839890     at projectContext (file:///opt/quarto/bin/quarto.js:82769:30)
```

Does this suggest that I need to publish to a server that supports the `manuscript` type, or that the `manuscript` type is being incorrectly inferred? (Should Connect just see manuscripts as websites?)

**Comment by jmcphers** [comment]
Not sure if this behavior is specific to the PR, but also noticed that if you click Publish on the editor toolbar, with a notebook from the manuscript project open (e.g. `explore-earthquakes.qmd`), you get a script error:

image

This is because `quarto inspect` on `explore-earthquakes.qmd` results in an error:

```
quarto inspect notebooks/explore-earthquakes.qmd
ERROR: Unable to read the extension 'agu'.
Please ensure that you provided the correct id and that the extension is installed.

Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///Applications/quarto/bin/quarto.js:41583:15)
    at Object.extension (file:///Applications/quarto/bin/quarto.js:41482:34)
    at readExtensionFormat (file:///Applications/quarto/bin/quarto.js:75101:50)
    at resolveFormats (file:///Applications/quarto/bin/quarto.js:75047:41)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:74421:21)
    at async renderFormats (file:///Applications/quarto/bin/quarto.js:74472:26)
    at async inspectConfig (file:///Applications/quarto/bin/quarto.js:96121:29)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:96169:20)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8100:13)

```

Probably not related to what you're seeing.

**Comment by jjallaire** [comment]
Okay, @dragonstyle can we make sure that Quarto Inspect handles that correctly?

Incidentally you shouldn't be able to publish individual notebooks from the manuscript project (the publish button should resolve to the whole project much like websites and books do).

**Comment by dragonstyle** [comment]
Sorry for the lack of specificity.

We are publishing the rendered output of the repo <https://github.com/cwickham/manuscript-template-rstudio> to `colorado.posit.co`:

Screenshot 2023-07-27 at 3 09 34 PM

**From my testing, updating to rsconnect 1.0.1 resolved the initial issue that we were running into** - sorry for not testing this sooner!

Manuscript projects generate HTML output which includes links to source documents like `qmd` files and `ipynb` file as resources that can be downloaded. When publishing to connect, it appears to me that including these files in a static publish is triggering Reconnect to attempt to render/execute that files.

If I just accept the suggested files and publishI can see the publish succeeding:

```
✔ Deploying "manu123" to "server: connect.posit.it / username: charles"
ℹ Creating application on server...
✔ Created application with id 9979
ℹ Bundling 37 files: 'images/la-palma-map.png', 'index-preview.html', 'index.html', 'index.ipynb', 'index.out.ipynb', 'index.qmd', 'notebooks/explore-earthquakes-preview.html', 'notebooks/explore-earthquakes.out.ipynb', 'notebooks/explore-earthquakes.qmd', 'index_files/figure-docx/cell-5-output-1.png', 'index_files/figure-docx/cell-7-output-1.png', 'index_files/figure-docx/cell-9-output-1.png', 'index_files/figure-docx/fig-spatial-plot-output-1.png', 'index_files/figure-docx/fig-timeline-1.png', 'index_files/figure-html/cell-5-output-1.png', 'index_files/figure-html/cell-7-output-1.png', 'index_files/figure-html/cell-9-output-1.png', 'index_files/figure-html/fig-spatial-plot-output-1.png', …, 'site_libs/quarto-html/tippy.css', and 'site_libs/quarto-html/tippy.umd.min.js'
ℹ Capturing R dependencies with renv
✔ Found 107 dependencies
✔ Created 2,298,292b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 380875
```

But then see:

```
── Deploying to server ─────────────────────────────────────────────────────────
Building Quarto document...
Bundle created with R version 4.3.0 and Quarto version 99.9.9 is compatible with environment Local with R version 4.2.3 from /opt/R/4.2.3/bin/R and Quarto version 1.3.340 from /opt/quarto/1.3.340/bin/quarto 
Bundle requested R version 4.3.0; using /opt/R/4.2.3/bin/R which has version 4.2.3
Performing manifest.json to packrat transformation.
[rsc-session] Content GUID: e798945d-21b1-4b00-8b30-38b9
...
[rsc-quarto] Running 'quarto render'
[1/4] index.out.ipynb
[2/4] notebooks/explore-earthquakes.out.ipynb
[3/4] notebooks/explore-earthquakes.qmd


processing file: explore-earthquakes.qmd
1/7                   
2/7 [unnamed-chunk-1] 
3/7                   
4/7 [unnamed-chunk-2] 

Quitting from lines 14-15 [unnamed-chunk-2] (explore-earthquakes.qmd)
Error:
! 'la-palma.csv' does not exist in current working directory ('/opt/rstudio-connect/mnt/app/notebooks').
Backtrace:
 1. readr::read_csv("la-palma.csv")
 4. vroom (local) `<fn>`("la-palma.csv")
 5. vroom:::check_path(path)
Execution halted
Stopped session pings to http://127.0.0.1:41873
Unable to render the deployed content: Rendering exited abnormally: exit status 1
── Deployment complete ─────────────────────────────────────────────────────────
✖ Deployment failed with error: Rendering exited abnormally: exit status 1
```

Which is unexpected given that those source files are merely resources and should not be rendered. I'm not familiar enough with reconnect to know whether this is expected or if the static nature of the publish should somehow be preventing this...

**Comment by jmcphers** [comment]
Whew, glad an rsconnect update fixed that issue! 

You should double-check that your content was indeed published as static output. What I'd recommend is turning on publishing diagnostics (under Options => Publishing) then publishing again to confirm that the content type and bundle match what you expect. If they do, the Connect team will know best how to troubleshoot why a render is being triggered on the Connect side (I don't know offhand).

**Comment by dragonstyle** [comment]
Ok, here is the connect command that we're using:

```
Deploy command: 
 rsconnect::deployApp(appDir = "/Users/ct/Desktop/manu/_manuscript",      
                                       recordDir = "/Users/ct/Desktop/manu", 
                                       appFileManifest = "/tmp/942f-6b99-2ee7-1733",      
                                       account = "charles", 
                                       server = "connect.posit.it", 
                                       appName = "manu123123",     
                                        appTitle = "manu123123",
                                        contentCategory = "site", 
                                       launch.browser = function(url) {         message("Deployment completed: ", url)     }, 
                                       lint = FALSE, 
                                       metadata = list(asMultiple = FALSE, asStatic = TRUE),      
                                       logLevel = "verbose") 
```

We are permitted to explicitly specify whether we want Quarto to render the uploaded documents - the presence of a `qmd` file in the bundle defaults this to true. I think perhaps we should consider explicitly setting this to false when performing a static publish?

> quarto
   Should the deployed content be built by quarto? (TRUE, FALSE, or NA). The default, NA, will use quarto if there are .qmd files in the bundle, or if there is a _quarto.yml and .Rmd files.

Alternatively, we could make the `asStatic` flag override the `quarto` NA behavior... Adding @aronatkins as well as I'm not certain where exactly the fix belongs.

**Comment by aronatkins** [comment]
rsconnect does not process the metadata fields `asMultiple` and `asStatic`. I think those are present as breadcrumbs for the IDE to use on subsequent re-deploys.

The "kind" of content is derived from the files included in the deployment.
https://github.com/rstudio/rsconnect/blob/2f07fde4c8a2bf96cb89d07eaf4c8780e372a12d/R/appMetadata.R#L120-L122

To have the content considered static, yes -- exclude `*.rmd` / `*.qmd` files.

CC @hadley as well.

**Comment by hadley** [comment]
@dragonstyle let me know if you want to hop on a call and debug live

**Comment by dragonstyle** [comment]
Ok sadly it isn't as simple as passing `quarto = FALSE` in the case of known static QMD content. There is a logic in the reconnect package for determining the `appMode` of the deploy, which in the presence of QMD files, is always going to be `qmd-static` or `rmd-static`. Those values result in either attempted QMD renders or RMD renders of included `.qmd` files. 

https://github.com/rstudio/rsconnect/blob/2f07fde4c8a2bf96cb89d07eaf4c8780e372a12d/R/appMetadata.R#L178

With the help of @jmcphers I was able to force the `appMode` to `static` and successfully deploy.

**Comment by jjallaire** [comment]
I am going to go ahead and merge this so that Mine can do the screen recordings on Monday. Let's create a separate PR for publishing.

**Comment by ronblum** [comment]
FWIW I just did a quick check daily build 2023.09.0-daily+285 and confirmed that when I install quarto version 1.4.268, Quarto Manuscript shows up as a project option, but not with the bundled version, 1.3.433.

**Pull request merged**
