### PR TITLE
Disable bionic/focal unit tests

### PR DESCRIPTION
**Pull request by zachhannum**
### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

Since we switched back to using bionic as a base image for building focal (for debian10 compatibility), we need to re-disable the unit tests until rstudio/rstudio-pro#4681 can be addressed.

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by AndrewMcClain** [comment]
I'm a little worried about just disabling so many test for bionic, especially as we're about to certify for a release. Are we confident these test breakages don't represent a regression?

**Comment by zachhannum** [comment]
I updated the PR to only disable tests that need to be disabled, which includes r tests on all bionic builds and for some reason rsession and rserver on Open Source Electron builds. All other unit tests are passing.
You can see those builds passing for [Open Source here](https://build.posit.it/blue/organizations/jenkins/IDE%2FOS-Builds%2FPlatforms%2Flinux-pipeline/detail/jenkins-disable-bionic-tests-test/4/pipeline/) and [Pro here](https://build.posit.it/blue/organizations/jenkins/IDE%2FPro-Builds%2FPlatforms%2Flinux-pipeline/detail/jenkins-disable-bionic-tests/3/pipeline/1795/)

**Review by MariaSemple — APPROVED** [review]
LGTM

**Review by AndrewMcClain — APPROVED** [review]
LGTM

**Review by cm421 — APPROVED** [review]
LGTM

**Pull request merged**
