### PR TITLE
disable accessibility rendering on macos

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/rstudio/issues/1990 -- see the associated issue for my investigation.

Let me know if this is too broad and we should scope this particular change to just e.g. macOS, or macOS + user has `Magnet` running.

### CODE REVIEW

**Comment by jmcphers** [comment]
Will this prevent accessibility software (e.g. screen readers) from interacting with the contents of the window?

**Comment by kevinushey** [comment]
I think it will.

Since I'm the only person who's bumped into this rendering issue thus far, I think I should just guard this behind an environment variable or something similar and set it for myself.

**Comment by kevinushey** [comment]
Should be good to go now -- @jmcphers, let me know what you think.

**Comment by jmcphers** [comment]
It's hard for the average user to set env vars that are applied to Dock-launched apps on MacOS, so if people hit this in the wild we might want to make it a preference somewhere so that affected users can opt in easily. Until we have evidence that's necessary however I think this is great as is.

**Pull request merged**
