### PR TITLE
avoid using 'list.dirs' (performance)

### PR DESCRIPTION
**Pull request by kevinushey**
This PR avoids using `list.dirs()` when retrieving package completions, as that call can be surprisingly expensive (especially on networked file systems). Even on my Macbook Pro (with an SSD), I see:

```
> system.time(list.files(.libPaths()))
   user  system elapsed 
  0.000   0.001   0.001 
> system.time(list.dirs(.libPaths()))
   user  system elapsed 
  0.067   0.135   0.202 
```

I'm not sure why `list.dirs` would be so much slower here, but we should avoid using it regardless.

### CODE REVIEW

**Comment by jmcphers** [comment]
It looks like we're manually removing `DESCRIPTION` from the results. Could this change result in the inclusion of other files included at the top level of a folder in `.libPaths` (i.e. do we need to test the results to make sure they're directories)?

**Comment by kevinushey** [comment]
Testing whether they're directories is too expensive, so we explicitly avoid that. (As an aside, I plan on updating this PR to actually just index installed packages, to avoid crawling the filesystem on every completion request)

**Comment by jmcphers** [comment]
Nice! Is this ready for merge now?

**Comment by kevinushey** [comment]
I think this should be good to go now; however, we might want to consider marking this as a potential patch release candidate.

The work here was primarily motivated by Dr. Ligges (one of the CRAN maintainers) who noted that their RStudio sessions would hang while attempting to retrieve autocompletion results (they work in an environment wherein the entirety of CRAN is accessible on a networked filesystem, and so traversing those library paths is very slow).

**Comment by jmcphers** [comment]
Do we have reports other than this one user? There's a very high bar for the patch release so unless we think many people are affected I'm inclined to just leave this in 1.1.

**Comment by kevinushey** [comment]
I've had a number of ad-hoc reports from colleagues as well (mainly Windows users where their R library lives on an networked file system)

**Comment by jjallaire** [comment]
I agree that it would be nice to have this in the patch release but I think it's too big a change for the bar we have. I'd say once we've had this out in public preview for a few weeks it would be safer to backport.

**Pull request merged**
