### PR TITLE
Add search copy-button and breadcrumbs to News site

### PR DESCRIPTION
**Pull request by petetronic**
### Intent

Following on from the quarto features for the IDE User Guide, enable the copy-button and breadcrumbs in search of the news / release notes page.

See #14069 and #13618

### Approach

Update the _quarto.yml file to enable these search features for news / release notes.

### Automated Tests

N/A

### QA Notes

Review the Release Notes search results once this is deployed.

### Documentation

Implementing requested features for search in the Release Notes docs site.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Comment by petetronic** [comment]
@AshleyHenry15 do we want breadcrumbs on the news site? Or is it not structured in a way that would benefit from them?

**Comment by AshleyHenry15** [comment]
@petetronic - since it is a single file - the breadcrumbs won't even appear on the page. So, it isn't structured in a way that would benefit them. We can add them just to keep things standardized across our ymls but they won't have any impact on the site itself.

**Review by AshleyHenry15 — APPROVED** [review]

**Comment by jthomasmock** [comment]
@petetronic - I see this in Triage, should this be out of the project since it's a PR?

**Comment by ronblum** [comment]
@jthomasmock You're right. I cleared this out, and confirmed that the two issues (both in `test`) are in Chocolate Cosmos.

**Pull request merged**
