### PR TITLE
Add roxygen tags `@order` and `@examplesIf` for completion

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

adresses #11377

### Approach

Add them to the list of known tags. 

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
Is there a list of known tags that we could dynamically get from `roxygen2` instead of hardcoding it here ? cc @Hadley @gaborcsardi

**Comment by hadley** [comment]
I think this is probably the best way to get a list of all tags:

``` r
library(roxygen2)
methods <- as.vector(methods("roxy_tag_parse"))
prefix <- "roxy_tag_parse.roxy_tag_"
gsub(prefix, "", methods[grepl(prefix, methods, fixed = TRUE)], fixed = TRUE)
#>  [1] "aliases"           "author"            "backref"          
#>  [4] "concept"           "describeIn"        "description"      
#>  [7] "details"           "docType"           "encoding"         
#> [10] "eval"              "evalNamespace"     "evalRd"           
#> [13] "example"           "examples"          "examplesIf"       
#> [16] "export"            "exportClass"       "exportMethod"     
#> [19] "exportPattern"     "exportS3Method"    "family"           
#> [22] "field"             "format"            "import"           
#> [25] "importClassesFrom" "importFrom"        "importMethodsFrom"
#> [28] "include"           "includeRmd"        "inherit"          
#> [31] "inheritDotParams"  "inheritParams"     "inheritSection"   
#> [34] "keywords"          "md"                "method"           
#> [37] "name"              "noMd"              "noRd"             
#> [40] "note"              "order"             "param"            
#> [43] "rawNamespace"      "rawRd"             "rdname"           
#> [46] "references"        "return"            "returns"          
#> [49] "section"           "seealso"           "slot"             
#> [52] "source"            "template"          "templateVar"      
#> [55] "title"             "usage"             "useDynLib"
```

<sup>Created on 2022-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

There's not currently a way to get any docs about the tags. If you wanted to propose something in a roxygen2 issue, we could likely implement it, as it's a long standing request.

**Comment by kevinushey** [comment]
@hadley is there a way to make this work without needing to load roxygen2 (or other packages that might be defining and providing their own roxygen2 tags?)

**Comment by romainfrancois** [comment]
Keeping those as a comment for now

**Comment by hadley** [comment]
@kevinushey in principle you could do it by parsing the `NAMESPACE` instead

**Comment by kevinushey** [comment]
Good point (I forgot we discussed that). One other minor downside is we don't know how many arguments the tag accepts (so we don't know if we should include a space after auto-completing the tag)

**Comment by hadley** [comment]
We could probably come up with some extension registration mechanism if you wanted.

**Review by kevinushey — APPROVED** [review]

**Pull request merged**
