### PR TITLE
Update to RSConnect 1.0.2

### PR DESCRIPTION
**Pull request by dragonstyle**
### Intent

Update to version of rsconnect which contains the optional `appMode` flag that is used when statically publishing Quarto Manuscripts.

### Approach

Update r-packages.json

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

### CODE REVIEW

**Review by aronatkins — APPROVED** [review]
Confirmed that the rsconnect 1.0.2 CRAN release has also been mirrored to the Posit Package Manager. https://packagemanager.posit.co/client/#/repos/2/packages/rsconnect

**Review by petetronic — DISMISSED** [review]

**Comment by petetronic** [comment]
Do we need to check the renv version for this updated rsconnect version?

**Comment by aronatkins** [comment]
> Do we need to check the renv version for this updated rsconnect version?

An updated version of renv will come along automatically, as rsconnect requires renv >= 1.0.0, but it does not demand the latest renv 1.0.2. 

CC @kevinushey - This change will pull newer renv to anyone using new RStudio builds. Should we also demand renv 1.0.2?

**Comment by kevinushey** [comment]
> CC @kevinushey - This change will pull newer renv to anyone using new RStudio builds. Should we also demand renv 1.0.2?

I think so -- it makes sense to ask RStudio users to use the latest release of renv anyhow.

**Comment by kevinushey** [comment]
Thanks @dragonstyle -- we've decided to use a more targeted change here; rather than requiring a newer versions of 'rsconnect' universally, we'll try to only request a newer version of 'rsconnect' when attempting to publish a Quarto manuscript. We'll track this separately.

**Pull request closed without merging**
