### PR TITLE
Remove unnecessary rprojroot dependency

### PR DESCRIPTION
**Pull request by jmcphers**
Title says it all; fixes https://github.com/rstudio/rstudio/issues/4628.

### CODE REVIEW

**Comment by kevinushey** [comment]
There's also a couple packages missing from the dependency list that we might consider adding explicitly (ref: sort(tools::package_dependencies("rmarkdown", recursive = TRUE)$rmarkdown))
:

- glue
- magrittr
- stringi
- tinytex
- xfun

I believe these packages normally get auto-installed when e.g. rmarkdown is installed / updated, which is why we get away with not checking these. However, if someone were to somehow install rmarkdown but later remove one of these required packages, RStudio would fail to detect it.

**Comment by kevinushey** [comment]
There's also a couple packages missing from the dependency list that we might consider adding explicitly (ref: sort(tools::package_dependencies("rmarkdown", recursive = TRUE)$rmarkdown))
:

- glue
- magrittr
- stringi
- tinytex
- xfun

I believe these packages normally get auto-installed when e.g. rmarkdown is installed / updated, which is why we get away with not checking these. However, if someone were to somehow install rmarkdown but later remove one of these required packages, RStudio would fail to detect it.

**Comment by jmcphers** [comment]
Thanks, I didn't notice that rmarkdown had added more dependencies! Will update the PR.

**Comment by jmcphers** [comment]
I have updated the branch and fully synch'ed the dependency list with the current state of the rmarkdown package, including bumping required versions to those named by the package (or current versions where no version was stated). 

Note however that all of these dependencies are as of version 1.12 of the package, whereas RStudio formerly depended on version 1.10 of the package. I have bumped the dependency to rmarkdown 1.12 so we can use this dependency matrix as-is, but I think that this now-larger change doesn't meet the bar for the patch release any more (let me know what you think).

**Comment by kevinushey** [comment]
I think I agree with that.

How do you feel about taking this for v1.3, but taking the smaller PR (just removing `rprojroot`) for v1.2-patch?

**Comment by jmcphers** [comment]
Sounds good. Conveniently those are two separate commits!

**Pull request merged**
